### ISSUE TITLE
Video Block created on mobile shows invalid content message on web

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/gutenberg-mobile#1237] opened 2019-07-19 15:30 UTC
Steps to reproduce:
1. Create a new post or open an existing post
2. Add at least one video block, take a new video
3. Save the draft
4. Open the same post on the web

Mobile

![IMG_E21BB00604B1-1](https://user-images.githubusercontent.com/6520461/61547010-1df05880-aa10-11e9-8113-bfa449e4242d.jpeg)

Web:

<img width="1016" alt="Screen Shot 2019-07-19 at 10 22 01 AM" src="https://user-images.githubusercontent.com/6520461/61547023-247ed000-aa10-11e9-990c-19ac34be3b8e.png">

**Comment by maxme** [comment] 2019-07-23 13:35
I did a quick test and found that the local path was used in the block:

```
<!-- wp:video {"id":2} -->
<figure class="wp-block-video">
  <video src="///data/user/0/org.wordpress.android.beta/cache/VID_20190722_113956.mp4" controls="controls" width="300" height="150"></video>
</figure>
<!-- /wp:video -->
```

I tried the same experiment with Aztec and the correct (remote) url was set in the video shortcode.

**Comment by maxme** [comment] 2019-07-23 14:57
I wonder if this is linked to this one https://github.com/wordpress-mobile/WordPress-Android/issues/10203

I was able to upload a post with a video correctly once in Gutenberg. IMO this one needs some more investigation on the wpandroid side first.

**Comment by mchowning** [comment] 2019-07-29 14:14
This may also be related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152

**Comment by mchowning** [comment] 2019-11-18 21:19
I've seen this issue before, but in testing this now I think the issue has been resolved. Tested both Android and iOS. If someone else can double-check that the issue is fixed, I think we can close this.

On a related note, I still see #1152 (video added on web shows invalid block on mobile) occurring.

**Comment by Tug** [comment] 2019-11-20 15:59
Can confirm, (tested on WPAndroid only)

**Comment by Tug** [comment] 2019-11-20 16:06
Actually I can reproduce from a Jetpack site.
Also, it looks like the issue can be resolved from the block editor "Resolve" function. It seems to be missing a ="" in the video tag: 

![image](https://user-images.githubusercontent.com/230230/69255420-13a9bb00-0bb8-11ea-838f-77788606a075.png)

**Comment by SiobhyB** [comment] 2023-11-16 16:47
I tested on a Jetpack-connected site and am no longer able to reproduce this issue. Video blocks added via my phone displayed as expected on the web. It looks like there must have been a change to the way a value is assigned to the `controls` argument.

```
<!-- wp:video {"id":11} -->
<figure class="wp-block-video"><video controls src="https://example.testing.com/wp-content/uploads/2023/11/testing.mp4"></video></figure>
<!-- /wp:video -->
```

**Closed by SiobhyB** 2023-11-16 16:47 UTC
Labels: [Type] Bug, Jetpack
