### ISSUE TITLE
Focus on title when the editor loads

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#357] opened 2018-12-12 12:27 UTC
When gutenberg is opened in the apps, make the title focused. On iOS, there is no focus. On Android, the title has focus but the keyboard isn't up until you tap.

I think this was done initially for the previous demo, but it was disabled since it caused some layout issues with the toolbar on iOS

**Comment by hypest** [comment] 2018-12-12 12:55
> On Android, the title has focus but the keyboard isn't up until you tap.

I'm under the impression that that was by design and started before gutenberg-mobile. I'll try to find the relevant info.

**Comment by etoledom** [comment] 2018-12-17 06:48
Closed via #373 and #10654

**Comment by etoledom** [comment] 2018-12-17 06:49
Reopening to get updates on Android side.
cc @hypest

**Comment by marecar3** [comment] 2018-12-19 08:50
From @koke comment

> sounds good. I think we’ll want to standardize that across platforms during the beta, but for now, following Aztec is ok

iOS Aztec -> will focus title when new post or old post is opened
Android Aztec -> won't focus anything when new post or old post is opened

cc: @koke @etoledom @hypest

**Comment by marecar3** [comment] 2018-12-19 12:02
Final conslusion from @hypest's  chat message :

>@iamthomasbishop’s feedback is actually the latest one as he’s already taking into account Eli’s feedback:
• (Previously mentioned by @elibud ) Title should be focused right away when new post is created. (iOS)
• when an existing post is loaded, we should assume no block focus and keyboard should be hidden (iOS, Android)

> to me that reads: focus the title on enter but only for new posts

@etoledom

**Comment by mzorz** [comment] 2018-12-20 22:55
Closing via #8826

**Closed by mzorz** 2018-12-20 22:55 UTC
Labels: App Integration, Needs Android Dev
