### ISSUE TITLE
Content: "Link To" shows always the same list of posts and pages

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/gutenberg-mobile#3047] opened 2021-01-22 20:16 UTC
The option to link a text is currently showing the same results over and over when you try to search for a published post or page.

### Expected behavior
To see results related to what I typed. 

### Actual behavior
I see always the same posts and pages. In my case, two posts and one page.

It's apparently impossible to search for published posts or pages.

### Steps to reproduce the behavior
1. Start a post or page
2. Add some text to the body
3. Click the Link icon
4. Choose the Link To option
5. On the search field, type something

##### Tested on [device], Android [version], WPAndroid 16.4 (waiting for the user info)

Internal reference: p4a5px-2HH-p2

**Comment by hypest** [comment] 2021-01-26 11:48
I understand @mkevins probably has good context in this to have a look so, adding the ticket to the Gutenpages project board.

**Comment by mkevins** [comment] 2021-01-27 04:37
I believe this is caused by this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2922. Good news is that [a fix has been merged](https://github.com/WordPress/gutenberg/pull/27867) and is already in 16.6. Closing for now, but feel free to re-open if you encounter the issue in 16.6.

**Closed as completed by mkevins** 2021-01-27 04:37 UTC
Labels: [Type] Bug
