### ISSUE TITLE
Editor Doesn't Scroll When Typing Text Into Paragraph Block on iOS

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/gutenberg-mobile#4069] opened 2021-10-02 20:42 UTC
**Describe the bug**
When typing text into the paragraph block, the cursor can go behind the keyboard and out of the field of view. The editor should automatically scroll so that you can see what is being typed.

**To Reproduce**
1. Open the editor.
2. Insert content and position a paragraph block near the bottom of the field of view (just above the keyboard).
3. Type text until the text cursor moves out of view below the keyboard.

**Expected behavior**
The editor should automatically scroll so that the text your typing is within view.

**Screenshots**

https://user-images.githubusercontent.com/42454301/135731204-1b4560f1-be14-4590-a01a-4641f004d8ea.mov

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.0.1
 - Version WordPress for iOS 18.3

**Comment by antonis** [comment] 2021-10-04 07:14
I quickly tested this with two old installations on my device and I was able to reproduce this behaviour in [version `17.6`](https://github.com/wordpress-mobile/WordPress-iOS/releases/tag/17.6) but but not [in `16.8`](https://github.com/wordpress-mobile/WordPress-iOS/releases/tag/16.8).
The issue is not reproduced on the latest Android version.

**Comment by antonis** [comment] 2021-10-06 09:21
I tested [on `17.5`](https://github.com/wordpress-mobile/WordPress-iOS/releases/tag/17.5) and wasn't able to reproduce the issue.
Thus this was [introduced with `17.6`](https://github.com/wordpress-mobile/WordPress-iOS/releases/tag/17.6).
I did a quick investigation and I don't see something obviously suspicious in the changes introduced in this release on the [native iOS](https://github.com/wordpress-mobile/WordPress-iOS/compare/17.5...17.6) or [`gutenberg` side](https://github.com/WordPress/gutenberg/compare/rnmobile/1.54.0...rnmobile/1.55.2). Further investigation is needed to determine the commit that introduced this and come up with a fix.

**Comment by fluiddot** [comment] 2021-11-26 12:47
I investigated this issue further and debugged the `react-native-keyboard-aware-scroll-view` package, as the `KeyboardAwareFlatList` component is the one involved in scrolling the content by the position of the caret ([reference](https://github.com/WordPress/gutenberg/blob/96a0dafa1c06d3785e5616a775e82df0c07403ad/packages/components/src/mobile/keyboard-aware-flat-list/index.ios.js#L70-L80)).

As far as I checked, the issue is produced when taking the target ID from the native event sent by Aztec ([reference](https://github.com/WordPress/gutenberg/blob/96a0dafa1c06d3785e5616a775e82df0c07403ad/packages/react-native-aztec/src/AztecView.js#L172-L176)) after the selection changes. The expected value in the function in charge of updating the scroll ([`KeyboardAwareHOC#_refreshScrollForField`](https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/blob/e5ce378011e84be0b6ea8c91e93b568fe940b846/lib/KeyboardAwareHOC.js#L463-L517)) is a number, but we're sending a `ReactNativeFiberHostComponent` object instead ([reference](https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/blob/e5ce378011e84be0b6ea8c91e93b568fe940b846/lib/KeyboardAwareHOC.js#L478)), so the scroll never gets updated. Besides, this is only happening on iOS because on Android, the `handleCaretVerticalPositionChange` function is disabled ([reference](https://github.com/WordPress/gutenberg/blob/3356cc157f8f17c9c2bf7bbf1468642a490d24ee/packages/components/src/mobile/keyboard-aware-flat-list/index.android.js#L17-L19)) as this behavior is managed by the OS. 

<img width="1273" alt="Screenshot 2021-11-26 at 13 26 45" src="https://user-images.githubusercontent.com/14905380/143583246-89783c05-6da8-40b6-a2ff-d6b75d361fc8.png">

I'm not sure what change introduced this issue, but my gut feeling is that it has to do with the React Native upgrade to version `0.64.0` ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3430)), as the `react-native-keyboard-aware-scroll-view` package ([reference](https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view/pull/12)), as well as React, were both updated potentially causing a change in the events coming from the native side. However, per [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4069#issuecomment-935823230), looks like the issue was first introduced in `1.55.0 (17.6)`, and the upgrade was released in the next version `1.56.0 (17.7)` 🤔 .

<img width="256" alt="Screenshot 2021-11-26 at 13 05 10" src="https://user-images.githubusercontent.com/14905380/143583218-feb5147b-94f1-46be-a6bc-0af18193fd06.png">

In any case, taking the target ID from `event.nativeEvent.target` instead of `event.target` should be enough to address the issue. I'll open a PR with the fix as soon as possible.

**Closed as completed** 2021-11-26 16:18 UTC
Labels: [Type] Bug, [Pri] High
