### ISSUE TITLE
App review: Unable to focus on a block for editing

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#3085] opened 2021-02-02 08:34 UTC
> Had everything that would make it a good mobile editor but the cursor keep jumping up and down, the edits won’t register, I can’t see what I typed, update takes forever. I would be editing line (block) 15 and the cursor will jump to block 6, then back to 15, then to 10. The keyboard will also blink up and down. What I type for block 15 will end up in the middle of block 10. When clicking in a block, no matter where you are it’s automatically capitalised, not friendly with mobile editing, especially with how hard to finely control the cursor within a word.

Date of review on App Store Connect: Jan 18, 2021
Reported on the WPiOS app version 16,4

**Comment by hypest** [comment] 2021-02-03 16:24
👋 @reginabally , thanks for opening the ticket! I wonder, any info around reproduction steps or what your tests have shown so far if you did any? Thanks!

**Comment by hypest** [comment] 2021-02-03 16:25
In the meantime, can you take a quick look @dcalhoun to see if you perhaps reproduce? Thanks!

**Comment by dcalhoun** [comment] 2021-02-03 21:29
> Had everything that would make it a good mobile editor but the cursor keep jumping up and down, the edits won’t register, I can’t see what I typed, update takes forever. 

@hypest @reginabally in 16.4, I was able to create a scenario where swapping focus from one block to another would cause the scroll position to be incorrectly set so that the _previously focused block_ would be in view. This resulted in the cursor and any keyboard input to be in the _correct_ block, but it would not be visible as the _incorrect_ block was scrolled into view.

I do not know if this is exactly what the reporter was experiencing, but I could see how it could be interpreted as "the edits won’t register, I can’t see what I typed." That said, this issue was not reproducible in the latest 16.6 build. So, upgrading to 16.6 once it is released may resolve the issue for the user. This may have been fixed in WordPress/gutenberg#28352.

https://user-images.githubusercontent.com/438664/106809352-30050c80-6631-11eb-8239-83c99cee7a88.MP4

> I would be editing line (block) 15 and the cursor will jump to block 6, then back to 15, then to 10. The keyboard will also blink up and down. What I type for block 15 will end up in the middle of block 10.

I was unable to create a scenario that resulted in text entry showing up in the incorrect block. However, I was able able to produce an infinite loop of a blinking keyboard and focus swapping between two blocks. This was accomplished by quickly tapping between two different blocks. Once this loop begins, it is near impossible to exit outside of quitting the app. This still occurs in the latest 16.6 build.

https://user-images.githubusercontent.com/438664/106809979-f7b1fe00-6631-11eb-9f27-b76922b8b2b3.MP4

> When clicking in a block, no matter where you are it’s automatically capitalised, not friendly with mobile editing, especially with how hard to finely control the cursor within a word.

I was unable to reproduce "automatically capitalized" occurring regardless of where the cursor is positioned. From my testing, the autocapitalization only occurred if the cursor was placed at the beginning of a sentence (i.e. after a period and space).

I also did not find any difficultly long pressing and moving the cursor from word to word or within a word. It operated with the level of accuracy I would expect on iOS.

@hypest not familiar with the typical process for triaging an issue from an app review. Please let me know if you'd like me to update this issue's description or create new tickets for any of this information. Thanks!

**Comment by hypest** [comment] 2021-02-04 10:53
Thanks for the thoroughness in trying to reproduce the various issues mentioned in the user review!

About the auto-scrolling issue, good news that it's fixed in 16.6. The recommendation there @reginabally would be to inform the user that 16.6 has a fix that may address that part of their report and it's advised to update the app if possible.

>  >   What I type for block 15 will end up in the middle of block 10.
>
> I was unable to create a scenario that resulted in text entry showing up in the incorrect block.

The way I read it it sounds like the messed up auto-scrolling can still be the root cause, with the user involuntarily typing text in the wrong block. Since you can't reproduce anyway, I'd say let's wait for the user to upgrade to 16.6.

> I was able able to produce an infinite loop of a blinking keyboard and focus swapping between two blocks. This was accomplished by quickly tapping between two different blocks. Once this loop begins, it is near impossible to exit outside of quitting the app. This still occurs in the latest 16.6 build.

Infinite loop issues have been reported in other tickets as well, see [this one](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1696) and [that one](https://github.com/wordpress-mobile/gutenberg-mobile/issues/953). If none of those tickets feel relevant to you David and the issue at hand has different characteristics, let's create a new ticket to capture it with the steps to reproduce too.

For the subcases you can't reproduce David, let's wait for feedback from the user and the extra debugging it might happen with their help.

**Comment by reginabally** [comment] 2021-02-05 03:30
Hi @hypest, Sorry I didn't test this out because I was checking the app reviews for the monthly stats post and noticed this one that worth reporting. I've edited the app review response and let the user know this will be fixed in 16.6. I've also encouraged them to reach out to us so we can gather more information for troubleshooting.

And of course, thank you @dcalhoun for the thorough test results!

**Comment by dcalhoun** [comment] 2021-02-19 19:47
Leaving a note that WordPress/gutenberg#28004 appears to capture the issue mentioned in https://github.com/wordpress-mobile/gutenberg-mobile/issues/3085#issuecomment-772836828 that results in erroneous scrolling to the _previously focused_ block instead of the _currently focused_ block.

**Comment by dcalhoun** [comment] 2021-02-23 20:26
Here is a summary of the reported issues. There is still potential that I have misinterpreted the users description, but below is my best mapping of my understanding of the user reports to existing issues from my attempts to reproduce.

| Name | Reproduced | Resolved in 16.7 | Related Issues | User Description |
| ---| --- | --- | --- | --- |
| Incorrect Focus Scrolling | ✅ | ✅ | Possibly duplicative of WordPress/gutenberg#28004 and fixed by WordPress/gutenberg#28352. | "Had everything that would make it a good mobile editor but the cursor keep jumping up and down, the edits won’t register, I can’t see what I typed, update takes forever." |
| Jumping Cursor / Focus Loop | ✅ | ❌ | Possibly duplicative of #953. | "I would be editing line (block) 15 and the cursor will jump to block 6, then back to 15, then to 10. The keyboard will also blink up and down. What I type for block 15 will end up in the middle of block 10." |
| Erroneous Capitalization and Cursor | ❌ | ❌ | No existing issues. | "When clicking in a block, no matter where you are it’s automatically capitalised, not friendly with mobile editing, especially with how hard to finely control the cursor within a word." |

@reginabally in terms of next steps:

1. The _Incorrect Focus Scrolling_ issue is hopefully resolved for the user by upgrading to the latest WordPress iOS 16.7.
2. The _Jumping Cursor / Focus Loop_ issue is known, but has not been prioritized or fixed at this time. @hypest do you believe this will be prioritized at some point?
3. The _Erroneous Capitalization and Cursor_ may need more information from the user for us to reproduce. Have they provided any further information about steps to recreate or specific post content used?

Thanks!

**Comment by hypest** [comment] 2021-02-24 13:10
Thanks for the summary David, awesome work there!

> The Jumping Cursor / Focus Loop issue is known, but has not been prioritized or fixed at this time. @hypest do you believe this will be prioritized at some point?

I don't think it we'll prioritize it more than it currently is.

All in all, What I'd suggest at this stage is to move the last issue into its own ticket to investigate there, and close this one as it's too general to be practical. David, can you create the new ticket, ping folks in that one, and close this one? Thanks!

**Comment by dcalhoun** [comment] 2021-02-24 16:42
Closing in favor of newly created WordPress/gutenberg#29304 and pre-existing issues mentioned in https://github.com/wordpress-mobile/gutenberg-mobile/issues/3085#issuecomment-784487428.

**Closed as completed by dcalhoun** 2021-02-24 16:42 UTC
Labels: [Type] Bug, Writing Flow, [OS] iOS, [Pri] High
