### ISSUE TITLE
Paragraph Block Causing Crash on Android App 

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/gutenberg-mobile#2524] opened 2020-07-30 17:29 UTC
**Describe the bug**
When a specific paragraph block is copy and pasted into a page or post that page or post can no longer be edited in the Android app. It crashes. This same text does not crash the iOS app

**To Reproduce**
1. Open a new page or post on a Simple WordPress.com site
2. Paste in this text to create a new block
```
<!-- wp:paragraph {"align":"center","fontSize":"large"} -->
<strong><span style="text-decoration:underline;"><span class="uppercase">Test Content </span></span></strong>
<!-- /wp:paragraph -->
```
3. Save your draft
4. Try to edit this page or post in the Android app.

**Expected behavior**
The text above should be editable in iOS and Android block editors in the app. It should not crash just Android apps.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS:  Android 10
 - Version alpha-235

User reported on 
- Android device name: OnePlus HD1903
- WordPress - 15.3 

#3185486-zen

**Comment by hypest** [comment] 2020-07-31 11:42
Reproduced and looks like the underling issue is the one also reported in https://github.com/wordpress-mobile/gutenberg-mobile/issues/2472. Good thing is that now we have steps to reproduce, which is good.

**Comment by guarani** [comment] 2021-03-24 15:32
Added an Android label since it says above that this crash doesn't affect iOS.

**Comment by AmandaRiu** [comment] 2021-08-06 00:28
Tested on a Pixel 4 running Android 11 and WPAndroid v17.9. **Unable to reproduce crash**. I did some digging and the crash was last reported in Sentry for v15.7 of WPAndroid. With further digging I found this Aztec PR that implemented the fix: https://github.com/wordpress-mobile/AztecEditor-Android/pull/923

I've marked the associated Sentry events as resolved, and am closing this ticket.

**Closed by AmandaRiu** 2021-08-06 00:28 UTC
Labels: [OS] Android, [Type] Crash
