### ISSUE TITLE
Single digit numbers are moving while List is editing

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#901] opened 2019-04-19 22:34 UTC
Scenario :

1. Create a list block with 10 rows or more
2. Make sure that numbering format is selected
3. Create a paragraph block
4. Change focus between list block and start editing List Block

![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/28219092/56446911-6d20d300-62d3-11e9-8028-39aba98df307.gif)

Result: Numbers from 1 to 9 will move from left to right and back
Expected: List Block should be broken

**Comment by koke** [comment] 2019-04-30 11:17
Seems like a duplicate of #846

**Closed by koke** 2019-04-30 11:17 UTC
Labels: Android, Blocks, bug
