### ISSUE TITLE
Undo does not work with links that open in a new tab

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#2495] opened 2020-07-20 21:35 UTC
**Describe the bug**
On Android only, it is extremely difficult to undo the application of a link that opens in a new tab.

**To Reproduce**
1. Create a paragraph block with some text
2. Highlight a word of the text and add a link to it, **with "Open in new tab" enabled.** (This is important, I do not observe this bug if "Open in new tab" is not enabled).
3. Close the link bottom sheet
4. Tap the undo button slowly to remove the link
5. Observe that the link is not removed
6. Observe that no matter how many times you _slowly_ tap the undo button, the link remains. If you tap the undo button a bunch of times very quickly, however, it is possible to remove the link. 

**Expected behavior**
Tapping the undo button a single time should be able to remove links that open in new tabs.

**Screenshots**
![remove_link mp4](https://user-images.githubusercontent.com/4656348/87988932-252cc500-caaf-11ea-8bef-0de41a617e76.gif)

**Smartphone:**
 - Device: Pixel 1
 - OS: Android X
 - Version 15.2.1

**Additional context**
I wonder if there might be some connection between this and https://github.com/wordpress-mobile/gutenberg-mobile/issues/2091

**Comment by designsimply** [comment] 2020-08-29 15:30
Duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/1160.

**Closed by designsimply** 2020-08-29 15:30 UTC
Labels: Writing Flow, [OS] Android, [Pri] Medium, [Status] Duplicate, [Type] Bug
