### ISSUE TITLE
Right alignment collapses empty text field and hides placeholder

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#2338] opened 2020-05-29 19:58 UTC
**Describe the bug**
On some iPhone simulators, I noticed that setting right alignment on a Paragraph Block with no text (so the placeholder should be showing) would cause the text to be given no height, such that the placeholder would not be shown. As soon as text is added, the expected height would be applied and the text would be displayed.

![Kapture 2020-05-29 at 15 53 02](https://user-images.githubusercontent.com/4656348/83299604-81b4e780-a1c4-11ea-9666-8cb9372f4040.gif)

**To Reproduce**
1. Add an empty paragraph block
2. Observe the placeholder
3. Apply right alignment
4. Observe the placeholder is no longer visible and the block's height has shrunk slightly
5. Begin typing
6. Observe the block un-shrinks and the text is visible

**Expected behavior**
The placeholder text should be visible when right alignment is applied.

**Smartphone (please complete the following information):**

I could recreate this issue with the 1.29.0 release code (553babc6) on an (i) iPhone  11 13.0 simulator, (ii) iPhone X 13.0 simulator, and an iPhone Xs 12.4 simulator. I could **not** recreate this issue with an (i) iPhone 11 13.4 simulator and an (ii) iPhone Xr 13.4 physical device. So it appears the issue might only occur on OS <13.4.

**Comment by mchowning** [comment] 2020-05-29 21:27
Any thoughts on this one @SergioEstevao ?

**Comment by SergioEstevao** [comment] 2020-06-19 15:51
I investigated this, and the issue is related to way we implement typing attributes in Aztec.

In order to show the current format active, we use a `String(.zeroWidthSpace)`, this works fine for left aligned and centered strings, but it looks that the UITextView layout system isn't unable to display this correctly in right alignment mode, and it make the UITextView collapse in size.

**Comment by hypest** [comment] 2021-06-24 11:31
Closing as I can't replicate on an iPhone 12 simulator running iOS 14.4, demo app from develop 9bf53198. Feel free to reopen if issue actually still persists.

**Closed by hypest** 2021-06-24 11:31 UTC
Labels: HACK week, Writing Flow, [OS] iOS, [Pri] Medium, [Status] Needs iOS Dev, [Type] Bug
