### ISSUE TITLE
[GlobalStep] [iOS] "Greyed Out Password field " and Magic link tool tip is not displayed under account details upon completing Sign Up

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2237] opened 2020-05-07 17:22 UTC
h2.Environment:
iPad Air 2(v13.3.1), iPad(6th Gen)-v12.4
 
Steps To Reproduce:
 1. Install and launch the application.
 2. Tap on "Sign Up for WordPress.com".
 3. Continue with the any option(Email/Google/Apple).
 4. Add your account and complete the sign up.
 5. Observe that on the Sign up page only Name and Username is displayed and Password field is missing. 
   
 h2. Actual Result:
"Greyed Out Password field " and Magic link tool tip is not displayed under account details upon completing Sign Up
 
 h2. Expected Result:
"Greyed Out Password field " and Magic link tool tip shouold display under account details upon completing Sign Up

![#2237](https://user-images.githubusercontent.com/41110392/81325091-81d63180-90b5-11ea-9ed9-fd3eafb8b23c.png)

**Comment by ScoutHarris** [comment] 2020-05-07 18:21
It's not clearly stated in the description, but I'm assuming the Password field did not display on Google or Apple accounts. This is by design, and has been this way for some time. You should see the Password field via the Email sign up flow. 

I'm closing this as a non-issue. But if you experience something different that what I explained please feel free to reopen.

**Closed by ScoutHarris** 2020-05-07 18:21 UTC
