### ISSUE TITLE
Top Bar Too Small on Android

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#2685] opened 2020-10-01 15:50 UTC
**Describe the bug**
Top bar on Android seems to be too small on my system, causing the black info block to be cut into by the notch. 

**To Reproduce**
1. Run Pixel 3 XL emulator with Android 9 (Pie, API 28) 
2. Add block

**Expected behavior**
Should extend top bar to the bottom of the notch.

**Screenshots**
![topBarIssue](https://user-images.githubusercontent.com/13263478/94832711-df0bb000-03d3-11eb-8e36-c1b770fd5662.png)
[PR #25658](https://github.com/WordPress/gutenberg/pull/25658) (unrelated to this issue) has a gif that shows this behaviour as well.

Seems to be an intermittent issue as sometimes the bar does extend:
![topBarCorrect](https://user-images.githubusercontent.com/13263478/94833781-27779d80-03d5-11eb-8cff-448283bc33e7.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3XL
 - OS: Android 9
 - Version: API 28

**Additional context**
@Tug I believe that your team is working on this, and perhaps this is a bug that's already being looked into.

**Comment by etoledom** [comment] 2020-10-02 10:19
I haven't been able to reproduce this, but I saw it happening on the gif from this PR: https://github.com/WordPress/gutenberg/pull/25658

**Comment by Tug** [comment] 2020-10-02 10:46
@etoledom Could this piece of code be related https://github.com/WordPress/gutenberg/pull/20238/files#diff-f2a9744b0d8b570033a66a2f59c56610R115 ?

CCing @lukewalczak since he's touched that code last

**Comment by lukewalczak** [comment] 2020-10-02 10:52
I will investigate that.

**Comment by lukewalczak** [comment] 2020-10-02 11:05
At first glance, I think it's reproducible only on the demo app _(on your screenshots/gifs there is no navigation bar with back button, username and publish/update button)_. Are you able to reproduce it on the production app?

**Comment by etoledom** [comment] 2020-10-02 11:35
> Are you able to reproduce it on the production app?

I have only seen it on the demo app so far. I agree that, at first sight, this seems like it shouldn't happen on WPAndroid.

> Could this piece of code be related https://github.com/WordPress/gutenberg/pull/20238/files#diff-f2a9744b0d8b570033a66a2f59c56610R115 ?

Makes sense. Visually, it l looks like that the system's Status bar is smaller than expected. Might that by an Android bug?
Or is it expected that the status bar won't always fully cover the phone's notch?

**Comment by lukewalczak** [comment] 2020-10-02 14:47
> Could this piece of code be related WordPress/gutenberg#20238 (files) ?


Cannot agree at this point, please notice that mentioned file/changes are related to setting `maxHeight` in `BottomSheet`

**Comment by etoledom** [comment] 2020-10-02 17:22
> Cannot agree at this point, please notice that mentioned file/changes are related to setting maxHeight in BottomSheet

Oh that's right! I completely didn't notice that important bit of info 👍

**Comment by lukewalczak** [comment] 2020-10-05 11:51
I'm not able to reproduce it even on the demo app. Do I have to cover some specific steps?

**Comment by SiobhyB** [comment] 2024-01-19 11:06
I haven't been able to reproduce the reported issue. As three years have passed since the original report, with no additional reports in the meantime, I'll go ahead to close this issue as non-actionable.

**Closed as completed by SiobhyB** 2024-01-19 11:06 UTC
Labels: [OS] Android
