### ISSUE TITLE
Selected blocks no longer have left/right borders on wide viewports

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1193] opened 2019-07-04 04:53 UTC
I believe this is a regression in the latest release, as I can’t reproduce in WPiOS 12.7.4.

iPad Pro 10.5”
![B5C8BD92-8DDA-4737-AE3C-BAF2D1C44507](https://user-images.githubusercontent.com/1200432/60640199-0603bc80-9df4-11e9-8d09-89e8fb4aed95.jpeg)

iPhone Xs Max (landscape)
![8E54D1CF-F95B-4854-8DC9-3B5A92799AF2](https://user-images.githubusercontent.com/1200432/60640582-cccc4c00-9df5-11e9-9c51-67698d0332ce.png)

Note: this applies to every block type on the canvas.

**Comment by guarani** [comment] 2020-03-13 19:36
| ![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-03-13 at 16 31 06](https://user-images.githubusercontent.com/1898325/76653873-6b45ab00-6548-11ea-8123-6394a378c9b5.png) |
|-|

@marecar3, I wonder if this issue can be closed since I'm not seeing the issue on the current Gutenberg version. The above screenshot shows the borders displaying correctly.

**Comment by iamthomasbishop** [comment] 2020-03-13 19:49
@guarani I think this was fixed alongside some recent work on InnerBlocks. Let's do a thorough double-check and then close if we're not seeing the issue anywhere.

**Comment by marecar3** [comment] 2020-03-13 20:36
Thanks, @guarani!
Agree with @iamthomasbishop, if we are sure that it's done we can close it.

**Comment by guarani** [comment] 2020-03-13 22:11
I retested on the two devices shown in the original post and this appears fixed.

| Device | Screenshot |
|--|--|
| iPhone Xs Max | <img width="1048" alt="iphonexsmax" src="https://user-images.githubusercontent.com/1898325/76657315-553be880-6550-11ea-8c7a-a4311e4baefb.png"> |
| iPad Pro 10.5" | <img width="1202" alt="ipad10-5" src="https://user-images.githubusercontent.com/1898325/76657344-6258d780-6550-11ea-9c7b-c6bff5730103.png"> |

**Comment by guarani** [comment] 2020-03-16 15:00
> Agree with @iamthomasbishop, if we are sure that it's done we can close it.

I've added a screenshot above from Android which also shows the left/right borders. I'm closing this now as I'm unable to reproduce.

**Closed by guarani** 2020-03-16 15:00 UTC
Labels: HACK 7/2019, bug
