### ISSUE TITLE
Video disappears from video block after turning off device screen

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#974] opened 2019-05-10 17:27 UTC
Steps to reproduce : 

1. Create a new post
2. Create new video block
3. Upload video
4. Create a  new block (paragraph/heading ..)
5. Turn off the screen with a power button
6. Turn on the screen with a power button

Result: Last video frame on video block is lost, so it seems that video block is empty, but it isn't as if you click on it, you will see video controls and if you click on the play button, the video will show up.

Video:

![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/28219092/60456556-8b764980-9c07-11e9-9c98-92a9e4ec20f5.gif)

**Comment by marecar3** [comment] 2019-07-01 17:47
I can confirm that this one is still reproducible on Nexus 5x 8.1.

**Comment by jhnstn** [comment] 2022-02-21 20:16
I'm unable to reproduce this on 
- WPAndroid 19.2-rc3
- Android 12 / Pixel 6

https://user-images.githubusercontent.com/744755/155021069-9dca131f-28ac-4cf7-823b-f66335e36868.mp4

**Comment by hypest** [comment] 2022-03-03 13:16
Can't reproduce either. Tried Pixel 2XL/Android11/WPAndroid v19.3-rc-1, and GalaxyNote20Ultra/Android12/WPAndroid v19.3-rc-1. Closing this as not happening anymore but happy to reopen if we get updated repro steps. Thanks!

**Closed by hypest** 2022-03-03 13:16 UTC
Labels: [Type] Bug, Blocks, [OS] Android, Media, [Status] Unreproduced
