### ISSUE TITLE
[GlobalStep] iOS/Android - Quote line overlap when using column blocks with other media.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#2181] opened 2020-04-24 11:53 UTC
### Description
If the user selects to create a column block and within it uses media such as an image followed by a quote, the line that precedes the quote when published can often be seen to overlap the edge of the media block that went before it, sometimes appearing over and sometimes under. This has been observed when viewed in mobile landscape preview and published view on both mobile and desktop.

### Expected behavior
All block editor added content appears tidily after creating a post.

### Actual behavior
In column blocks quotes after media can result in minor clipping.

### Steps to reproduce the behavior
1.	Install WordPress 14.7
2.	Login to a valid account.
3.	Ensure block editor is enabled.
4.	Create a new post.
5.	Add a column block.
6.	Add media such as an image as the first block within the column block.
7.	Add a quote as the second block.
8.	Preview in landscape.
9. 	Publish and view in landscape on mobile and on desktop.

##### Tested on the following:
iPhone 6S Plus (13.4.1)
Samsung Galaxy S7 Edge (8.0)

#### Please see the attached screenshots for reference.
<img width="270" src="https://user-images.githubusercontent.com/60415523/80209653-57529600-862a-11ea-89a2-3cc5942d200a.jpg" />
<img width="270" src="https://user-images.githubusercontent.com/60415523/80209655-5883c300-862a-11ea-8c93-7a08f54ae921.jpg" />

#### Submitted by:
Oliver Howe

**Comment by pinarol** [comment] 2020-04-27 15:14
Hi @wptester9845 . This doesn't seem like a problem about the native editor because the issue seems like happening on the preview page. Preview is not done by the editor, it is a WebView which just displays the output web page within an internal browser. This issue should be reproducible on system browser as well, so I suggest moving this to https://github.com/WordPress/gutenberg repo.

**Comment by pinarol** [comment] 2020-04-28 15:43
Closing this one due to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2181#issuecomment-620049972 Let me know if I can help further.

**Closed by pinarol** 2020-04-28 15:43 UTC
