### ISSUE TITLE
[GlobalStep] iOS- Option to switch from Classic Editor to Block Editor Missing

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#1912] opened 2020-02-14 14:07 UTC
### Description
While if a user types some content while in the Block Editor before switching to the Classic editor then it is possible to switch back to the Block Editor. If the user does not type anything while in the Block Editor before switching to the Classic Editor, the option to switch back to the Block Editor disappears.

### Reproduction Rate
4/4 100%

### Expected behavior
The button to switch back to the Block Editor should be present

### Actual behavior
The button to switch to the Block Editor disappears.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Press “Add new”.
4. Access the Meatball menu.
5. Select the option to switch to Classic Editor.
6. Access the Meatball menu again.
##### Tested on the following
iPhone SE (12.0.1)

#### Please see the attached video for more information
[iOSSwitchEditorEmptyPost.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4204764/iOSSwitchEditorEmptyPost.zip)

### Submitted by:
Luis Pimenta

**Comment by SergioEstevao** [comment] 2020-05-18 10:23
Duplicate of #1911

**Closed by SergioEstevao** 2020-05-18 10:23 UTC
Labels: [Status] Duplicate
