### ISSUE TITLE
Proposal: add a new default block (para) when tapping Enter on Image caption

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#426] opened 2018-12-20 22:38 UTC
I labelled this issue `Writing Flow`, because of the following:

Imagine I'm writing, hit enter, get a new block, keep writing, all looks good. Decide to insert an image and add a caption. I expect that adding a caption and hitting ENTER gets me a new Paragraph block to keep writing. Instead, it dismisses the keyboard and no new block is added, so I need to figure out what happened for a second and then if I want to keep writing I need to add a block myself.

I think we could try making it **add a new default block**, to _keep the writing flow going_.

On the Web, ENTER does not have a special treatment but only adds a new line to the caption:
![gutenbergwebcaption](https://user-images.githubusercontent.com/6597771/50314703-ac0e5b80-048e-11e9-9bb7-e421d3dde1f7.gif)

wdyt?

**Comment by koke** [comment] 2018-12-21 06:13
Possibly a duplicate of #324

**Comment by koke** [comment] 2018-12-21 14:02
Looking at https://github.com/WordPress/gutenberg/issues/2173 and https://github.com/WordPress/gutenberg/pull/2664 I'm not sure that behavior on the web is intentional, but they postponed the fix and it never happened.

**Comment by mzorz** [comment] 2018-12-21 14:08
> I'm not sure that behavior on the web is intentional, but they postponed the fix and it never happened.

nice catch !

**Comment by mchowning** [comment] 2019-04-12 00:11
Any update or conclusion on this? 

I'm working on [adding styling to the image caption]( https://github.com/WordPress/gutenberg/pull/14883), and I'm going to need to do some custom work to get the Enter key working, so I would like to implement it so it has our preferred behavior. Now I just need to figure out what that is! 😄

**Comment by hypest** [comment] 2019-04-12 08:07
👋 @mchowning , even though I personally like the proposal in this ticket, I think that for the time being, mirroring what the web side does is a good compromise. So, when tapping Enter while in the caption, the focus should stay in the caption in a new line inside it. Do you think that might be problematic perhaps?

**Comment by SergioEstevao** [comment] 2020-05-03 14:14
@mchowning I'm thinking on closing this issue, because it reflects the behaviour on the web. What do you think?

**Comment by mchowning** [comment] 2020-05-04 12:43
It seems like we still want a change along these lines according to @hypest 's [comment above](https://github.com/wordpress-mobile/gutenberg-mobile/issues/426#issuecomment-482480689) and @iamthomasbishop 's [more recent comment about this](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1651#issuecomment-561855158). 

With that said, this issue has been open for well over a year now with virtually no movement toward actually implementing it. I'm not sure how to best handle old issues like this that seem to be very low priority. As much as I would like to close this in order to clean up our issues list, I'm not sure that is the best approach since it seems like it's still a desired improvement. I would lean towards keeping this open myself, but I do not feel strongly about that.

**Comment by iamthomasbishop** [comment] 2020-05-06 13:39
@mchowning @SergioEstevao I still agree with the sentiment behind the issue (I still expect enter on caption to create a new block, however rare the occurance), and my feelings about keeping open vs. closing (is there a "dormant" status? 😆) are not strong. Considering it is low priority and I'm not aware of any specific user feedback — not to mention it's been dormant for over a year — perhaps we should close it and we can re-open if we end up tackling in the future?

**Comment by SergioEstevao** [comment] 2020-06-03 16:48
After this PR: https://github.com/WordPress/gutenberg/pull/22290, the behaviour on the web changed to:
 - If you press Enter inside a caption it creates a new paragraph block after the image block
- If you press Shift+Enter it inserts a newline (`br`) in the caption.

@iamthomasbishop Am I correct to assume that we want in mobile that Enter creates a new paragraph block?

**Comment by iamthomasbishop** [comment] 2020-06-04 12:42
> Am I correct to assume that we want in mobile that Enter creates a new paragraph block?

I think so — it seems that was the original proposal by @mzorz and now web has the desired behavior, so we should match it 😄

**Closed** 2020-06-08 21:56 UTC
Labels: Writing Flow, [Type] Enhancement
