### ISSUE TITLE
A gif image can't be added to the post on iOS

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/gutenberg-mobile#6366] opened 2023-11-09 14:44 UTC
**Describe the bug**
When a gif image from the device is added to the post on iOS, the post can't be updated, and it always shows an error message that states the upload is in progress.

**To Reproduce**
1. Launch the WP/JP app on an iOS device.
2. Log in.
3. Edit your post or create a new one.
4. Add an Image block.
5. Tap on the block and select "Choose from the device"
6. Select a GIF image.
7. Update the post.
8. Notice that you see an error message even if the GIF image is already uploaded.

**Expected behavior**
After a GIF image from the device is added to a post on iOS, the post should be able to be updated.

**Screenshots**

https://github.com/wordpress-mobile/gutenberg-mobile/assets/2471769/28569bb0-c312-4854-bad7-3eace6a1b220

**Smartphone (please complete the following information):**
 - Device: iPad mini 6th gen
 - OS: iPadOS 17.1
 - Version 23.6

**Comment by tiagomar** [comment] 2023-11-09 18:54
Couldn't reproduce it on
* iPhone 13, iOS 16.6.1
* iPad, iPadOS 17.0

**Comment by twstokes** [comment] 2023-11-09 22:50
I was able to reproduce with:
- iPhone 15 in Simulator running iOS 17
- Built using Xcode 15
- Built from this [WPiOS commit](https://github.com/wordpress-mobile/WordPress-iOS/commit/1511635f090a05a13b9983e0aa598332f62402f0) (currently `trunk`)

I can also confirm that uploading media in the WPiOS app via the "Media" view (outside the editor), there were no issues.

**Comment by derekblank** [comment] 2023-11-09 23:10
I was able to reproduce on an iPhone SE running iOS 16.6.1, but with a slightly different experience:

1. Upload gif and hit "Publish"
2. Returns to Posts screen and the post hangs indefinitely in drafts with the upload progress bar around ~95% 

I did not see the "Uploading Media" dialog like in the video above, but it is present in the draft post:

![IMG_4287-2](https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/79965ca5-3f27-4972-9a04-6ed2edeeb06a)

**Comment by derekblank** [comment] 2023-11-10 00:22
Replicated the same behavior above when debugging locally. The error output so far:

```
2023-11-10 10:20:18:533 WordPress[98177:18989117] Could not find image file:///Users/derekblank/Library/Developer/CoreSimulator/Devices/3F6F476A-9B9B-4577-A96F-146E73030824/data/Containers/Data/Application/715E9599-AF41-4469-BF48-85041FBE4617/tmp/-466378314.png
2023-11-10 10:20:18:584 WordPress[98177:18970961] Unable to download image for attachment with url = Optional(http://localhost:8081/symbolicate). Details: Optional("The operation couldn’t be completed. (WordPress.ImageDownloaderError error 0.)")
2023-11-10 10:20:18:636 WordPress[98177:18970961] Unable to download image for attachment with url = Optional(https://i0.wp.com/localhost:8081/assets/gutenberg/node_modules/react-native/Libraries/LogBox/UI/LogBoxImages/close.png?platform=ios&hash=369745d4a4a6fa62fa0ed495f89aa964?quality=80&w=16). Details: Optional("The operation couldn’t be completed. (WordPress.ImageDownloaderError error 0.)")
2023-11-10 10:20:18:646 WordPress[98177:18992108] Failed to get size for image file:///Users/derekblank/Library/Developer/CoreSimulator/Devices/3F6F476A-9B9B-4577-A96F-146E73030824/data/Containers/Data/Application/715E9599-AF41-4469-BF48-85041FBE4617/tmp/-466378314
2023-11-10 10:20:18:652 WordPress[98177:18970961] Unable to download image for attachment with url = Optional(http://localhost:8081/symbolicate). Details: Optional("The operation couldn’t be completed. (WordPress.ImageDownloaderError error 0.)")
```

**Comment by derekblank** [comment] 2023-11-10 00:24
Possibly related:

* https://github.com/wordpress-mobile/WordPress-iOS/pull/13910
* https://github.com/wordpress-mobile/WordPress-iOS/issues/13929

**Comment by derekblank** [comment] 2023-11-10 06:30
Further investigation details:

- When adding the GIF on iOS, the file actually uploads successfully to the server, a valid URL is created, and the GIF appears in WordPress Media Library.
- When running locally, warnings are thrown from `RNImage.getSize` in the native Image component [here](https://github.com/WordPress/gutenberg/blob/57211ac3d2d05e67378cb471dd77140cf680b1e0/packages/components/src/mobile/image/index.native.js#L69-L82): `Failed to get size for image`. 
- When uploading a GIF, there are two image files created and returned from the server: the animated GIF, and a static image from the first frame.
- On Android, (where the GIF uploads successfully), the static image of the GIF is displayed in the Editor Image Block as a preview. Tapping on this static image displays the animated GIF. (Video example below.) On iOS, it's the opposite: the animated GIF is displayed in the Image Block, and tapping it displays the static file. **On iOS It seems like the static and animated image URLs are inverted somehow.**
- It's not possible to publish a post with a GIF on iOS. Even after removing an Image block that contained a GIF, it is still not possible to publish the post. There is likely something that is triggered in the state of the Image component that prevents this.

Android (working) | iOS (not working)
-|-
<video src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/f32f13af-939b-49a8-ace5-9912ebfdda8f" /> | <video src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/42815908-b1c0-4d1a-ba0a-23a445244e5e" />

**Comment by geriux** [comment] 2023-11-10 10:36
I'm currently debugging but wanted to share that we recently changed quite a few things [related to Media](https://github.com/wordpress-mobile/WordPress-iOS/pulls?q=is%3Apr+label%3AMedia+is%3Aclosed) over WordPress iOS.

So far what I'm seeing is that for local GIFs, the progress value never reaches `1.0` when they're actually successfully uploaded. For GIFs uploaded from the free library, they do reach that value and are marked as `uploaded` correctly.

**Comment by kean** [comment] 2023-11-10 12:40
**RCA**

- `ItemProviderMediaExporter` doesn't contribute progress to the overall uploads progress when it comes to GIFs

**Comment by kean** [comment] 2023-11-10 12:49
I opened a PR with a fix https://github.com/wordpress-mobile/WordPress-iOS/pull/22025

**Closed as completed** 2023-11-10 15:05 UTC
Labels: [Type] Bug, [OS] iOS, GIF Support
