### ISSUE TITLE
[GlobalStep] iOS – The Block Editor allows an empty post

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#1915] opened 2020-02-14 14:38 UTC
### Description
While on Android, attempting to publish an empty post causes an error message to appear stating “Can’t publish an empty post”, on iOS attempting to publish an empty post causes the Block Editor to be dismissed and the error message stating “Post failed to upload” is displayed along a retry button.
However, if the user selects the “Start writing...” block before pressing the publish button then an empty post will successfully be published.

### Reproduction Rate
4/4 100%

### Expected behavior
An error message stating “Can’t publish an empty post” should be displayed.

### Actual behavior
An empty post is successfully published.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Press the “Add new” button.
4. Select the “Start writing...” block.
5. Press the Publish button.
6. Confirm the Publish.
##### Tested on the following
iPhone SE (12.0.1)

#### Please see the attached video for more information
[iOSEmptyPost.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4204892/iOSEmptyPost.zip)

### Submitted by:
Luis Pimenta

**Comment by mchowning** [comment] 2020-07-20 13:06
Is this resolved by https://github.com/wordpress-mobile/gutenberg-mobile/pull/2393 @SergioEstevao ?

**Comment by guarani** [comment] 2020-07-20 14:16
I did a quick test on the 15.3 WP beta for iOS and I can't reproduce this issue anymore (cc @SergioEstevao).

**Comment by SergioEstevao** [comment] 2020-07-20 14:20
Yes, this was resolved in two parts, first, there was a previous PR that checked always if the post was empty or not before publishing, and now with https://github.com/wordpress-mobile/gutenberg-mobile/pull/2393 the Publish button will be disabled until we have a non-empty post.

**Closed** 2020-07-20 14:20 UTC
Labels: HACK June 2020, Writing Flow, [OS] iOS, [Pri] Medium
