### ISSUE TITLE
Cut&Paste menu doesn't work fine on iOS

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#134] opened 2018-09-06 14:20 UTC
I noticed that the cut and paste menu does't work fine on iOS when there is a bit of text in the input field.

Actually there are different type of errors with the context menu, the animated GIF at the bottom can show details - some of the errors are briefly listed here:
- Selecting `cut` doesn't always work as expect. Often the menu remains on the screen and no action is taken.
- If you select a word, and the `Paste` nothing happens.

![ios-cut-and-paste-menu](https://user-images.githubusercontent.com/518232/45163397-aac36680-b1f0-11e8-8273-4d0b401bd0ac.gif)

Btw, didn't test in ReacNativeAztec to check if it's a problem of the react native component, or its integration here.

**Comment by diegoreymendez** [comment] 2018-10-24 12:40
I spent most of yesterday trying to figure this one out without much success.

One of the things I noticed is also present in the GIF above.  You can see how the block becomes de-focused sometimes even if the caret is still in the text view.  I tried fixing that problem by not letting the block ever be de-focused but it seems to be unrelated to the cut, copy / paste iOS issue.

So far no hints as to what the problem is.

**Comment by diegoreymendez** [comment] 2018-10-24 15:16
It seems this issue was fixed by [this PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/185).

After merging the latest from master I can no longer reproduce it.

**Closed by diegoreymendez** 2018-10-24 15:16 UTC
Labels: Writing Flow, bug
