### ISSUE TITLE
Keyboard hide button is not working on the Image Caption

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#829] opened 2019-04-05 10:42 UTC
Steps to reproduce:

1. Add an image block, add an image
2. Add a caption text
3. Tap keyboard down button
4. Keyboard is not hidden

Expected behavior:

4. Keyboard is hidden

Note: This only happens when there's a text in caption field. If the caption is empty then keyboard closes without a problem.

![image-caption-keyboard-close](https://user-images.githubusercontent.com/5032900/55622328-92c4bd00-57a8-11e9-85dc-549932757776.gif)

**Comment by mchowning** [comment] 2019-04-07 20:00
I was unable to recreate this on Android, do you know if this was only an issue on iOS? (I'm working on a  linux machine, otherwise I would check myself).

Also, it's worth taking another look at this once #574 is resolved.

**Comment by hypest** [comment] 2019-04-19 11:00
There is no-one assigned to this one yet so, will lift the milestone designation.

**Comment by pinarol** [comment] 2019-05-03 13:34
yes I think this is an iOS only problem, I'll label it. Thanks @mchowning

**Comment by etoledom** [comment] 2019-05-22 09:39
Closing since I could not reproduce it after merging https://github.com/wordpress-mobile/gutenberg-mobile/pull/975

**Closed by etoledom** 2019-05-22 09:39 UTC
Labels: bug, iOS
