### ISSUE TITLE
Uploading videos in a WordPress.com free site is not restricted

### ISSUE THREAD

**Issue by jartes** [wordpress-mobile/gutenberg-mobile#2462] opened 2020-07-06 20:01 UTC
**Describe the bug**
Uploading videos into a free WordPress.com site is not restricted as it is in Calypso.

**To Reproduce**
1. Open the app.
2. Add a new post into a WordPress.com free site.
3. Add a `Video` block and upload a video from the device.
4. Publish the post.
5. Check the post in Calypso and the video is there.

**Expected behavior**
A message or warning when trying to add a Video block saying to upgrade to Premium like in Calypso. Also, I will expect not being able to upload a video.

**Screenshots**

Video uploaded: 
![IMG_5249](https://user-images.githubusercontent.com/1046943/86635789-d6256100-bfd3-11ea-9c18-04aaf34435c1.PNG)

The video uploaded in Calypso (note the warning about upgrading to Premium):
![Screenshot 2020-07-06 at 21 54 38](https://user-images.githubusercontent.com/1046943/86635729-c0b03700-bfd3-11ea-9e1a-a222790c0a29.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 13.5.1
 - Version 15.2 (15.2.0.0) (beta)

**Additional context**

**Comment by hypest** [comment] 2020-07-08 15:47
👋 @jartes , thanks for opening this ticket. It is actually by design that the mobile apps are allowed to upload videos to free-plan WordPress.com sites. The spirit behind this is to help the mobile apps get more adopted.

There is no current plan to change this setup so, I will close this ticket as "wontfix" for the time being. We can reopen in the future if needed.

**Closed by hypest** 2020-07-08 15:47 UTC
