### ISSUE TITLE
Para block - Formatting toolbar - Problems when applying Bold to the whole text and then typing at the beginning of the block

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#757] opened 2019-03-18 18:17 UTC
There is a weird problem (actually it's a set of problems but the root cause should be common) that happens when applying Bold to the whole text in a para block and then typing at the beginning of it. Every other letter will be bold.

Steps :
- Create a new paragraph
- Write some text
- Select all and then apply `bold`
- Move the caret at the beginning of the block
- Start typing new text

Result -> Every other letter will be bold.

![every_other_letter_bold](https://user-images.githubusercontent.com/28219092/54454545-15b9a100-4730-11e9-87e8-271770b118ec.png)

Slightly different problems reported in these videos: 
https://cloudup.com/ct7LMVYR4J0
- In the first video, after placing the caret at the beginning of the text, and start typing, only the first letter is bold. all other new letters are plain text.
- In the second video the 1st letter is bold, the second is plain text, and then the rest of the new letters are bold. 

I guess it's a problem with the async events that transit from JS <--> Java.

**Comment by mkevins** [comment] 2019-03-29 14:23
I have attempted to reproduce this on the Android Emulator (both in the demo app, as well as the [WordPress-Android app](https://github.com/wordpress-mobile/WordPress-Android)), but I did not observe the same behavior. If it is indeed caused by a timing issue with async cross-platform events, it is possible that this could also result in a race condition that makes this hard to reproduce in an emulated environment.

@daniloercoli do you know, when you tested on a real device, if the rate of typing had any effect on whether you encountered this issue, i.e. did this only occur when typing fast?

**Comment by daniloercoli** [comment] 2019-03-29 17:56
> @daniloercoli do you know, when you tested on a real device, if the rate of typing had any effect on whether you encountered this issue, i.e. did this only occur when typing fast?

Interesting consideration. I had reproduces the problem several times on a real device, Nexus 5 with Android 7 attached to AS. I also remember that I was able to reproduce the same problem on a Samsung S9 (Android 9) attached to AS.
Would you mind to test on a real device, and see it the problem happens?

Let me know, otherwise  I can try do replicate the issue on Monday.

**Comment by mkevins** [comment] 2019-03-30 04:41
Thanks for the additional details about the environment used when you encountered this.
> Would you mind to test on a real device, and see it the problem happens?
That is my next plan, after I try using the computer keyboard as input through the emulator.

**Comment by mkevins** [comment] 2019-03-30 04:59
I just tried it with the computer keyboard (to get higher frequency keyboard events), but the issue still evades me. I will set up a real device for testing as my next step.

Once the cause is determined, I think I may want to find a way to reproduce it in the emulated environment as well, if possible. My thinking is, when we start to improve our test coverage, it may be helpful to understand some of the "classes" of bugs that are not consistently encountered between the emulated and physical device environments. I expect that even if we cannot reproduce it on the emulator, the attempt to do so may help elucidate gaps in coverage during automated tests.

Interestingly, https://github.com/wordpress-mobile/gutenberg-mobile/issues/783 seems to be a bug that is reproducible on the emulator, but *not* on a real device.

**Comment by daniloercoli** [comment] 2019-04-01 16:07
I've just re-tested and can replicate the problem consistently. I noticed when trying to replicate the issue - it was failing on my first attempts - that we need to follow testing steps carefully (there is a tap on the screen we cannot miss to replicate the problem).
- Start the demo app
- Create a new paragraph
- Write some text
- Select all and then apply bold
- [Tap at the beginning of the block] without doing any other UI action
- Start typing new text...booom 🤯

Below is a link to 2 videos I've just made on my Nexus 5 with Android 7.1.1 https://cloudup.com/cycFLCo7dGn


Hope this will help a bit. Note that the device was not under heavy loading and I was not tapping fast. In the video you can see taps on the screen, since i've enabled the option to record them.

**Comment by mkevins** [comment] 2019-04-02 09:01
When I try to reproduce on the emulator, I don't see the same. Here is how it looks for me:

<img src="https://user-images.githubusercontent.com/8507675/55389199-1c417880-5578-11e9-8e95-55a442e591ef.gif" width="360">

I had to create the paragraph block by splitting with the enter key, because the new block button seems to not work (on the emulator):

<img src="https://user-images.githubusercontent.com/8507675/55389198-1c417880-5578-11e9-9737-cf7e44b881fe.gif" width="360">

**Comment by mkevins** [comment] 2019-05-23 06:24
I am able to reproduce a similar issue on the Android emulator (Pixel 2 - API 27), and observed some other strange behaviors around text styles. After following these steps: https://github.com/wordpress-mobile/gutenberg-mobile/issues/757#issuecomment-478642275 I observed that the bold text will lose its bold style one character at time as characters are added before it. This seems to occur only when the keyboard has suggestions listed (i.e. if I start with a number, it does not occur, but if I start with letters, it does occur). This phenomenon may be hard to visualize, so I've added the screencasts below to demonstrate what I mean (a picture is worth 1000 words):

<img src="https://user-images.githubusercontent.com/8507675/58229503-46900500-7d75-11e9-85e6-152d2e939d1e.gif" width="300"><img src="https://user-images.githubusercontent.com/8507675/58229504-46900500-7d75-11e9-8d01-0ebadf0509fc.gif" width="300">
<img src="https://user-images.githubusercontent.com/8507675/58229505-47289b80-7d75-11e9-97da-9ce9b91dd5d0.gif" width="300"><img src="https://user-images.githubusercontent.com/8507675/58229506-47289b80-7d75-11e9-8340-a551a13f5b8f.gif" width="300">
<img src="https://user-images.githubusercontent.com/8507675/58229507-47c13200-7d75-11e9-9dca-19ce28e96a09.gif" width="300"><img src="https://user-images.githubusercontent.com/8507675/58229508-47c13200-7d75-11e9-9946-e360a4c781dd.gif" width="300">

These experiments with different mixes of letters and numbers may provide a clue to an underlying inconsistency in state for the formats of the individual characters. Also note, these same observations are consistently occurring for **bold** and _italic_ text, but are not happening for ~strikethrough~ nor linked text.

**Comment by JavonDavis** [comment] 2019-06-24 16:29
I'm able to reproduce this as well on Pixel 3a - Android 9 I experimented with bold, strikethrough and Italic text here... I've included gifs to show the weird behaviors I've seen most of which with the toolbar not matching up with the formatting applied once you've left the paragraph block and returned.

![vid1](https://user-images.githubusercontent.com/6520461/59951620-81a25880-9447-11e9-8179-58471decc548.gif)

![vid2](https://user-images.githubusercontent.com/6520461/59951626-849d4900-9447-11e9-8cd0-e15281b020f4.gif)

![vid3](https://user-images.githubusercontent.com/6520461/59951631-8830d000-9447-11e9-9765-cf305b851a7e.gif)

![vid4](https://user-images.githubusercontent.com/6520461/59951634-8b2bc080-9447-11e9-8753-164db7b56f0b.gif)

**Comment by hypest** [comment] 2020-10-22 10:07
This ticket is not worked on at the moment so, I'll clear the assignee field to denote so.

**Comment by designsimply** [comment] 2020-10-28 00:58
A user reported this in an App Review and I was able to replicate it in testing.

> In the iOS app, when typing text in the block editor, the bold button changes back to regular in the middle of bolded sentences and even in the middle of bolded words. Very frustrating to have to keep tapping it to continue with bold text. 

<sup>4-star App Review - Oct 26, 2020 - Version 15.9 - Canada - app-store-reviewId=6575851635</sup>

Steps to reproduce:

1. Start a new post.
1. Create a new paragraph.
1. Tap the bold option and start typing.
1. Observe that the text stops being bold at some point, usually in a word where the delete key was used.
1. Create a new paragraph.
1. Type some text then tap the bold option and start typing.
1. Observe that after swiping a word then pressing backspace the bold option is still highlighted but the text is no longer actually bold.

**Result:** bold is applied inconsistently while typing—note that it seems to happen when the delete key is involved. ([2m32s](https://cloudup.com/cR35qhIANNS))

<img src="https://user-images.githubusercontent.com/1119271/97374774-c2ea1a00-187e-11eb-954c-e2c329a937c2.gif" width="270" alt="bold-does-not-stay-bold-wpios-15 9">
<sup>Tested with WPiOS 15.9 App Store version on iPhone 11 iOS 14.0.</sup>

**Comment by guarani** [comment] 2021-09-17 20:02
I can't reproduce on WPAndroid 18.2, but reading through the comments here, some had difficulty reproducing. So, I think it would be best to have another person confirm this issue is no longer reproducible. If it can't re reproduced, I think it's best to close this issue.

--- 

I think the above comment, https://github.com/wordpress-mobile/gutenberg-mobile/issues/757#issuecomment-717629028, deserves a separate issue. As noted in the comment, it's due to how tapping the delete key turns bold formatting off. In my testing, it's an iOS specific issue, while the rest of this issue is an Android-specific issue.
I've gone ahead and created a separate issue for it here: https://github.com/WordPress/gutenberg/issues/34938

**Comment by SiobhyB** [comment] 2024-01-29 15:22
I'm not able to reproduce the original issue with Android. I tested with the latest version of the app (24.1) and a Pixel 6 (Android 14). As we haven't had user reports of this happening on Android in almost 5 years, and the fact we're not able to reproduce, I'll go ahead to close this issue. If similar comes up again, we can open a separate issue and troubleshoot separarely.

**Closed by SiobhyB** 2024-01-29 15:22 UTC
Labels: [Type] Bug, Writing Flow, [Status] Needs Android Dev, [OS] Android, [Pri] Medium, HACK week
