### ISSUE TITLE
[iOS] Video Block doesn't play MP4

### ISSUE THREAD

**Issue by jacoswan** [wordpress-mobile/gutenberg-mobile#1998] opened 2020-03-11 13:03 UTC
**Describe the bug**
Apologies in advance for this less than stellar bug report.  In #19322509-hc user reports their MP4 video doesn't play on iPhoneX, Safari and explains:

> my mp4 files plays on normal browsers but not on iPhoneX, the browser specifically need an option "playsinline", which I couldn't set when i insert the video.
if i add plays inline on an html i created, it works
but i don't see such option on the WP video plugin options

**To Reproduce**

1. Go to post/page editor
2. Add a video block
3. Add Mp4 video (Autoplay on, Loop on, Muted on, Playback Controls off, Preload auto, no post image, AMP layout default, AMP noloading off)
4. Visit with iPhoneX using Safari. See just an image, no video.

Video specs:
Format: H.264 HD (1-1-1)
Resolution: 1024x768 4:3
Encoded FPS: 30
Data size: 5mb
Data rate: 3.15 Mbit/s

**Expected behavior**
Expected the video to play, or at least have an option to tap to play

**Screenshots**
Apologies, none available, don't have the same device to thoroughly test. 
Not an issue on Android with Firefox

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhonex]
 - OS: iOS version is 13.3.1 and iPhoneX

Couldn’t get the safari version
 - Browser: Safari

**Additional context**
Followed up in #2781652-zen

**Comment by hypest** [comment] 2020-04-06 13:41
Interesting, can you have a look @guarani to see if we can replicate this and how hard would it be to have the specific attribute available? Thanks!

**Comment by guarani** [comment] 2020-04-07 16:45
### Can I Reproduce?

**Yes**, I could reproduce the bug on mobile Safari, where videos don't play on posts and there's no option to play them.

### Cause(s)

On WordPress.com, the `playsinline` option is missing (it's not found in the video block's settings panel). The option is present on the WordPress for iOS app, though there is [a bug where the option is not saved by the server](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1721#issuecomment-570945873).


I think the path forward is to first find out why the option is not in the visual editor of Gutenberg on WordPress.com. I noticed that even if `playsinline` is manually added to the block by the user using the code editor, it's removed as soon as the post is saved. 
(This option _is_ available on WordPress.org – I replicated on a local WordPress.org installation – it was [added and merged here](https://github.com/WordPress/gutenberg/issues/14422)).

The second step is to follow up on the bug I linked to above where the option is not saved by the server.

### To Note

Although the user is on mobile, I think some of their actions take place on WordPress.com (via Safari) and others on the WordPress for iOS app.

### Next Steps

I will follow up on the bug linked to above because that will allow users to add the "Plays inline" option from the mobile app. I will then check why the WordPress.com site doesn't display the option either, as this affects mobile users who opt to use the responsive website instead of the app.

**Comment by guarani** [comment] 2020-04-19 16:11
**Update:** I've added [a feature request on the wp-calypso repo](https://github.com/Automattic/wp-calypso/issues/41239) to support `playsinline`. This will allow users to access the "Plays inline" checkbox on the responsive website.
I'll update again after creating a feature request for the REST API, as that will allow us to add support on the mobile apps.

**Comment by guarani** [comment] 2021-09-30 14:58
Removing myself as assignee since I'm not working on this at the moment.

**Comment by igotdes** [comment] 2022-04-29 02:52
Also reported in #5176537-zen. The issue can be seen when viewing [this page](https://micarf.com/2022/04/28/water/) (private).

I was able to replicate the issue on an iPhone SE (2022) with both Chrome and Safari. The mp4 plays just fine in Slack. Here's some more information on the video, if it helps:

- Dimensions: 1280 × 720
- Codecs: AAC, H.264
- Color profile: HD (1-1-1)
- Audio channels: Stereo

**Comment by SiobhyB** [comment] 2024-02-23 17:21
Fixed in https://github.com/Automattic/jetpack/pull/35637.

**Closed by SiobhyB** 2024-02-23 17:21 UTC
Labels: [Type] Enhancement, Video block
