### ISSUE TITLE
Links: “Open in a new tab” setting doesn’t look like it saves.

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#1161] opened 2019-06-19 14:56 UTC
**Expected:**
When I set the “Open in a new tab” setting for a link, I expect it to remain toggled on.

**Actual:**
It does not remain toggled on in all circumstances, even though the target=“_blank” remains in tact.

This happens in Paragraph

**To Reproduce:**
1. Create a new post
2. Add a paragraph block, type some text.
3. Add a link and set it to “Open in a new tab”.
4. Open link settings again and see that “Open in a new tab” is toggled off (don’t touch the toggle, just note). 
5. Tap into another block.
6. Tap back into the block with the link, and carefully place your cursor mid-word within the link.
7. Open link settings again and see that “Open in a new tab” is toggled on.
8. Tap to close link settings. Note that the word is highlighted, but the “link” icon is not.
9. If you tap link settings again, you’ll see that once again “Open in a new tab” is toggled off.

This makes it very difficult to know for sure whether I have in fact set the link to “Open in a new tab”. 

**Video:**

![linksettings](https://user-images.githubusercontent.com/15107387/59776236-1cb9f780-92bb-11e9-926b-121c49ac24d7.gif)

**However, the target=“_blank” remains in tact despite it not appearing consistently.**
This has to be tested in a web browser, since currently preview posts in iOS opens them in the in-app browser. When we tap the link, the device browser opens, so there’s not a simple way to tell whether it was set to open in a new tab or not without browser tools.
In a browser, we can easily Inspect Element, or simply test the link when previewing.

**To Reproduce:**
1. Open WordPress.com in a web browser and navigate to Blog Posts.
2. Open the Post you’ve been working on (doesn’t matter if it’s Draft or Published).
3. Check the link. Is “Open in a new tab” toggled on? Check again. How about now?
4. Preview or View the post. 
5. Check the link, either with Inspect Element or by simply tapping it, and note it opens in a new tab.

<img width="594" alt="Screen Shot 2019-06-19 at 5 12 39 PM" src="https://user-images.githubusercontent.com/15107387/59776285-39562f80-92bb-11e9-9d76-e52bcab8187f.png">

<img width="876" alt="Screen Shot 2019-06-19 at 5 54 46 PM" src="https://user-images.githubusercontent.com/15107387/59776374-5e4aa280-92bb-11e9-92ec-5bf533e77882.png">

**iPhone SE, (iOS 12.2) running WPiOS 12.7**

**Comment by iamthomasbishop** [comment] 2019-06-19 16:49
I thought this was fixed recently (#1018 ?), but maybe we've got a regression on our hands.

**Comment by etoledom** [comment] 2019-06-24 06:32
I think it's not a problem with the link setting itself, but a problem with the underlying selection data.
If you notice, the second time that the links settings is opened and the switch is off, the URL is not there and the link text shows the whole sentence.

The system seems to be confused about what is the text selected.

**Comment by thehenrybyrd** [comment] 2019-06-25 07:24
@etoledom agreed - when I carefully place the cursor mid-word, I could see the link. When the whole word was selected, I'd see no link.
In addition, I _think_ this is an iOS-only issue. Android needs more testing, but at a glance I wasn't able to reproduce there.

**Comment by SiobhyB** [comment] 2023-11-16 16:37
I'm no longer able to reproduce this issue, so going ahead to close this one. :)

**Closed by SiobhyB** 2023-11-16 16:37 UTC
Labels: HACK 7/2019
