### ISSUE TITLE
Crash when opening a post with fontSize set to a paragraph

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#2991] opened 2021-01-11 14:05 UTC
**Describe the bug**
The editor is crashing when opening a post that has a custom font size set in a paragraph.

**To Reproduce**
1. On the web, create a simple post with a single paragraph block and set its "Font Size" in the Typography section (see screenshot)
2. Save the post as draft or publish it
3. Go to the WPAndroid and open the post
4. 💥 

**Expected behavior**
The app should not crash.

**Screenshots**
<img width="300" alt="Screenshot 2021-01-11 at 16 03 00" src="https://user-images.githubusercontent.com/1032913/104191822-b0679180-5426-11eb-950d-7702c12315e4.png">

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - WPAndroid Version 16.4-rc-3, 16.3, 15.9.1 (at least, probably happening on more versions too)

**Additional context**
* Doesn't seem to happen for me on WPiOS v16.3
* Sentry report: https://sentry.io/share/issue/0244926c0adf4aeda025bc36bae98d3e/ although Sentry conflates this with similar crash reports.

**Comment by cameronvoell** [comment] 2021-01-11 23:02
Looks like the  final error is:
`E unknown:ReactNative: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'fontSize' in shadow node of type: RCTAztecView`
with Exception:
` E unknown:ViewManager: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double`

I believe [this line](https://github.com/WordPress/gutenberg/blob/4dace92fa0134c8e2f33f9ac251d50ed1e41e37e/packages/rich-text/src/component/index.native.js#L938-L940 ) is setting `RCTAztecView` `fontSize` to "14px" (for example) when it is expecting a `float` value and then we get the Exception when [this method call](https://github.com/WordPress/gutenberg/blob/4dace92fa0134c8e2f33f9ac251d50ed1e41e37e/packages/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java#L284) has incorrect arguments (receives a String when expecting a float).

It feels like this should be fixed on the js side, but I may look at the Android `ReactAztecManager.java` as well ~since this is working okay on iOS~ (see below issue was reproduced on WPiOS).

**Comment by cameronvoell** [comment] 2021-01-12 01:41
I reproduced this crash on WPiOS by running latest `develop` branch build (commit [83342a51db1f6e4d9610641287d151c9f461e7b2](https://github.com/wordpress-mobile/WordPress-iOS/commit/83342a51db1f6e4d9610641287d151c9f461e7b2))  locally with latest gutenberg-mobile locally (same steps as description). 

This is interesting because WPiOS 16.4 from the App Store seems to be working fine for me. 

See screenshot of issue with local build on latest gutenberg-mobile/gutenberg:
![image](https://user-images.githubusercontent.com/1103838/104258785-0cd1ad80-5435-11eb-9793-31ed24d9f8f9.png)

**Closed as completed** 2021-01-14 18:19 UTC
Labels: [OS] Android, [Type] Crash, [Pri] High
