### ISSUE TITLE
[GlobalStep] [iOS] While switching the app language to any "Right-to-Left language" (such as Hebrew,Arabic etc). Paragraph, List, Text blocks icon/buttons are misaligned.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2296] opened 2020-05-21 15:11 UTC
**Environment:**
iOS: iPhone 8 (v13.4.1), iPhone 11 pro (v13.2.2), iPhone XS (v13.2.2).
Build[version]: v14.9

**Steps To Reproduce:**
  1. Install and launch the application.
  2. Tap on "Log In".
  3. Log in to the app using valid credentials.
  4. Assuming app language is changed from English say to any one of the RTL languages e.g Arabic.
  5. Tap on MySite .
  6. Now Tap on "+" to create a blog post.
  7. Enter any text at title.
  8. From footer tap on "+" symbol to add Columns and Media & Text,  Paragraph, List, Text blocks.
  9. Rotate the device to landscape mode.
  10. Observe that while switching the app language to any "Right-to-Left language" (such as Hebrew,Arabic etc). Paragraph, List, Text blocks icon/buttons are misaligned.

Note: Compared the template with below link
https://github.com/WordPress/gutenberg/pull/21502

**Actual Result:**
While switching the app language to any "Right-to-Left language" (such as Hebrew,Arabic etc). Paragraph, List, Text blocks icon/buttons are misaligned.

**Expected Result:** 
While switching the app language to any "Right-to-Left language" (such as Hebrew,Arabic etc). Paragraph, List, Text blocks icon/buttons are should be properly aligned.

**Attachment:**
[#2296.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663167/2296.zip)

**Comment by designsimply** [comment] 2020-05-22 20:51
Duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2288.

RTL Gallery|RTL MediaText|RTL Paragraph|RTL List
---|---|---|---
![IMG_3673](https://user-images.githubusercontent.com/1119271/82708117-bf50c800-9c3a-11ea-9c42-faeaa414db8a.PNG)|![IMG_3674](https://user-images.githubusercontent.com/1119271/82708125-c2e44f00-9c3a-11ea-94e3-ce5c920f4180.PNG)|![IMG_3675](https://user-images.githubusercontent.com/1119271/82708126-c37ce580-9c3a-11ea-93f2-b412ad0302eb.PNG)|![IMG_3676](https://user-images.githubusercontent.com/1119271/82708128-c37ce580-9c3a-11ea-93d3-a72514596fc8.PNG)

<p style="clear:both;"><sup>Tested with WPiOS 14.9.0.2 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

Closing as invalid for the same reason as the other issue. It appears the app interface language was not changed to RTL in the attached video and a test of WPiOS after switching the language in the device Settings > WordPress > Language to Hebrew reveals the redo/undo buttons, Gallery image mover buttons, and default alignment for MediaText and Paragraph blocks look correct.

**Closed** 2020-05-22 20:51 UTC
Labels: RTL, [Status] Duplicate, [Status] Invalid
