### ISSUE TITLE
Feature Request: Add an option to default the editing mode to HTML Mode

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#3757] opened 2021-07-26 03:42 UTC
**Is your feature request related to a problem? Please describe.**

Requested in 4165101-zd-woothemes:

<blockquote>
I have a self-hosted Wordpress blog where I use Markdown to format my posts. Sometimes, I need to indent code blocks with 4 spaces in the beginning of every line. This is normal formatting, in line with Markdown standards.

I have customised the web editor accordingly and it works fine. But the iOS app is only able to save posts with whitespace after I switch it to the HTML editor mode.

The further problem is, when I come back and re-open that post later, it still always reverts to the Visual editor by default, which removes the whitespace on load. I can then manually switch back to the HTML mode, but the whitespace is now lost and won't be restored.

So is there a way to have the iOS app always start the HTML editor by default -- either via a setting, or by remembering the previous editor mode used for a given post? I found a setting to disable the block editor, but it doesn't seem to help. I need a setting to disable the Visual editor in favour of the HTML mode.
</blockquote>

**Describe the solution you'd like**

Having an option to default the editing mode to HTML Mode.

**Additional context**

The user also mentioned some customizations used on their site for the editor:

> I have several filters wrapped into a custom plugin. The purpose is to disable the rich editor and all the post-processing and auto-magic that comes with it (e.g. replacing double backticks with quotes). Here's what it does: https://github.com/mehov/writedown/blob/main/writedown.php

They're also referring to [this GitHub issue](https://github.com/WordPress/gutenberg/issues/33558) to customize their web editor.

> The problem was the editor removing the whitespace indentation required by Markdown. The above link has the hotfix. Basically, I disabled the Javascript version of the `autop`, and then subsequently its `removep` counterpart.

**Comment by hypest** [comment] 2021-07-26 10:04
Seems like a fairly custom use case. Besides, in a post without blocks, the app will open the "Classic" editor (Aztec), not the block editor. The classic editor is not currently the focus of attention but, feel free to open a ticket in the [Aztec Android](https://github.com/wordpress-mobile/aztecEditor-android) and [Aztec iOS](https://github.com/wordpress-mobile/AztecEditor-iOS/) repos.

That said, I see little possibility for such a feature to be properly supported in the apps anyway. As the WordPress editors in the apps are trying to adhere to the HTML standards, maintaining a feature that puts special role to leading whitespace won't be prioritized (leading whitespace in HTML plays a role only in cases). I'm going to close this ticket as "wontfix", but happy to review a Pull Request by anyone that would like to own implementing something similar. Thanks!

**Closed as completed by hypest** 2021-07-26 10:04 UTC
Labels: [Type] Enhancement, [Pri] Low

**Comment by mehov** [comment] 2021-08-05 06:04
Hello @hypest, @reginabally,

I'm afraid there was a misunderstanding. I sent you additional links for context, but that only confused you. Please ignore them then.

The functionality I want is already there in the current HTML Mode editor. Here it is:

![IMG_B4B886DA3296-1](https://user-images.githubusercontent.com/7813306/128298017-92a26ac6-6482-4c02-a474-7f05dc1b5c4d.jpeg)

the HTML Mode Editor already maintains the whitespace and special characters just fine. The problem is when I close the post and re-open it later, it always goes to the Classic editor, which messes those up on load. So even if I then manually switch to the HTML Mode editor using the above menu, the markup has been lost.

All I was asking for was to have this HTML Mode editor loaded by default, this way I don't have to switch to it from the other editor (again, not because I'm lazy to make a few extra clicks, but because the default editor irreversibly messes up the markdown). 

So this **is** about: 
- opening posts in the (already existing) HTML Mode editor right away, skipping the Classic editor, by default

This is **not** about:
- the Aztec
- the whitespaces or the HTML standards
- asking you to maintain anything that you don't already have

Please let me know if this is still confusing. Thank you!
