### ISSUE TITLE
Tapping backspace to merge a paragraph into pullquote block dismisses keyboard

### ISSUE THREAD

**Issue by ceyhun** [wordpress-mobile/gutenberg-mobile#3089] opened 2021-02-02 16:11 UTC
**Describe the bug**

When merging back an empty paragraph block into pullquote block the keyboard is dismissed instead of cursor moving back to the pullquote block.

**To Reproduce**
1. Add a pullquote block
1. Add quote
1. Add citation
1. Tap enter to create a new paragraph block
1. Tap backspace to merge the paragraph into pullquote block
1. Keyboard is dismissed and pullquote is selected

**Expected behavior**
Keyboard should stay on screen and cursor should move back to the pullquote block's quote or citation

**Screenshots**

https://user-images.githubusercontent.com/1845482/106627374-08526d80-6579-11eb-8090-7e56b0ff7c02.mp4

**Smartphone:**
iPhone 11 Pro, iOS 14.3

**Additional context**
Same on both WPiOS 16.6 and 16.5 and WPAndroid 16.6

**Comment by guarani** [comment] 2021-09-16 19:27
Noting that since this issue doesn't appear on the Quote block (only on the Pull Quote block), any differences between the blocks might help pinpoint where the issue is.

**Comment by geriux** [comment] 2023-11-28 16:24
Fixed in https://github.com/WordPress/gutenberg/pull/56496

**Closed as completed by geriux** 2023-11-28 16:24 UTC
Labels: [Type] Bug, Writing Flow
