### ISSUE TITLE
Italics style is removed when pressing backspace in captions (iOS)

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/gutenberg-mobile#2055] opened 2020-03-24 12:18 UTC
**Describe the bug**
If you hit the backspace button while typing a caption that has italics style selected, the style is removed even though it is still highlighted in the toolbar. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new post in the block editor
2. Add a media block and add an image
3. Add a caption and set text style to italics.
4. Type a message and in the middle click on backspace. 
5. Continue typing and the text style is removed.

**Expected behaviour**
I expected the text to stay the same even after a backspace.

**Screenshots**
![Screen Recording 2020-03-24 at 12 12 pm](https://user-images.githubusercontent.com/10325627/77424314-cd17d780-6dc8-11ea-8dea-fb60b44e876c.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3.1
 - Version 14.3

**Additional context**
Reported by a user in 2808472-zen for a free WordPress.com site (replicated on Premium site)

**Comment by rezzap** [comment] 2020-09-23 11:48
I've had another report of this but not just within the caption, it also happens when you're editing a normal paragraph block. Is this intended behaviour @hypest ?  

3337811-zen

I was able to replicate this on:

iPhone X, iOS 13.7, Version 15.7

**Comment by hypest** [comment] 2020-09-23 12:54
Thanks for the additional report @rezzap !

I don't think it's intended behavior, and there was at least one ["similar" Aztec-iOS issue](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/749) in the past.

When you get the chance @etoledom , can you check with Aztec to see what might be going on? Thanks!

**Comment by fluiddot** [comment] 2022-02-02 10:07
Closing this issue as it was already solved in https://github.com/WordPress/gutenberg/pull/37676 and released in version `19.0`.

**Closed by fluiddot** 2022-02-02 10:07 UTC
Labels: [Type] Bug, Writing Flow, [OS] iOS
