### ISSUE TITLE
Story block - Blocks are removed when adding media (only iOS)

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#3243] opened 2021-03-10 12:31 UTC
**Describe the bug**

After adding media to a Story block, it removes all the blocks from the post.

**To Reproduce**
1. Add some blocks to a post.
1. Add a Story block.
1. Add a media item.
1. Tap on the right arrow button to continue.
1. Observe that the previous added blocks are removed.

**Expected behavior**
The Story block shouldn't remove or modify the blocks from the post.

**Screenshots**

https://user-images.githubusercontent.com/14905380/110617558-1efe6c80-8196-11eb-992b-592a66f1324e.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.2
 - Version 16.9

**Additional context**
I managed to reproduce this issue also in version `16.8`.

**Comment by geriux** [comment] 2021-03-10 12:50
I couldn't reproduce this on Android so it is only for **iOS**.

**Comment by hypest** [comment] 2021-03-12 12:33
Fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/3246

**Closed as completed by hypest** 2021-03-12 12:33 UTC
Labels: [Type] Bug, [OS] iOS, Story block
