### ISSUE TITLE
Story block - Crash after discarding a media item selected from the device media library (only iOS)

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#3244] opened 2021-03-10 12:39 UTC
**Describe the bug**

After discarding a media item selected from the device media library, trying to add a media item from the device on any block produces the crash.

I managed to reproduce this issue on TestFlight builds of versions `16.8` and `16.9`, on those versions the app doesn't crash but the flow for adding media items in any block stops working.

**Sentry issue:** https://sentry.io/organizations/a8c/issues/2250393647/events/389dedd8d5484c5c83b6591500862436/?project=1438083&statsPeriod=14d

**To Reproduce**
1. Add a Story block.
2. Tap on ADD MEDIA.
3. Tap on the little square button located at the bottom left.
4. Select any item.
5. Tap on Add button.
6. Tap on X button to discard changes.
7. Tap on Discard button.
8. Add an Image block.
9. Tap on ADD IMAGE.
10. Tap on Choose from device.
11. Select any item.
12. Observe that the app crashes.

**Expected behavior**
Discarding a media item selected from the device media library shouldn't derive in a crash.

**Screenshots**

https://user-images.githubusercontent.com/14905380/110620131-f6c43d00-8198-11eb-8694-80e07f3d1975.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.2
 - Version 16.9

**Additional context**
N/A

**Comment by bjtitus** [comment] 2021-03-11 01:35
This is an assertion which will not fire in non-debug builds and is due to a Core Data managed object context mismatch. I don't think this warrants a Hot Fix at this time, but will be investigated for the next release (16.9 or later depending on timing).

**Comment by bjtitus** [comment] 2021-03-15 23:52
The assertion was the cause of the crash but the media issue was the other reported problem here.

[Hot Fix 16.8.1](https://github.com/wordpress-mobile/WordPress-iOS/pull/16059) fixed this bug with the following change:
https://github.com/wordpress-mobile/WordPress-iOS/pull/16059/commits/46a07401997bed37c6ff5eebe7c055214981291d

**Closed as completed by bjtitus** 2021-03-15 23:52 UTC
Labels: [OS] iOS, [Type] Crash, Story block
