### ISSUE TITLE
GB mobile demo app - red screen is presented when entering the app from background

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#1130] opened 2019-06-13 13:29 UTC
Steps are:
1. Open GB mobile demo app
2. Dismiss it with the back button.
3. Lunch the app again by clicking on the icon

Result-> red screen

![error](https://user-images.githubusercontent.com/28219092/59436443-9d5d8d00-8dbd-11e9-982c-674200759995.png)

**Comment by hypest** [comment] 2019-06-14 10:19
I think this is duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/670. Closing.

**Closed by hypest** 2019-06-14 10:19 UTC
