### ISSUE TITLE
Media & Text block - can't take a photo or video

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/gutenberg-mobile#1571] opened 2019-11-12 14:53 UTC
**Describe the bug**
I can't add a photo or video using Media & Text block.

**To Reproduce**
1. Create a post in WPAndroid
2. Add "Media & Text" block
3. Click on it
4. Choose "Take a photo or video"
5. Nothing happens

**Expected behavior**
The app opens a camera app I guess?

**Screenshots**
![image-text-block-gb](https://user-images.githubusercontent.com/2261188/68681875-7f5ea900-0564-11ea-8b93-6e36296fafe2.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android X
 - Version develop 6e59663f8c0eda962c8a6fa0a45212fbd17942b1

**Comment by hypest** [comment] 2019-11-13 14:05
I can reproduce the issue on WPiOS as well.

**Comment by mkevins** [comment] 2019-11-14 05:06
It seems that the language "Take a Photo or Video" was introduced in this PR: https://github.com/WordPress/gutenberg/pull/17145, but I couldn't find an underlying implementation which allows for _capture_ of both image or video within a single intent. If such an intent exists, we can launch it for `MediaType.MEDIA`. Otherwise, it isn't exactly clear to me how to proceed.

We have `launchCamera` and `launchVideoCamera` methods for capturing photos and videos, respectively. These each prepare an intent in slightly different ways (within `WPMediaUtils`). The capture image intent [customizes the file path with a "wp-" prefix](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java#L302), and the capture video intent [launches the `MediaStore` provider intent directly (without extras)](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java#L252). The capture photo code path also has some extra checks to make sure the destination directory exists for writing the output file.

I'm not aware of any `MediaStore` provider to capture _either_ a photo or a video. It seems the intents that return with a result are mutually exclusive in that regard. https://developer.android.com/reference/android/provider/MediaStore

One solution may be to use the existing photo capture  intent and change the language to reflect that. Something like this might work:

```diff
diff --git a/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java b/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
index 1965d5f..6238c7f 100644
--- a/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
+++ b/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java
@@ -182,7 +182,7 @@ public class WPAndroidGlueCode {
             public void requestMediaPickerFromDeviceCamera(MediaUploadCallback mediaUploadCallback, MediaType mediaType) {
                 mMediaPickedByUserOnBlock = true;
                 mPendingMediaUploadCallback = mediaUploadCallback;
-                if (mediaType == MediaType.IMAGE) {
+                if (mediaType == MediaType.IMAGE || mediaType == MediaType.MEDIA) {
                     mOnMediaLibraryButtonListener.onCapturePhotoButtonClicked();
                 } else if (mediaType == MediaType.VIDEO) {
                     mOnMediaLibraryButtonListener.onCaptureVideoButtonClicked();
```

Another solution could be to prepare an `ACTION_CHOOSER` intent, but that'd be one more additional tap in the user flow.

Interestingly, when choosing an image or video already present on the the device, the user has the ability to launch the camera, totally outside of the activity that originally launched the intent. This may somewhat mitigate the issue of the photo only solution (i.e. users can still capture video via the "Choose from device" flow).

**Comment by pinarol** [comment] 2019-11-14 07:49
I suggest doing this in 2 iterations:

- [ ]  Temporary workaround: Let's quickly update the option as "Take a Photo" and make it work similar to Image block and ship it as soon as possible.

I think this is better than having a button doing nothing and it will give us time to address the whole thing.

- [ ]  Implement Take a photo or video option on both platforms.

**Comment by hypest** [comment] 2019-11-14 08:14
We could also try having separate options in the bottom sheet: "Take photo" and "Take video" which we should already have the native sides ready since those are the individual actions of the Image block and the Video block.

**Comment by pinarol** [comment] 2019-11-14 08:18
That's even a better, and it can be a long term solution! Thanks @hypest !

**Comment by hypest** [comment] 2019-12-06 10:54
Closing since the option has been replaced by two separate ones with #1579.

**Closed by hypest** 2019-12-06 10:54 UTC
Labels: Android, bug, iOS
