### ISSUE TITLE
Media Picker - Warning - can't perform state update on an unmounted component

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#1049] opened 2019-05-30 12:34 UTC
Notice the warning below when tried to upload a media in the wp-android app.

![Screen Shot 2019-05-30 at 12 35 23](https://user-images.githubusercontent.com/518232/58632874-37660580-82e7-11e9-92ab-19f7ff813ce5.png)

**Comment by Tug** [comment] 2019-05-30 14:23
I could not reproduce by simply doing those steps on my android device:
- Boot WPAndroid on `develop` with `libs/gutenberg-mobile` on `develop` and `libs/gutenberg-mobile/gutenberg` on `master
- Load a post
- Add an image block
- Upload an image

Is there anything else I could do to trigger it?

**Comment by daniloercoli** [comment] 2019-05-30 14:45
I'm on wp-android `develop` (it points to the version 1.5.1 of mobile-gb). 

- Start a new post
- Add a Video or Image block
- Select a media from the WP media library

**Comment by Tug** [comment] 2019-05-30 15:05
Indeed it only happens when I pick from the WP media library, not from device 👍

**Comment by SergioEstevao** [comment] 2020-05-25 22:19
I no longer see this warning on the current version, so I'm closing this issue.

**Closed by SergioEstevao** 2020-05-25 22:19 UTC
