### ISSUE TITLE
[GlobalStep] [Android] Single picture is displayed even after selected multiple photos from "Choose from Free Photo Library"

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2228] opened 2020-05-06 16:51 UTC
**Environment:**
Android: Samsung Galaxy s9 v(10)

**Reproduction Rate:** 
4/4 100%
 
**Steps to Reproduce:**
1. Install and launch the application.
2. Login using valid credentials.
3. Create a New Site.
4. Tap on Posts.
5. In Body post add Image.
6. Tap on "Add Image" button.
7. Tap on "Choose from Free Photo Library"
8. Search for tomatoes.
9. Select multiple images.
10. Tap on Add.
11. Observe that only one image gets displayed.

**Actual Result:**
Single picture is displayed even after selected multiple photos from "Choose from Free Photo Library"

**Expected Result:**
All the selected images should be displayed on editor.

[#2228.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4588187/2228.zip)

**Comment by mchowning** [comment] 2020-05-07 16:23
Thanks for the report! This looks like a duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/1902, so I'm going to go ahead and close this one. Let me know if you think this is different though, and we can definitely reopen it.

**Closed by mchowning** 2020-05-07 16:23 UTC
