### ISSUE TITLE
Quote background on RTL

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1604] opened 2019-11-21 12:55 UTC
Quote background (shaded with a bar on the side) does not switch to RTL with RTL text like it does in the Aztec demo app.

**Comment by etoledom** [comment] 2020-04-08 13:38
This one seems to be fixed on iOS.

<img src="https://user-images.githubusercontent.com/9772967/78790480-df8c3680-79ae-11ea-9118-b50167f9e9ba.png" width="200" />

**Comment by SiobhyB** [comment] 2024-02-09 18:10
I confirmed the background's showing up correctly for RTL languages in 24.2 for both platforms. The screenshot's from Android:

<img width="368" alt="Screenshot 2024-02-09 at 18 09 30" src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/2998162/f7addc71-b168-4516-ab49-4de9d6f78452">

**Closed by SiobhyB** 2024-02-09 18:10 UTC
Labels: Aztec Parity
