### ISSUE TITLE
Introduce the proper "default block placeholder"

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#453] opened 2018-12-27 12:11 UTC
Comes from https://github.com/wordpress-mobile/gutenberg-mobile/pull/445#issuecomment-450102887

> the Inserter we have on mobile, is matching the _contextual_ inserter button from the web, not the global one. The contextual one always "replaces" the empty block placeholder instead of appending a new block. It's title though still is "Add block". The default block placeholder should not be considered a block though... it's only a fancy/elaborate indicator.

> Long story short, I think we should work towards the proper behavior anyway, which I think is:
> * Introduce the proper "default block placeholder", which is not the paragraph block

cc @hypest to elaborate? I think we might need more information here to make the issue's description "complete"

**Comment by SergioEstevao** [comment] 2020-05-02 09:41
@iamthomasbishop is this something that still needs to be done?

**Comment by iamthomasbishop** [comment] 2020-05-02 21:49
@SergioEstevao I wouldn’t consider it a blocker by any means, but from what I gather we still need to implement behavior that moves selection to the title block when the only block on the canvas is removed or contents cleared. I think other parts of this have been solved in various issues (particularly the part about not showing the movers on the inline toolbar — bc those were removed a while back).

**Comment by SergioEstevao** [comment] 2020-05-04 11:27
@iamthomasbishop I don't see that behavior on the web side after you remove all the blocks the selection stays on the placeholder block. 
Do we want to do something different for mobile?

**Comment by iamthomasbishop** [comment] 2020-05-04 12:02
I don't have strong feelings about the behavior, but it seems like the expected behavior is what I described above. I was referring to what we should try to do on mobile specifically, if possible.

**Comment by hypest** [comment] 2020-06-09 16:05
Since the ticket's original intention was to try and reuse the placeholder as it's found on the web (along with its recently used blocks quick icons) and most of its functionality is already in place per the discussion above, I will close this at this point.

@iamthomasbishop , can you please open a ticket about the "move focus to title block" behavior you are describing? Best to track it separately I think. Thanks!

**Closed by hypest** 2020-06-09 16:05 UTC
Labels: Blocks, [Status] Needs Design, [Status] Needs Design Review
