### ISSUE TITLE
Block titles are not translated

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#3422] opened 2021-04-27 09:32 UTC
**Describe the bug**
The block titles are not translated, they're showing the text in English independently of the device language.

⚠️ I tried in a previous version (WPiOS 17.0.1) and the block titles are translated so looks like this is a regression bug introduced in a recent version.

**To Reproduce**
1. Change the language of your device to a non-English one that is supported by the app (check [this list](https://github.com/WordPress/gutenberg/blob/329fe98df660b0da9b3f149ce34fce2bda1b805d/packages/react-native-editor/i18n-cache/index.js#L10-L60))
2. Open the app
2. Tap on the ➕ button
3. Observe that the block titles are not translated

**Expected behavior**
The block titles should be translated.

**Screenshots**

<img src=https://user-images.githubusercontent.com/14905380/116219386-d9006680-a74b-11eb-8447-e671bd2ad266.jpeg width=400>

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6, Pixel 4] iPhone 8
 - OS: [e.g. iOS 8.1,  Android X] iOS 14.2
 - Version [e.g. 22] 17.1

**Comment by fluiddot** [comment] 2021-04-27 09:44
I've just investigated this issue and I found that this problem is caused due to not updating the i18n cache when making a release.

As an example, for the Paragraph block's title, the localization key is `block title\u0004Paragraph`. If you check [latest localization files](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/bundle/ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es.json) that we've bundled, you will see that this key is not present. However, if you run `npm run core i18n-cache:force` to force updating the localization files and open the file located in `gutenberg/packages/react-native-editor/i18n-cache/data/es.json`, you will see that the key is present.

Looks like the problem is that the scripts that we run when making a release are not assuring that we use the latest localization files. A potential solution would be to clean the localization files when we make the bundles, I saw in the [npm command `bundle`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/6e76f4092bc195420738396f1b9bc10ebf8b1097/package.json#L64) that we invoke the [command `clean` in the `react-native-editor`](https://github.com/WordPress/gutenberg/blob/329fe98df660b0da9b3f149ce34fce2bda1b805d/packages/react-native-editor/package.json#L119) package so we could include there the command `clean:i18n-cache` to clean the localizations cache too.

**EDIT:** I noticed that, if we delete the i18n localization files, we should also explicitly generate the i18n localization files before generating the bundle because they're not automatically generated.

**Comment by fluiddot** [comment] 2021-04-27 11:41
I finally decided to follow a different approach, I realized that we have a `prebundle` command in the `react-native-editor` that updates the i18n localization files. So I add it to the `bundle` command to assure that we always bundle the most recent localization files.

**Comment by mchowning** [comment] 2021-04-27 17:33
I think this may actually be a duplicate of this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/3269. Let's just make sure we close both issues once we resolve this (if you agree).

**Comment by fluiddot** [comment] 2021-04-27 17:39
> I think this may actually be a duplicate of this issue: #3269. Let's just make sure we close both issues once we resolve this (if you agree).

Yep, most likely this issue has been introduced and fixed in different versions, depending on if the release wrangler had the latest localization files 🤦 .

**Closed as completed** 2021-04-28 10:14 UTC
Labels: [Type] Bug, i18n, [Type] Regression, [Pri] High
