### ISSUE TITLE
Links UI: spaced URLs are taken for valid and break the UI

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#740] opened 2019-03-12 19:59 UTC
Originally reported in https://github.com/wordpress-mobile/gutenberg-mobile/pull/716#issuecomment-472157221

1. start a draft, enter some text
2. place the cursor on a word
3. tap the link button
4. in the URL field, insert something with a space in it, for example `yahoo com` instead of `yahoo.com`, and dismiss the links ui
5. observe 2 different words are inserted where the cursor was, `yahoo` and `com` 
6. place the cursor on `yahoo` and tap the links button -> observe the links ui shows empty
7. place the cursor on `com` and tap the links button -> observe the `yahoo com` (invalid) address appears there.

**Comment by daniloercoli** [comment] 2019-03-26 13:59
I can't seem to reproduce this issue on Android.
I also have some questions about testing steps @mzorz , in particular the points no.2 and 3.

> place the cursor on a word

Not quite sure what you mean here, move the caret in the middle of a word and then tapping on the link button? Should I select the word before?
In both cases it seems to work fine, if I don't select the previous word,  two new words are inserted in the editor, where the caret was positioned, and the "link" is just one. When you try step 5 and 6 both open the correct UI with the data filled in.

**Comment by daniloercoli** [comment] 2019-03-26 14:16
When testing this I also noticed a problem with the link UI. @pinarol @etoledom 
When I insert a link, and then position the caret at the end of the newly inserted link, and tap again on the `Link` button the Inserter UI has the `Link Text` field empty.
Steps to repro:
- Add a link
- Move the caret at the end of the link
![Screen Shot 2019-03-26 at 15 11 27](https://user-images.githubusercontent.com/518232/55003922-905ca900-4fd9-11e9-9b66-f511348bc4b4.png)
- Tap the link Button again...(See `Link Text` is empty in the UI)
![device-2019-03-26-151146](https://user-images.githubusercontent.com/518232/55004062-d154bd80-4fd9-11e9-803a-8d7deb757245.png)

- Instead if you move the caret in the middle of the link, and open the link UI again, it has all the details filled in:
![device-2019-03-26-151207](https://user-images.githubusercontent.com/518232/55004151-fb0de480-4fd9-11e9-8ba4-caf8697318fc.png)

**Comment by etoledom** [comment] 2019-03-26 14:37
Hey @daniloercoli - I have seen that issue too. It happens in both iOS and Android.
This value comes from the `format-library`. My guess would be that something wrong is happening here: https://github.com/WordPress/gutenberg/blob/dadd86399abd618e7b7f933b0f1a94cc91d8ffb7/packages/format-library/src/link/index.native.js#L66

But I haven't really checked it out deeply enough to be sure.

**Comment by koke** [comment] 2019-04-04 09:50
I think that's the expected behavior, which seems odd because you are pasting something that's not a URL. The logic here is that if you just typed `wordpress.org` in the URL field, it would actually insert `<a href="http://wordpress.org">wordpress.org</a>`, which makes sense to me.

I'm closing this but feel free to reopen if I misunderstood the issue

**Closed by koke** 2019-04-04 09:50 UTC
Labels: bug

**Comment by mzorz** [comment] 2019-04-04 11:52
Good, just re-tried this and couldn't observe the issue anymore

Just for clarification (sorry @daniloercoli that I missed your ping before):
> place the cursor on a word

I meant, placing the caret in the middle of the word, for example  "this is a wo|rd" (imagine | being the caret), then tapping the url icon in the toolbar and _there_ entering a URL that has spaces in it (that is, an invalid URL).

Anyway, tried it just now and couldn't observe the situation anymore, so OK to keep this closed 👍
