### ISSUE TITLE
Rainbow emoticon causes title to become bold.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/gutenberg-mobile#1929] opened 2020-02-18 15:18 UTC
**Describe the bug**

The rainbow emoticon causes the text that follows in the title to become strong, and the tag is showing up in notices when publishing posts.

**To Reproduce**

1. New post.
2. Type "🌈Testing!🌈".
3. Publish the post.

Notice that the title shown in the notice is: "🌈<strong>Testing!</strong>🌈"

**Expected behavior**

The publication notice shown should show the title as it was written.

**Screenshots**

Gutenberg | Aztec
-|-
<img width="300" alt="Screen Shot 2020-02-18 at 12 06 14 PM" src="https://user-images.githubusercontent.com/1836005/74748991-30ea3600-5248-11ea-9530-f115457987aa.png"> | <img width="300" alt="Screen Shot 2020-02-18 at 12 09 44 PM" src="https://user-images.githubusercontent.com/1836005/74749001-347dbd00-5248-11ea-82a8-571393c679f6.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max Simulator
 - OS: iOS 13.3
 - Version NA

**Additional context**

This issue was first reported by @catehstn

**Comment by SergioEstevao** [comment] 2020-02-18 15:44
I investigate this, and it happens with any title that has an emoji character on it.
The issue is that emoji characters make aztec add more `<strong>` element around them, and the component for the title only removes the start and end `strong`.

**Comment by SergioEstevao** [comment] 2020-02-18 15:45
Related to: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1613

**Comment by mchowning** [comment] 2020-02-24 13:29
I believe we can close this, right @SergioEstevao ?

**Comment by SergioEstevao** [comment] 2020-02-24 16:26
Fixed on release 1.23 of GB

**Closed by SergioEstevao** 2020-02-24 16:26 UTC
Labels: bug
