### ISSUE TITLE
Problem displaying block on Video block when the video was uploaded from Calypso

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#2862] opened 2020-12-02 05:37 UTC
### Expected behavior
I would expect to be able to view the video thumbnail in the app for videos that were uploaded from Calypso, using a Video block.

### Actual behavior
The Video block that was added from Calypso displays the error "Problem displaying block".

![videoblock](https://user-images.githubusercontent.com/40906847/100832056-0baa7980-34a2-11eb-8730-af0c52ea35b7.jpg)

### Steps to reproduce the behavior

1. Log in to WordPress.com
2. Go to My Site > Site > Posts and create a new post
3. Add a Video block and upload a video to the post
4. Save the post as a draft
5. Open the draft post in the app
6. See that the Video block is showing the error "Problem displaying block".

If you publish the draft post, the Video block will show the same error in the app.

##### Tested on OPPO Reno 4, Android 10, WPAndroid 16.2-rc-2

Also replicating this on One Plus 5, Android 10, WPAndroid 16.1

#### Additional information

The test site used in this report is a WordPress.com Premium plan site. The issue was originally reported in a live chat (3421197-hc) using the iOS app version 16.2 on a WordPress.com Premium plan site as well.

I noticed that the VideoPress URL (https://videopress.com/v/NoJfXV0V?preloadContent=metadata) shows up in the app when I viewed the post list in the app. This may be the reason why the Video block wasn't able to render the video thumbnail.

![Screenshot_2020-12-02-13-15-17-24_1cdbe7dded7ec259ed1024b4ff1ae8db](https://user-images.githubusercontent.com/40906847/100832579-24675f00-34a3-11eb-8a87-b12fed17d583.jpg)

**Comment by designsimply** [comment] 2020-12-03 19:06
Tested and confirmed that video blocks added from the web do not work in the WPAndroid app with a message saying "Problem displaying block".

Video added using the web|Video added from the app
---|---
<img src="https://user-images.githubusercontent.com/1119271/101075504-55a56500-355f-11eb-98ad-cc1e5625d3f4.png" width="270" alt="Screenshot_20201203-115055">|<img src="https://user-images.githubusercontent.com/1119271/101075498-54743800-355f-11eb-8a16-6f8417406f60.png" width="270" alt="Screenshot_20201203-115420">

<sup>Tested with WPAndroid 16.3-rc-1 on Pixel 3 Android 11 on a WordPress.com Premium site made4testing0318.blog as testuser0313 and I also tested on a WordPress.com Business site with the same results (not pictured).</sup>

Here is what the HTML looks like for the video block that was added via the web:

```
<!-- wp:video {"id":1955,"className":"wp-block-embed is-type-video is-provider-videopress wp-embed-aspect-4-3 wp-has-aspect-ratio wp-embed-aspect-1-2"} -->
<figure class="wp-block-embed is-type-video is-provider-videopress wp-embed-aspect-1-2 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
https://videopress.com/v/hOW5aPQH?preloadContent=metadata
</div><figcaption>caption test</figcaption></figure>
<!-- /wp:video -->
```

While the HTML is this for the video block that was added using WPAndroid 16.3-rc-1: 

```
<!-- wp:video {"id":1959} -->
<figure class="wp-block-video"><video controls src="https://madefortesting190318.files.wordpress.com/2020/12/pxl_20201023_185404321.mp4"></video></figure>
<!-- /wp:video -->
```

**Comment by designsimply** [comment] 2020-12-03 19:08
@hypest this bug is for one user report so far, but I know it also something similar came up in Slack not too long ago and that other users have probably run into this but not a huge percentage overall. Can you help me set priority for this one? I think it deserves at least immediate triage with an estimate for how long it might take to fix even if it cannot be fixed for the next release. In other words, I think we should check whether it can be fixed quickly and if it cannot then it should be assigned to fix within the next few releases. wdyt?

<sup>(internal reference: GKGRD9YF5/p1606263316058600-slack-wp-mobile-leads private channel)</sup>

**Comment by hypest** [comment] 2020-12-04 12:19
👋 all. This looks related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152.

There is no current plan to remedy this from the mobile apps side but, I'd like to get something moving. I'll comment on the ticket above too.

In the meantime, let's keep this ticket open too since it focuses on the web-to-mobile flow a bit more. WDYT?

**Comment by adelineyaw** [comment] 2021-03-03 01:06
Another case to report: 28137303-hc
It appears on all blog posts that contain the video block. 

- Site URL: https://unrealisticfaith.com/
- Phone model: Samsung Galaxy Note 20 Ultra 5G
- App version: Version 16.7
- Screenshot: https://d.pr/i/fAPnTp
- Follow up: 37882230-zen

**Comment by reginabally** [comment] 2021-03-03 02:49
Another report in 3788147-zen.

**Comment by kosiew** [comment] 2021-03-04 04:55
[I tested adding video via wp-admin new post and video plays correctly.
](https://wpstore101.wpcomstaging.com/test-video-again/)

**Comment by skim1220** [comment] 2021-03-05 06:41
- The user came back with the feedback that the workaround suggested by @kosiew doesn't work for him: [3788223-zen](https://woothemes.zendesk.com/agent/tickets/3788223).
- The suggested workaround works on my Android phone though (Samsung Galaxy S10; Android version 11; WP App version 16.7)
- However, when I check [the user's current post](https://unrealisticfaith.com/2021/03/02/the-lord-never-knew-you/) in SU mode, it does not load the video correctly ([displaying a black screen only](https://d.pr/i/WOLYvv) on both on Desktop and on mobile)

**Comment by hypest** [comment] 2021-03-08 15:14
> displaying a black screen only on both on Desktop and on mobile

👋 @skim1220 , thanks for the extra info! The bit about the video not showing OK in the frontend (in the post as rendered for a visitor of the post on a web browser) makes me wonder if the user actually does any edits to the post on the app or not. Here's the thing: even if the block doesn't display OK **inside the editor in the app**, the html markup itself won't be touched by the app so it should render in the frontend as normal. If it doesn't render OK then it's not actually an app issue.

So, let's try to make sure which case is it. Can you confirm (perhaps by trying it in SU mode on your side) what happens if:
1. User adds a video in a post via Calypso on the desktop web
2. Video plays OK while previewing on the desktop web (?)
3. User opens the post in the app's editor, makes no changes and exits the editor.
4. The post shouldn't be marked as changed
5. Previewing the post on the desktop web should still show the video OK.

If user actually introduces changes in some way (say, in HTML mode or via the Unsupported Block Editor) then we can focus on that. Let me know if this all makes sense and I can rephrase if needed, thanks!

**Comment by galakhyati** [comment] 2021-03-09 05:40
Asked the user to follow the steps shared above and check what happens. Ticket: 3788223-zen.

**Comment by lakellie** [comment] 2021-03-10 19:40
The user shared:

"I added a video in a post from WordPress.com > My Sites > Posts on the desktop web.
I checked if the video plays OK while previewing on the desktop web. And Yes, It Played OK.
I Opened the post in the app's editor, and made no changes and exited the editor. I Did Not Change The Post.
I previewed the post on the desktop web and It Was Still OK."

Based on this, would this still be an app issue, or no?

**Comment by hypest** [comment] 2021-03-18 12:46
> Based on this, would this still be an app issue, or no?

Since the app doesn't break the block and the block continues to render OK **in the frontend of the site**, then there's no new issue here.

So, the only issue is the known one captured in https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152. Will close this ticket in favor of the older one. Please add a comment to possibly re-open if I missed something and there's actually new issues still unaddressed here, thanks!

**Closed as completed** 2021-03-18 13:47 UTC
Labels: [Type] Bug, Jetpack
