### ISSUE TITLE
Post title: Duplicate text with the alias symbol

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#3486] opened 2021-05-12 03:13 UTC
**Describe the bug**

Adding an alias symbol (@) after some text at the post title section in the editor will duplicate the text.

**To Reproduce**
1. Go to My Site > Blog Posts and create a new post
2. At the post title, type some text followed by the @ symbol
3. See that the text is duplicated

**Expected behavior**

I would expect the text before the @ symbol will not be duplicated

**Screen recording**

https://user-images.githubusercontent.com/40906847/117912823-c6248f00-b312-11eb-817f-80199f1f07c6.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone SE, OPPO Reno 4
 - OS: iOS 14.5.1, Android 11
 - Version: WPiOS 17.3 (Internal), WPAndroid 17.3-rc-1

**Additional context**

I noticed this issue when performing a test for a user in 3978163-zd-woothemes who wanted to use the @ symbol at the post title.

**Comment by hypest** [comment] 2021-05-12 07:07
Issue seems to have started happening (on Android at least) with v1.50.1 of gb-mobile.

**Comment by guarani** [comment] 2021-05-12 12:48
I can reproduce this as far back as WPiOS 16.6.1.2 (which is the oldest build on TestFlight). That [included](https://github.com/wordpress-mobile/WordPress-iOS/blob/40e66ade46e6525203e97665abb4b7b7a9aef325/Podfile#L157) v1.45.0 of Gutenberg Mobile.

**Comment by SiobhyB** [comment] 2021-09-02 15:06
I'm closing as it looks like this was fixed in https://github.com/WordPress/gutenberg/pull/31759. 🎉 I confirmed I'm not able to replicate on the latest version of the Android app on a physical Pixel 5.

**Closed as completed by SiobhyB** 2021-09-02 15:06 UTC
