### ISSUE TITLE
Focus loop flicker occurs if return button is double-clicked on a rich-text

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#953] opened 2019-05-03 14:05 UTC
Steps to reproduce:

Focus on a rich text block like paragraph
Focus on it
Double tap return button

A focus loop occurs as seen here:

![rich-text-focus-loop1](https://user-images.githubusercontent.com/5032900/57142609-a83bff80-6dc5-11e9-9b5a-9f0850d3cfc2.gif)

Tested on branch `develop`, commit `82228c565361915daaaf4a3dbec22cda721159f3`

**Comment by koke** [comment] 2019-05-03 20:31
Have you been able to verify on device as well as the simulator? This seems like a high priority one, but  I couldn't reproduce on iPhone XS, WPiOS with gutenberg-mobile 1.4

**Comment by koke** [comment] 2019-05-03 21:27
I also can't reproduce this in simulators in `release/1.4.0`, either on WPiOS or the demo app

**Comment by pinarol** [comment] 2019-05-06 07:52
Yes I can see it on the device also (iPhone 6, iOS 12.0.1):

![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/5032900/57212419-51fcd580-6fec-11e9-81e2-83a5453cf0f5.gif)

This is running on WPiOS develop commit `080b6f5860e74c243df457bb1a77bdbc0708bb3e` with dependency to gutenberg 1.4.0

**Comment by hypest** [comment] 2019-05-06 08:13
👋 @pinarol , can you also check if it happens before https://github.com/wordpress-mobile/gutenberg-mobile/pull/928 was introduced? There were some changes in some flags in that PR and just want to make sure it didn't introduced this issue as a regression. Thanks!

**Comment by pinarol** [comment] 2019-05-06 08:47
hey @hypest I checked with gutenberg 1.3.0 and I can repro this there too, so it doesn't look like it is related to that PR.

**Comment by pinarol** [comment] 2019-05-06 08:55
Another thing I noticed, I can't repro the issue on Internal-Release configuration, it happens only on Debug. So it might have sth to do with the speed of the bridge communication. This lowers urgency of the issue. But still, it'd be good to know the root cause 🤔

**Comment by etoledom** [comment] 2019-05-20 18:11
I fail to reproduce this in release builds too, so I'm moving this to `Future` and removing my assignment.

**Comment by k9yyy** [comment] 2019-09-27 10:13
This bug can be 100% triggered by quickly tapping between two blocks repeatedly. Tested on iPhone 6s with iOS 13, on the App Store version of WordPress iOS.

I guess in the `AztecView` class (`react-native-aztec/src/AztecView.js`), `isFocused()` being a bit behind of the actual focus status may be causing the focus loop? I don't have an Xcode environment so I can't test the code to be sure though.

**Comment by mchowning** [comment] 2019-09-27 11:22
I've also been able to recreate this on a release build. It does seem to be *much* easier to recreate this on a debug build (I had to do lots of very fast tapping to see it on a release build). 

WP Internal 13.3.0.20190926
physical iPhone XR
iOS 12.4.1

**Comment by designsimply** [comment] 2020-04-24 17:49
This was reported internally and I am copying relevant steps and notes here for reference:

> Steps I think I took:
> 
> 1. Started at My Sites, clicked on bishop.blog.
> 1. Clicked Media, “+”, Choose from My Device.
> 1. Selected the 2:33 minute-long video, Add 1.
> 1. Waited for the spinning hourglass circle to complete. The video’s transparency went away.
> 1. Clicked on the video, clicked the Share icon in the top-right. I think I copied the URL, but didn’t end up pasting it anywhere.
> 1. < Media, < Back, Blog Posts, "+"
> 1. Added a title “Pavane in Progress” or something like that.
> 1. Clicked down one block, clicked the blue “+”, chose Video.
> 1. In the Video block, I clicked Add Video, and chose WordPress Media Library.
> 1. I selected the video I wanted to insert, (there was a pause by me here, but I don’t remember how long I waited), and then clicked down one block to start typing.
> 
> Potentially helpful info:
> 
> * It’s a new iPhone 11 Pro
> * It was updated to 13.4.1 about 24 hours before this occurred
> * The internal beta was not installed, so there were never 2 versions of the WP mobile app on there
> * Everything is set to auto-update.
> * The app version is 14.5 WP iOS
> * site using a .blog domain
> * The video is 2:33 minutes long and was recorded on the same iPhone.

<sup>(internal reference: p4a5px-2yi-p2 h/t @andrealeebishop)</sup>

**Comment by maxme** [comment] 2020-04-27 08:16
I tried on an iPad with a debug build and I wasn't able to reproduce it. Do we have a way to detect this loop? At least for debugging and getting an idea of how many users this is affecting.

**Comment by designsimply** [comment] 2020-05-13 02:38
I observed a similar focus loop issue while testing https://github.com/wordpress-mobile/gutenberg-mobile/issues/2254 which reported a lag when selecting multiple images to add to the Cover block with the Free Photo Library upload option. I was able to reliably replicate the focus loop problem using WPiOS 14.8.0.1 TestFlight beta by doing the steps in the 2254 issue and then tapping on the "Add title" field. ([4m5s](https://cloudup.com/cFXEWAZuaaV))

![2254-wpios-14 8-rc-2](https://user-images.githubusercontent.com/1119271/81752254-5fa23200-946e-11ea-97e2-7e6fae780024.gif)
<p style="clear:both;"><sup>Tested with WPiOS 14.8.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by pinarol** [comment] 2020-05-13 09:10
Thank you for reporting that @designsimply 

@dratwas Let's discuss what we can do about this focus loop quickly as a hotfix. I know we were planning to do a [refactor](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1702#issuecomment-567831623), but we need to upgrade react native for that and it wouldn't be quick.

I think we can consider limiting the selection to only 1 image on Cover block, wdyt?

**Comment by dratwas** [comment] 2020-05-13 09:50
Hey @pinarol I totally agree that we can limit the selection in cover block to single image/video. I'm working on it ATM :)

**Comment by pinarol** [comment] 2020-05-13 09:54
Thanks. It turns out allowing multiple uploads on Cover was not an intended behavior anyway.

**Comment by dratwas** [comment] 2020-05-13 11:26
I created a PR with the fix for that https://github.com/wordpress-mobile/WordPress-iOS/pull/14108

Thanks to that the cover block is in a single selection mode.

**Comment by designsimply** [comment] 2020-08-19 01:06
I saw a focus loop happen again while I was testing cover blocks in 15.5 beta testing. I caught the last part of it on video and wanted to mention it and to note I tried to replicate and couldn't reliably replicate the problem this time. ([52s](https://cloudup.com/cOI9-rTJBwj))

**Comment by designsimply** [comment] 2020-09-16 18:35
Another focus loop was reported by a user in 3312531-zen running iPad Pro latest gen 12.9” WPiOS 15.6. Examining the video they provided, it looks like it happened after tapping back and forth between a couple paragraph blocks and then tapping the three-dot menu at top right.

<sup>(internal reference: p9ugOq-1gR-p2#comment-2566)</sup>

**Comment by rossanafmenezes** [comment] 2020-09-17 22:23
Hi everyone. It sounds like this user is having a similar issue on this app review today. 

Device Galaxy Note10+ 5G (d2xq)
App version 915 (15.6)
OS Android 10
User: Vampire Nox

**Comment by designsimply** [comment] 2021-02-17 16:17
👋  I added "flicker" to the title because whenever I go to search for this issue I keep not finding it and forget the phrase "focus loop". Hopefully it will help others find this report more easily if they find additional cases to note.

**Comment by dcalhoun** [comment] 2021-02-23 20:08
I am able to recreate a focus loop/flicker in WordPress iOS 16.7 by quickly tapping between two paragraphs. Arrived here from related #3085.

**Device:** iPhone 11 Pro
**App Version:** 16.7
**OS:** iOS 14.4

https://user-images.githubusercontent.com/438664/108901333-5e4a8c00-75e0-11eb-9cf7-f299e0c4ff12.MP4

**Closed** 2023-08-03 07:12 UTC
Labels: [Type] Bug, Writing Flow
