### ISSUE TITLE
Editing unsupported blocks is disabled on Jetpack and Atomic sites accessed via older WP.com accounts

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/gutenberg-mobile#3425] opened 2021-04-27 20:27 UTC
**Describe the bug**
A Jetpack-site recently connected to a WPCom account older than December 2018 won’t display the option to open the Unsupported Block Editor. The same applies to Atomic sites.

**To Reproduce**
_Using a WPCom account created before December 2018_, follow the steps outlined for [UBE TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc005). 

<details>
<summary>Click to view detailed TC005 steps</summary>

#### Precondition

For this test, you need a self-hosted site with the Jetpack plugin installed, activated and connected to a WP.com account. Here are the steps for creating this if needed:

1. Create a site on https://jurassic.ninja/
2. Connect the Jetpack plugin (it comes pre-installed) to a WP.com account
3. By default, Gutenberg is the default editor so no action required there

### Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack

1. On the site described above, add a post, then add a block that's not yet supported on mobile (e.g. Audio at time of writing) via the site's WP Admin web interface
2. Log into the WordPress mobile app using the WP.com account that was used to connect Jetpack to the self-hosted site
3. Open the post and expect to see the unsupported block rendered as a placeholder with the text "Unsupported"
4. Tap the `(?)` icon and expect to see an option to enable `Login with WordPress.com`.
5. Tap on that option, and enable `Loogin with WordPress.com` on the screen presented.
4. Go back and tap the `(?)` icon.
5. Expect the option to edit the block in a web browser to be shown
6. Tap the edit in a web browser button and expect a web view requesting to `Login with WordPress.com`.
7. Tap on said option and expect the block to be shown, ready to edit, on a new screen
7. Edit the block content (e.g. update its caption)
8. Tap the Continue button and expect to be taken back to the block editor
9. Publish the post and verify it contains the edits

</details>

**Expected behavior**
The option to "Log in with WordPress.com" is presented, which allows editing the unsupported block via a web view. 

**Actual behavior**
On Android, you are only presented with a notice that the block is unsupported. On iOS, you are provided a message regarding Jetpack security settings, but the "Open Jetpack Securty settings" button appears to not do anything when tapped. 

**Screenshots**
| Android | iOS |
| --- | --- | 
| ![android-jetpack-no-ube](https://user-images.githubusercontent.com/438664/116308065-aca91200-a76c-11eb-97e0-b151abec3d77.jpg) | ![IMG_087C92A157B1-1](https://user-images.githubusercontent.com/438664/116308114-bcc0f180-a76c-11eb-953a-4bed815db995.jpeg) | 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20, iPhone SE
 - OS: Android 11, iOS 14.4.2
 - Version: 17.1

**Additional context**
Both Android and iOS fail to pass the TC005 test case, but in a different manner.

**Comment by jd-alexander** [comment] 2021-04-27 21:01
Thanks for flagging this @dcalhoun I started investigating the issue and I am thinking it may be API related. Here's the[ logic within the Android codebase](
https://github.com/wordpress-mobile/WordPress-Android/blob/d26723bd10a48335e03e32f3b957e019e34b3179/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2265):

It seems that the API is returning `classic` instead of `gutenberg` for the site's `WebEditor` so that is causing the UBE to not be enabled thus the logic `&& "gutenberg".equals(mSite.getWebEditor()))` fails even though the block editor/gutenberg is being utilized in the self hosted Jetpack enabled instance. 

Below is a screenshot of my site as a `SiteModel` and the associated `WebEditor` property.

<img width="597" alt="Screenshot 2021-04-27 at 3 52 00 PM" src="https://user-images.githubusercontent.com/1509205/116312126-a9fceb80-a771-11eb-9fc0-a77f744961bb.png">

**Comment by enejb** [comment] 2021-04-27 22:25
I notice that on my test jetpack site( selective-squid.jurassic.ninja ) the user I was using would always return "Classic" even though the site didn't have the classic editor installed. Which is definitely not expected. 🤔

**Comment by jd-alexander** [comment] 2021-04-28 00:34
True. I noticed that we are using`editor_web` when the `editor_mobile` property exists and is already being utilized in other parts of the app like [here](https://github.com/wordpress-mobile/WordPress-Android/blob/6d2c22a573c726348a2f8b13281969109cff1c51/WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java#L209 ) so I was wondering if this is being done because the UBE is editing blocks via the web. Probably @guarani will be able to shed some light on this but overall, I think `webEditor` logic in the API needs investigation.

**Comment by mchowning** [comment] 2021-04-29 12:34
I believe there was a known issue where a Jetpack-site recently connected to a WPCom account older than December 2018 won’t display the option to open the Unsupported Block Editor. I'm not sure whether that is still an issue, but could that be what we're seeing here?

Reference: p9ugOq-Zz-p2#comment-2626

**Comment by jd-alexander** [comment] 2021-04-29 14:04
@mchowning that is indeed the issue that we are seeing here. Thanks for the reference to that comment.

**Comment by jd-alexander** [comment] 2021-04-29 14:32
So the proper course of action here is to simply update the test checklist with this, as a known issue, so the results/test is ignored until it is resolved right @mchowning ?

**Comment by mchowning** [comment] 2021-04-29 15:12
> So the proper course of action here is to simply update the test checklist with this, as a known issue, so the results/test is ignored until it is resolved right @mchowning ?

Instead of ignoring the test, could we just update the test so it requires a WPCom account newer than December 2018? It sounds like the test case should work in that case if I'm understanding correctly.

**Comment by dcalhoun** [comment] 2021-04-29 15:39
> Instead of ignoring the test, could we just update the test so it requires a WPCom account newer than December 2018? It sounds like the test case should work in that case if I'm understanding correctly.

@mchowning thank you for providing this insight. This is my understanding of the situation too. I have opened https://github.com/wordpress-mobile/test-cases/pull/74 to update the test case. I will keep this issue open, but update the details regarding the age of the WP.com account.

**Comment by jd-alexander** [comment] 2021-04-29 16:29
> Instead of ignoring the test, could we just update the test so it requires a WPCom account newer than December 2018? It sounds like the test case should work in that case if I'm understanding correctly.

Ah, that makes sense. Thanks!

> I have opened wordpress-mobile/test-cases#74 to update the test case. I will keep this issue open, but update the details regarding the age of the WP.com account.

Thanks for wrangling that @dcalhoun

**Comment by enejb** [comment] 2021-04-29 21:15
What would the fix on the backend look like?

Should we be sending all atomic users to use the new editor.
I think if the site doesn't have the classic editor plugin active we should just default to the block editor and not base it on whether the user has been with us for a while :) 

But since this is a web editor preference we will need to get the web folks involved. @mchowning do you know if this is a mobile specific endpoint? Can we update it to work the way we would expected now?

**Comment by mchowning** [comment] 2021-04-29 21:49
Let's wait to get some input from @hypest and @guarani on this. It will be a few days before they'll be able to respond most likely, but this isn't an urgent issue, so we should be fine to wait. (Some related context: p1599153486338800-slack-CKZHG0QCR)

**Comment by guarani** [comment] 2021-05-13 01:41
> It seems that the API is returning `classic` instead of `gutenberg` for the site's `WebEditor` so that is causing the UBE to not be enabled thus the logic `&& "gutenberg".equals(mSite.getWebEditor()))` fails even though the block editor/gutenberg is being utilized in the self hosted Jetpack enabled instance.

I agree this would cause the UBE to not open. It needs to open Gutenberg on the site's WP Admin to function, so it uses the web setting to know if this is available.

To verify that the issue is present with old accounts, I connected a brand-new self-hosted site to an old WP.com account (July 2012 according to https://wordpress.com/me/account), queried the `/sites/{site_id}/gutenberg` endpoint and it does return `editor_web:"classic"` even though the **block editor** is presented when I open a new post (`/wp-admin/post-new.php`).

<img width="910" alt="Screen Shot 2021-05-12 at 20 07 46" src="https://user-images.githubusercontent.com/1898325/118059146-d150dc80-b35d-11eb-9786-4d13fc8290c0.png">
 
I then connected the same site to a newer WP.com account (created August 2020) and got `editor_web: "gutenberg"`. In both this and the previous scenario, I saw `editor_mobile:""`, but that isn't relevant here.

--- 

I've seen commentary suggesting that the editor preference setting **does not** determine which editor is shown on the web (see p1599465316035900/1599153486.338800-slack-CKZHG0QCR). I wonder if it's possible to stop using this API, and try loading the web view in all scenarios. That way, if it fails to load or loads something that's not the block editor, we could display a more generic message along the lines of "Unable to load the block editor. Please ensure that Gutenberg is enabled on your site and try again."

**Comment by hypest** [comment] 2021-05-13 08:47
>  wonder if it's possible to stop using this API, and try loading the web view in all scenarios. That way, if it fails to load or loads something that's not the block editor, we could display a more generic message along the lines of "Unable to load the block editor. Please ensure that Gutenberg is enabled on your site and try again."

I like that route. I'd even add, what about not even trying to detect if there has been an error loading and instead just have a splash/loading screen that states something like "Loading the block editor directly from your site... Please ensure it's enabled there".

**Comment by guarani** [comment] 2021-05-20 23:20
I updated the title and description to include that this bug is present on Atomic sites as well.

**Comment by dcalhoun** [comment] 2021-05-21 19:13
@Guarani I was testing a [1.53.1 release build](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3535#issuecomment-846156482), which does not include https://github.com/wordpress-mobile/WordPress-iOS/pull/16468, and noticed an oddity for the [TC004 test case](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc004) for Classic-enabled Atomic sites. 

Following the TC004 steps _with an account registered before December 2018_, I see the unexpected results already captured in this issue, as you mentioned in https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425#issuecomment-845545064.

However, after following the TC004 steps _with an account registered after December 2018,_ I am presented the "Edit using web editor" button, even though the Classic editor is enabled and set as the default. Tapping the button loads an empty web view. My understanding is the expectation is that there should not be an option to edit the block in a web browser. 

Do you believe this is related to this issue or should I open a new issue? Thanks!

https://user-images.githubusercontent.com/438664/119186357-9de90e80-ba3d-11eb-8b98-9582e4b93d0e.MP4

**Comment by guarani** [comment] 2021-05-24 19:19
Hi @dcalhoun 👋 

> However, after following the TC004 steps _with an account registered after December 2018,_ I am presented the "Edit using web editor" button, even though the Classic editor is enabled and set as the default. Tapping the button loads an empty web view. My understanding is the expectation is that there should not be an option to edit the block in a web browser.

Thanks for reporting! I could reproduce this as well.

> Do you believe this is related to this issue or should I open a new issue? Thanks!

Fixing this issue involves [removing the Unsupported Block Editor's dependency of the editor preference API](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425#issuecomment-840416798) – so my hunch is that it may have the side-effect of fixing the bug you're reporting here. However, to make this gets addressed properly, I think it's best to create a new issue. 🙇

**Comment by dcalhoun** [comment] 2021-05-24 19:37
@Guarani thank you! I have created #3544.

**Comment by guarani** [comment] 2021-05-25 19:16
I've experimented with messaging on the Unsupported Block Editor loading screen. It consists of a prompt asking users to make sure the block editor is enabled on their site, along with a loading animation (borrowed from the My Site → People screen). The idea here is that in the unlikely scenario that a user _doesn't_ have the block editor enabled on their site, the message will be enough information for them to know the reason the UBE fails to load.

**Success case**: The block editor is enabled on the site.

https://user-images.githubusercontent.com/1898325/119552624-ba03ed00-bd68-11eb-8fe1-fc55691100cb.mov

**Failure case**: The block editor is disabled on the site (the Classic plugin was activated).

https://user-images.githubusercontent.com/1898325/119559033-26361f00-bd70-11eb-96b9-4dba16446c3b.mov

### On enabling the UBE on all self-hosted sites

When the UBE was launched last year, it shipped without support for non-Jetpack self-hosted sites. This was because the editor preference API which the UBE relied upon is a WP.com REST API and is not available in the XML-RPC API that these sites use.

Now that we've removed the dependency on this API – by attempting to load the UBE regardless of whether or not the block  editor is available on the site's backend – it makes sense to revisit this and enable self-hosted sites if possible.

The video above of the UBE was recorded on a non-Jetpack self-hosted site. If I don't run into any issues with this type of site and everything seems to work as expected, I think we can enable this when this ships.

### Android work needed

We'll need an Android dev to implement this on WPAndroid. The loading animation I got from My Sites → People doesn't seem to be there on WPAndroid. If it's iOS-specific we could change the animation or use something roughly equivalent on WPAndroid.

### Edge cases

The loading screen needs to handle the scenario where the user is prompted to enable WP.com SSO in Jetpack settings (affects both _Atomic_ and _Jetpack-connected self-hosted_ sites)

---

I'll be going through the [UBE test cases](https://github.com/wordpress-mobile/test-cases/blob/27653e80073408adda42e33b9954991143a92d9e/test-cases/gutenberg/unsupported-block-editing.md), and if everything (including the failure cases) looks good I'll make a PR to implement this in WPiOS.

**Comment by hypest** [comment] 2021-05-26 07:56
Looks promising @guarani ! We probably need some form of timeout and reach an error view as I was there looking at the animation and thought that "ok, it's still trying" :). Perhaps adding a 10sec timeout for that and change the animation to a failure state. On the "loading" state, perhaps the copy can also inform "This will fail if the block editor is disabled on the site" to set better expectations.

> it makes sense to revisit this and enable self-hosted sites if possible.

Oh, thanks for surfacing that! Lemme ask, will UBE work in non-Jetpack-self-hosted if the block editor is normally enabled? If yes then it's a great idea to yeah, enable UBE for all sites!

> We'll need an Android dev to implement this on WPAndroid. 

👍, good note. Let's bring someone in after we finalize the implementation here.

**Comment by guarani** [comment] 2021-05-27 19:10
> Looks promising @guarani ! We probably need some form of timeout and reach an error view as I was there looking at the animation and thought that "ok, it's still trying" :). Perhaps adding a 10sec timeout for that and change the animation to a failure state. On the "loading" state, perhaps the copy can also inform "This will fail if the block editor is disabled on the site" to set better expectations.

Yes, that's true. I'll show some sort of "Loading Failed Screen" in this case.

> Oh, thanks for surfacing that! Lemme ask, will UBE work in non-Jetpack-self-hosted if the block editor is normally enabled? If yes then it's a great idea to yeah, enable UBE for all sites!

I'm not sure what you mean by "normally enabled". In the above video, I used a self-hosted site which came with the block editor enabled and it worked. If there's another scenario which you think I could check, please let me know and I'll verify it works there, too.

> > We'll need an Android dev to implement this on WPAndroid.
> 
> 👍, good note. Let's bring someone in after we finalize the implementation here.

Sounds good! 🙇

**Comment by SiobhyB** [comment] 2021-06-02 11:18
👋 @hypest gave a hint that I might be working on the Android side of this PR in a 1:1. As I had a bit of time on my hands towards the end of last week, I began to experiment and came up with something that works, which can be found at https://github.com/WordPress/gutenberg/pull/32395. Even if I'm not officially assigned to this, I wanted to share just in case it's useful. :)

**Comment by guarani** [comment] 2021-06-02 14:22
> 👋 @hypest gave a hint that I might be working on the Android side of this PR in a 1:1. As I had a bit of time on my hands towards the end of last week, I began to experiment and came up with something that works, which can be found at [WordPress/gutenberg#32395](https://github.com/WordPress/gutenberg/pull/32395). Even if I'm not officially assigned to this, I wanted to share just in case it's useful. :)

Thanks a lot for doing that, @SiobhyB! I looked at the screenshots and it looks great 💯 

---

Looping back to the discussion about enabling the UBE on non-Jetpack self-hosted sites, it sounds from https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425#issuecomment-848553448 that we have the all-clear for this, is that correct @hypest?
I want to link to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2482, which can be used to track this work.

**Comment by hypest** [comment] 2021-06-03 12:08
👋 @guarani !

> I'm not sure what you mean by "normally enabled". In the above video, I used a self-hosted site which came with the block editor enabled and it worked. If there's another scenario which you think I could check, please let me know and I'll verify it works there, too.

Ah, I probably misread [your original report](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425#issuecomment-848194586), indeed, you mention there that you tested on non-Jetpack-self-hosted site. No, wasn't meaning to bring up a different case so, all good 👍.

> Looping back to the discussion about enabling the UBE on non-Jetpack self-hosted sites, it sounds from #3425 (comment) that we have the all-clear for this, is that correct @hypest?

Have we tested the new approach (the timing-out loading screen) against Jetpack sites? Can we make sure it works OK in the two cases there (1. Jetpack site accessed via WPCOM and 2. Jetpack site accessed as self-hosted directly, 3. Atomic)? Sounds to me that yeah, if we have tested all cases then all-clear!

**Comment by guarani** [comment] 2021-06-03 15:53
Hi @hypest 👋 

> > Looping back to the discussion about enabling the UBE on non-Jetpack self-hosted sites, it sounds from #3425 (comment) that we have the all-clear for this, is that correct @hypest?
> 
> Have we tested the new approach (the timing-out loading screen) against Jetpack sites? Can we make sure it works OK in the two cases there (1. Jetpack site accessed via WPCOM and 2. Jetpack site accessed as self-hosted directly, 3. Atomic)? Sounds to me that yeah, if we have tested all cases then all-clear!

Yes, I've [tested the iOS PR on all the UBE test cases](https://github.com/wordpress-mobile/WordPress-iOS/pull/16586#issuecomment-849986556), which include self-hosted sites accessed via WP.com as well as via username/password. It also includes Atomic sites so I think that covers all the site types we support. Thanks for checking though 🙇.

**Comment by hypest** [comment] 2021-06-23 10:19
Reopening to better reflect that not all platforms have been updated/fixed yet (the [Android side is ongoing](https://github.com/wordpress-mobile/WordPress-Android/pull/14762) at the time of writing).

**Comment by guarani** [comment] 2021-06-23 14:10
> Reopening to better reflect that not all platforms have been updated/fixed yet (the [Android side is ongoing](https://github.com/wordpress-mobile/WordPress-Android/pull/14762) at the time of writing).

Thanks for catching, @hypest! I didn't expect GitHub to close this issue when that PR was merge, ~~it looks like it might have been caused by the word "fixes" that I included in the parenthesis~~:

> Addresses wordpress-mobile/gutenberg-mobile#3425 (fixes for iOS, not Android)

Update: It was caused by the commit message in https://github.com/wordpress-mobile/WordPress-iOS/commit/6e5fc656a35b0559f47660cc7eeaed5a8644fee7, oops!

**Comment by hypest** [comment] 2021-06-24 14:42
👋 @guarani , sorry, getting a bit confused and wanted to check with you to clear up: with the recent work here for the loading screen, have we indeed ended up enabling UBE for non-Jetpack self-hosted sites?

**Comment by guarani** [comment] 2021-06-28 14:12
> 👋 @guarani , sorry, getting a bit confused and wanted to check with you to clear up: with the recent work here for the loading screen, have we indeed ended up enabling UBE for non-Jetpack self-hosted sites?

@hypest sorry for the confusion. That's been put in a separate issue, https://github.com/wordpress-mobile/gutenberg-mobile/issues/2482. This was done to make sure this bug fix issue is addressed independently of any issues that might arise with enabling the UBE on non-Jetpack self-hosted sites.

**Comment by hypest** [comment] 2021-06-30 13:59
Ah, I see, thanks for clarifying @guarani !

Fine by me for the separate ticket for non-Jetpack self hosted sites. In that case, and since [the Android side fix also landed](https://github.com/wordpress-mobile/WordPress-Android/pull/14762), can we close this ticket?

**Comment by guarani** [comment] 2021-06-30 23:59
> Fine by me for the separate ticket for non-Jetpack self hosted sites. In that case, and since [the Android side fix also landed](https://github.com/wordpress-mobile/WordPress-Android/pull/14762), can we close this ticket?

Good call, closing this issue now that both platforms have been addressed.

**Closed as completed by guarani** 2021-06-30 23:59 UTC
Labels: Writing Flow, Blocks, [OS] iOS, [OS] Android, Jetpack, [Type] Regression, Unsupported Block Editor
