### ISSUE TITLE
Nearly invisible text color on bright background

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#4637] opened 2022-03-09 02:11 UTC
**Describe the bug**

It was reported in 4838810-zd-woothemes that the text in the WPAndroid 19.2 is nearly invisible because it is white in color on a bright background. I was able to reproduce this in WPiOS 19.3.

**To Reproduce**
1. On a WPCOM site, activate the Livro theme
2. Go to https://wordpress.com > My Site > Appearance > Editor, change the background color to a bright color (#fcf4f4 in the reported case), set the text and link color to "Default (Black)"
3. Create a test post on Calypso with a Paragraph block that contains text, save the post as a draft or publish it
4. Open up the post in the app, noticed the text is white in color

**Expected behavior**

I would expect the app to honor the color settings on the site and displayed the text color in the app's editor.

**Screenshots**

![Screenshot_2022-03-07-15-35-36-544_org wordpress android](https://user-images.githubusercontent.com/40906847/157358725-92414991-f6e9-4633-a050-ef5689551b1a.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi M2103K19G
 - OS: Android 11

Also reproduced in iPhone 11, iOS 15.3.1.

**Comment by hypest** [comment] 2022-03-09 07:01
Confirmed from my side as well.

@geriux , since you have recently worked on picking the colors from the theme, is this behavior here expected? 🤔

**Comment by geriux** [comment] 2022-03-09 08:33
Hey 👋 

>is this behavior here expected? 🤔

It is not expected, this issue was related to custom colors not loading correctly on the editor. This was fixed in https://github.com/WordPress/gutenberg/pull/38417 which will ship on `19.4`. I checked that this works correctly in the current beta.

**Comment by hypest** [comment] 2022-03-09 09:57
Thanks for the update @geriux !

@reginabally , I will go ahead and close this ticket as "addressed/fixed" but happy to reopen if we see that the fix is not perhaps covering the issue.

**Closed as completed by hypest** 2022-03-09 09:57 UTC
Labels: [Type] Bug
