### ISSUE TITLE
Cursor is large when inserting new list items

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/gutenberg-mobile#4577] opened 2022-02-11 18:47 UTC
**Describe the bug**
When inserting new list items under an existing item (except for the last), the flashing cursor can appear larger than expected.

**To Reproduce**
1. In WPiOS or in the Demo App, add a List block using the editor (both ordered and unordered lists are affected)
2. Add a few items to the list
3. Select any existing item but the last
4. Tap return to insert a new item
4. Observe the cursor

**Expected behavior**
The cursor should stay the appropriate size for the text being input.

**Screenshots**

https://user-images.githubusercontent.com/2092798/153651186-154757f0-9f7f-4fb1-a80e-879c793c9e87.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.3.1
 - Version: iOS 19.2.0.1 / GB Mobile v1.71.1

**Additional context**
It may be worth inspecting the [attributes](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/AttributedStrings/Tasks/AccessingAttrs.html#//apple_ref/doc/uid/20000161-BAJBBCBI) of the string when this happens.

**Comment by hypest** [comment] 2022-02-14 12:03
Replicated it on v18.1 from August 2021 as well. Might be happening on even older versions but couldn't test those on my iOS15 device (they don't run on this OS version).

**Comment by geriux** [comment] 2024-06-18 15:55
Closing since I can't reproduce this with the latest version of the List block that uses inner blocks.

**Closed as completed by geriux** 2024-06-18 15:55 UTC
Labels: [Type] Bug, [OS] iOS
