### ISSUE TITLE
Enter.key fails to split paragraph block after merge

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#851] opened 2019-04-10 11:59 UTC
I discovered this odd bug while testing this: https://github.com/wordpress-mobile/gutenberg-mobile/pull/756 , but it appears to be an issue on the latest `develop` branch (tested on Android emulator).

**Description:**
When a paragraph block has been split, and re-merged, the [Enter] key fails to split the block, but instead inserts a newline at the "seam" of the previous split/merge. Also, it seems a word is deleted just before the "seam" as well.

**Steps to reproduce:**
1. Place caret just after "dictum" in the "Lorem ipsum..." block.
2. Press [Enter] (observe that the block splits, with the new block beginning with "orci...").
3. Press [Backspace] (observe that the blocks "re-merge", with the caret just after "dictum").
4. Tap the end of the block to place caret at the end (after "...elit.").
5. Press [Enter].

**Expected result:**

* The previous paragraph remains intact.
* A new paragraph block is created below, which now has focus (showing placeholder text).

**Actual result:**

* The current paragraph is still active, with a newline added before "orci".
* The word "dictum" is removed.
* The caret is now on the new line, before the word "orci".

**Screencast:**

<img src="https://user-images.githubusercontent.com/8507675/55876739-aa9ea580-5bdb-11e9-8d24-0fa63c3944d8.gif" width="360">

**Comment by hypest** [comment] 2019-05-24 12:03
I think this issue doesn't happen anymore. Can you retry and close if not happening @mkevins ?

**Comment by daniloercoli** [comment] 2019-05-24 14:13
Closing this issue since cannot reproduce it anymore. Tried different keyboards and HW keyboard.

**Closed by daniloercoli** 2019-05-24 14:13 UTC
Labels: Writing Flow, bug

**Comment by mkevins** [comment] 2019-05-27 01:26
Tested on `392df98bfeedfe8615657448f62439c888649444` and confirmed that this issue has been resolved. I tried these steps on latest develop (`0533baf76be6fa9c9b0d3c6fa18855f5ed4d0083`), but there seems to be a regression of the block merge crash, so I could not perform these steps there.
