### ISSUE TITLE
List block - performance issues

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#902] opened 2019-04-19 22:52 UTC
Make sure that you have some low-end device, e.g. Nexus 5x with Android 8.1.

Scenario :

1. Create a list block with 10 list items
2. Create an image block with some random image
3. Create a paragraph block with some content
4. Create a second list block with 10 list items
5. Create an image block with some random image
6. Create a header block with some content
7. Create a third list block with few elements
8. Start fast typing/removing text from the list block

![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/28219092/56447075-44e5a400-62d4-11e9-8ed3-7f9fd39c9486.gif)

Result: Cursor will move automatically from newly created block to the previous block
Expected: Nothing odd should happen when type fast

**Comment by hypest** [comment] 2019-05-03 07:53
Not able to reproduce on my Nexus 5X (Android 7.1.2) on a production build of wpandroid, using gutenberg-mobile at hash f4e91b94 (which includes the #928 fix).

Will close this but, feel free to reopen if the issue is still happening.

**Closed by hypest** 2019-05-03 07:53 UTC
Labels: Android, Blocks, bug
