### ISSUE TITLE
Format propagates to adjacent word after typing a space

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#824] opened 2019-04-05 09:51 UTC
1. Start with two words text like "two words".
2. Place the cursor between the space and the "w".
3. Tap on "B" to turn on bold.
4. Type a few chars and press "space".

Notice the "word" becoming strong while it shouldn't.

Tested on Motorola G5 Plus, Android 8.1, WPAndroid alpha-160

**Comment by mkevins** [comment] 2019-04-10 13:00
I failed to reproduce this on Android emulator (I tried both the demo app `360a28`, and WPAndroid `3dde49`).

WPAndroid screencast:

<img src="https://user-images.githubusercontent.com/8507675/55880599-6532a600-5be4-11e9-98fc-0a67ce4172ce.gif" width="360">

**Comment by daniloercoli** [comment] 2019-04-10 13:16
I wasn't able to reproduce the issue and asked @mkevins to double check this. 
I'm closing this one, even though styling of text has lot of small bugs, and things to fix.

**Comment by koke** [comment] 2019-04-10 14:46
Interesting, I can still reproduce on WPAndroid 3dde49, both on a Pixel emulator, and on a Moto G5 Plus, which version of gutenberg-mobile were you running? I also tried running metro from gutenberg-mobile develop and still seeing the same issue.

![bugreport](https://user-images.githubusercontent.com/8739/55888689-1f5bea80-5bb0-11e9-9010-0c527b7298de.gif)

**Comment by daniloercoli** [comment] 2019-04-10 14:53
I tried develop `360a28b98d8dc11260dbcfe68fab92d78af670d3` on both Android 7 and Android 9 (real devices)

**Comment by koke** [comment] 2019-04-10 17:11
I've tried to debug this and I'm seeing something that I don't understand. When I press space, I'm getting a selectionChange event from Aztec with the selection and the cursor and the text dropping out anything after the cursor.

So if I had:

> Two *hey* |words

The event is sending

```js
{
    selectionStart: 8,
    selectionEnd: 8,
    text: "<p>Two <strong>hey </strong></p>",
}
```

**Comment by daniloercoli** [comment] 2019-04-11 12:39
Ok, so you need to use the`Gboard` keyboard to be able to replicate the issue. I was using Samsung, and the default AOSP keyboard, that's why I was not seeing it.

**Comment by mkevins** [comment] 2019-04-11 13:23
Interesting find! I wonder, is this something we should keep in mind for later, when creating UI tests?

**Comment by daniloercoli** [comment] 2019-04-11 14:21
This issue was originally reported in Aztec here:https://github.com/wordpress-mobile/AztecEditor-Android/issues/622

Should we keep this open to not losing track of it?
How about the priority of it? It was opened more than 1 year ago.

**Comment by hypest** [comment] 2019-05-06 07:19
Let's keep this ticket open for a bit since this repo is more closely monitored at the moment.

> I'm getting a selectionChange event from Aztec with the selection and the cursor and the text dropping out anything after the cursor.

That's a know behavior of the Gboard virtual keyboard (and probably other keyboards too). Relates to this ticket as well: https://github.com/wordpress-mobile/gutenberg-mobile/issues/898.

**Comment by guarani** [comment] 2021-09-17 18:42
I couldn't reproduce this on WPAndroid 18.2, I tried using both the Gboard and Samsung Keyboard.

https://user-images.githubusercontent.com/1898325/133837778-62b11276-4479-471c-985b-92f2e64acae5.mp4

Since there hasn't been activity on this issue for over a year, and I can't reproduce, I'm going to go ahead and close. If anyone would like to re-test and confirm it's fixed, that would be great, but otherwise I think closing is the best option. Please feel free to re-open if you think otherwise.

**Closed by guarani** 2021-09-17 18:42 UTC
Labels: [Type] Bug, Writing Flow, [OS] Android, [Pri] Medium, HACK week
