### ISSUE TITLE
Media Upload fails to upload image when leaving and coming back in

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#1928] opened 2020-02-18 14:39 UTC
**Describe the bug**
Close/Re-opening a page with ongoing image uploads in a Gallery Block causes the image to be marked for retry.

**To Reproduce**
1. Create a new Draft Page or select an existing page. 
2. Add a Gallery or Image Block
3. Select Add Media
4. Select "Choose From Device"
5. Select an Image
6. While the image is uploading; select back
7. Go right back into the Page

**Error:** Image gets locked into a mode where it's tagged to be uploaded
**Expected:** Image should upload successfully and reflect the proper state. 

https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001

**Expected behavior**

**Screenshots**
![FailedUpload_GalleryTC001 2020-02-18 09_38_50](https://user-images.githubusercontent.com/3384451/74745915-96cbc300-5232-11ea-9248-adcba01cb261.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10
 - Version API 29

[APK used to test](https://37929-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-11331-build-37929.apk)

**Additional context**
Discovered during regression testing for [Release 1.23.0](https://github.com/wordpress-mobile/WordPress-Android/pull/11331)

**Comment by pinarol** [comment] 2020-02-18 16:11
What happens when we dismiss the retry dialog? Does it complete successfully?

**Comment by chipsnyder** [comment] 2020-02-18 16:21
For me when the app was uploading a new page and a new image it was just hanging on the upload for a new page and never completing (waited for a few minutes). However, if I can fix this issue by:
1) Tap the image
2) Select Retry
3) Tap the image
4) Select Cancel 

Then the page uploads successfully. Just revalidated a few flows and this looks like it's an issue on other media blocks as well not just gallery.

**Comment by pinarol** [comment] 2020-02-18 17:15
I can repro this with the same apk on Android:

- Add an image block
- Start an upload
- Close/Re-open the post while the upload is still going on

Expected: 

- The post loads immediately showing an upload progress on the Image block
- Image upload continues and end up with success

Reality: 
 
- The post displays white screen until the upload is complete(the upload is observable on device's status bar only)
- There's no progress indication on Image block
- Image block still shows the local image even after waiting some time

**Comment by chipsnyder** [comment] 2020-02-18 17:16
After performing the steps in the previous comment, in the notification center, I see the Uploading dialog for "1 page and 1 file."
![screenshot-1582044835640](https://user-images.githubusercontent.com/3384451/74759988-b3bec100-5247-11ea-94bf-d29666fd9fb8.jpg)

To fix this apparent lock between the media uploader and the page publish, you can do one of the following:
Possible fixes are:
A) restart the phone
B) Click on the image and remove (either via remove on retry prompt or retry and cancel)
C) Loose network through airplane mode or wifi and get the network back. Then go back to site pages

Any of those seem to allow the page to upload successfully. 

Also worth noting in the HTML view of the page, you'll see a local URL for the media. However, in my case, when I went to https://wordpress.com/media/{site name}, then I saw the image had successfully uploaded.

**Comment by cameronvoell** [comment] 2020-02-18 23:19
So far I verified this Bug was not in Android release 14.1 and was introduced in 14.2. At the moment I'm focusing on these changes from 1.22 gutenberg-mobile release to see if they introduced the problem, and how we can fix both issues simultaneously - https://github.com/wordpress-mobile/gutenberg-mobile/pull/1686

**Comment by mkevins** [comment] 2020-02-19 05:25
Hi @chipsnyder :wave: ,

Thanks for testing this flow on the release. I was unable to reproduce this issue, following the same steps. I tried on:

* Commit `12fbfd07886f166a5f710120c0619096037818d6` w/ metro on
* The latest WordPress-Android apk: https://38071-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-11331-build-38071.apk
* The same apk that you and @pinar tested: https://37929-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-11331-build-37929.apk

via Pixel 3a (Android 10).

In all cases, I observed the expected behavior for this flow, so perhaps there is some subtle difference in our actions to arrive at different results (or maybe some race condition)?

Here is a screencast of my test:

<img src="https://user-images.githubusercontent.com/8507675/74804372-c7435800-532b-11ea-81f4-913391acb118.gif" width="360">

Can you see whether anything is different about the flow I used?

**Comment by chipsnyder** [comment] 2020-02-19 11:54
Hey @mkevins, In your gif, it looks like you might be creating a new post instead of a new page. Try creating a new page instead. In my testing posts were fine, but pages had problems.

**Comment by cameronvoell** [comment] 2020-02-19 18:51
> Reality:
The post displays white screen until the upload is complete(the upload is observable on device's status bar only)

I definitely was seeing the issue with Posts also, and I think Pinar was too, unless the above was a mistype. 

Still not sure why Matt is not producing the issue, his steps look the same as mine. I did have to switch to slower mobile network and make sure I was not loading super fast when switching back and forth. But the loading bar in Matt's video seems to show that the image is still loading, so not sure why he is not seeing the issue.

**Comment by pinarol** [comment] 2020-02-19 19:38
Right, I tried with a post as well.

**Comment by mchowning** [comment] 2020-02-19 22:17
I'm seeing the following in my testing:

1. Create a post and add a new image that must be uploaded
2. Exit the post editor
3. Reopen the post editor
4. Then 
    a. **If the image uploads _before_ I try to reopen the post in the editor:** the image id and url update correctly
    b. **If the image uploads _as the editor is opening_:** the image id and url do __*not*__ update and the local id and local file path remain. This results in the retry upload dialog when you tap on the image. But if I check on my media library online I can confirm that the image uploaded. In addition, exiting the post shows that the post is still a local draft, but exiting the posts screen and returning to it initiates the upload of the post. Of course, since the post has the local media id and file url, it will not display properly on the web.
    c. **If the image uploads _after_ the editor has reloaded the post:** the image updates with the correct id and url once the upload completes.

In the scenario where the upload finishes _after_ the post has been reopened in the editor (4c), I did not observe any UI indication that the upload was still in progress with _image blocks_. _Gallery blocks_, on the other hand, did have the upload progress bar as like in @mkevins [comment and gif](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1928#issuecomment-588042463).

I recreated this issue on the 14.1 release (the only other release I tested), so this does not appear to me to be a new regression.

I could not recreate this issue on iOS because iOS appears to block the user from reopening a post while it is in the process of being uploaded.

**Comment by pinarol** [comment] 2020-06-22 13:21
Should be resolved with associated PRs

**Closed by pinarol** 2020-06-22 13:21 UTC
Labels: [OS] Android, [Type] Bug
