### ISSUE TITLE
Tiled Gallery UX change to match Gallery - Columns

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#4285] opened 2021-11-24 16:50 UTC
Change tiled gallery columns to match gallery:
* Right now, tiled gallery columns is WYSWYG -- the columns shown in settings is what is shown in the preview
* Gallery, however, separates preview from settings; it shows a set 1-2 columns for portrait, 1-4 for landscape.
* Also, make sure to match web's HTML when there are no images; don't set columns attribute.

**Comment by illusaen** [comment] 2021-11-30 18:44
Linking to https://github.com/wordpress-mobile/gutenberg-mobile/issues/4147 as we found this after putting the PR up for 4147.

**Comment by illusaen** [comment] 2021-12-06 17:46
Still working on this; running into a maximum update exceeded error when looking at JTG block settings. This is being caused by setState being called recursively in an infinite loop. I think this is caused by TiledColumnsSetting:

`onChange={ value => {
						setColumnNumber( value );
						setAttributes( { columns: value } );
					} }`

Stopping due to HACK week this week; will pick up afterwards. Branch is called `columns-decoupling`.

Tried removing useEffects one by one in the main TiledGalleryEdit but unfortunately don't think it's any of those.

**Comment by guarani** [comment] 2022-01-03 19:11
My reading of this issue is that it is a duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/4147. Both issues describe under what conditions the number of columns shown in the editor can differ from the number of columns chosen by the user in block settings.

> Also, make sure to match web's HTML when there are no images; don't set columns attribute.

This seems like it should be addressed separately since it is about the block "column" setting (not how columns are rendered in the editor, which is the focus of this issue). 👋 @SiobhyB, did you run into an issue when fixing Tiled Gallery automated tests (possibly in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4263) where the block was setting the value of the columns attribute when no images were added? If so, was there an issue for that?

@illusaen I'm closing this for now, but please feel free to re-open id you don't agree it's a duplicate.

**Closed as completed by guarani** 2022-01-03 19:11 UTC
Labels: [Type] Bug, [Pri] High, Tiled Gallery block

**Comment by SiobhyB** [comment] 2022-01-04 14:55
> 👋 @SiobhyB, did you run into an issue when fixing Tiled Gallery automated tests (possibly in #4263) where the block was setting the value of the columns attribute when no images were added? If so, was there an issue for that?

Yes, that's right, I believe https://github.com/wordpress-mobile/gutenberg-mobile/issues/4262 is the issue you're remembering here, but let me know if there's something missing from it!

**Comment by guarani** [comment] 2022-01-04 17:36
Thanks! With that I think we can leave this issue closed since everything here appears to be covered by existing issues.
