### ISSUE TITLE
Nested Inner Block with Block Group Results in Unhideable Keyboard

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#3122] opened 2021-02-09 22:04 UTC
**Describe the bug**
When adding a block group as a nested inner block, as in Address block in Contact Info block, and then selecting and deselecting the block, the keyboard becomes stuck open.

This seems to only happen once you type something into Address block field, i.e. Street Address; the cursor then gets stuck there even when the focus is removed from the block.

**To Reproduce**
1. Go to post on site with Jetpack (also needs to be running with dev flag atm).
2. Add Contact Info block.
3. Click on Street Address.
4. Type text.
5. Click on Email.
6. See that keyboard is stuck open and even clicking on the hide keyboard button doesn't work. Also see that cursor is stuck on your text.

**Expected behavior**
Cursor should be removed from Address block when deselecting it and keyboard should be hidden.

**Screenshots**
![Feb-09-2021 16-03-39](https://user-images.githubusercontent.com/13263478/107434504-786c7080-6af0-11eb-9b65-5ffb687509ad.gif)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 14.4

**Comment by illusaen** [comment] 2021-03-11 20:18
Note: Leaving until can get some expert help. 

This seems to be a race condition that happens when typing in the inner block (i.e. Address Line) and then immediately clicking over to the outer field (i.e. email).

So far I've tried explicitly dismissing keyboard if focus was on an inner block and moving out, but unfortunately that doesn't fix the race condition; all that happened was that the keyboard would pop up, and then dismiss itself a bit after.

**Comment by dcalhoun** [comment] 2021-07-09 21:34
@illusaen I am unable to reproduce this and I noticed https://github.com/Automattic/jetpack/pull/19367 claims to fix this issue. I am closing this issue, but please reopen if you believe we still need it. Thanks! 🙇🏻

**Closed as completed by dcalhoun** 2021-07-09 21:34 UTC
Labels: [Type] Bug, [Pri] High
