### ISSUE TITLE
Videos added/edited on the web don't load in mobile editor

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#1152] opened 2019-06-18 17:27 UTC
1. On the web, create a post and add a video block. (I added a video already uploaded to the site's media library.)
2. Save the draft.
3. In the app, open the draft post.

Expected: The video blocks will load (or at least the video block with no caption will load).
Actual: The error “Problem displaying block” appears instead for both blocks.

![image](https://user-images.githubusercontent.com/8658164/59705639-b4094700-91f6-11e9-8a64-a5b8bd12045d.png)

Saving the post in the app and trying to open it again on the web results in an error on that end: “This block contains unexpected or invalid content.”

![image](https://user-images.githubusercontent.com/8658164/59705657-b9ff2800-91f6-11e9-864c-ddc4a00feafa.png)

I also confirmed that the same “Problem displaying block” error occurs if I add a video in the app, open the draft on the web and save it there, and then reopen the video in the app. There seems to be an issue between how Gutenberg web saves the video block markup and how Gutenberg mobile expects it to be.

Tested on iPhone XS, iOS 12.3.1, WPiOS 12.7.0.20190617

**Comment by rachelmcr** [comment] 2019-06-18 17:41
This issue occurred on a WordPress.com Simple site with the Premium plan. @pinarol let me know that there's a known issue with how the video block code is handled for sites on that plan (internal ref: pafL3P-pg-p2), which is the likely cause for both problems I saw.

**Comment by marecar3** [comment] 2019-06-27 16:40
Hi @rachelmcr,

I would split this problem into 2 parts.

1. The reason why we are showing: "Unsupported block type" is this: https://gutenpackp2.wordpress.com/2019/05/10/videopress-block-is-breaking-video-blocks-on-mobile-gutenberg/#comment-1712

@hypest is ⬆️agreement still ok for us?

2. Is that mobile is changing the content of that block which results in invalid content on the web. This one needs to be examined and I will take a look at it.

cc: @frosty

**Comment by marecar3** [comment] 2019-06-28 03:59
This issue is also reproducible on Android devices. I have found the root cause of the problem. 
It seems that mobile apps are changing the `<--wp:video... ` content.

<img width="1977" alt="Screen Shot 2019-06-27 at 5 45 52 PM" src="https://user-images.githubusercontent.com/28219092/60316091-3f8d8100-9937-11e9-914c-9df1fc922be0.png">

**Comment by marecar3** [comment] 2019-07-02 03:36
Hey @rachelmcr @frosty, just to let you know that it's a known issue and it doesn't have high priority 
https://gutenpackp2.wordpress.com/2019/05/10/videopress-block-is-breaking-video-blocks-on-mobile-gutenberg/#comment-1720

**Comment by designsimply** [comment] 2019-10-24 20:08
Re-tested and confirmed with 13.5-rc-1 that video blocks added using Calypso Gutenberg do not load in Gutenberg Mobile with error "Problem displaying block" and confirmed that the precursor block comment code is changed after viewing the post in the app—the `guid` and `src` attributes go missing. 

On the web:

```
<!-- wp:video {"guid":"Kb3sKmpL","id":54,"src":"https://aboutmakingmoviesmovie.files.wordpress.com/2019/10/59372044362__e5d32d89-e607-49a8-94b3-03ed7a014063.mov"} -->
```

In the app:

```
<!-- wp:video {"id":54,"className":"wp-block-embed is-type-video is-provider-videopress"} -->
```

<img src="https://user-images.githubusercontent.com/1119271/67521011-3e5f2d00-f667-11e9-84b0-3f8dc651934d.png" width="270" alt="Screenshot_20191024-135618"> <img src="https://user-images.githubusercontent.com/1119271/67521010-3e5f2d00-f667-11e9-8845-78d52d0019a4.png" width="270" alt="Screenshot_20191024-135628">
<sup>Tested with WPAndroid 13.5-rc-1 on Pixel 3 Android 10.</sup>

<img width="270" alt="Screen Shot 2019-10-24 at Oct 24 1 54 58 PM" src="https://user-images.githubusercontent.com/1119271/67521206-a1e95a80-f667-11e9-9335-281e25e18cce.png"> <img width="270" alt="Screen Shot 2019-10-24 at Oct 24 1 55 03 PM" src="https://user-images.githubusercontent.com/1119271/67521204-a1e95a80-f667-11e9-8baa-39065d5622bf.png">
<sup>Tested with Gutenberg Calypso on Chrome 77.0.3865.120 on macOS 10.14.6.</sup>

**Comment by kcswong** [comment] 2020-04-22 18:18
Updating to say we were contacted about this by a user in #2900144-zen

**Comment by chipsnyder** [comment] 2020-06-16 19:45
Looking into this it appears that for SimpleSites on a premium plan are creating video blocks with the following pattern:
```
<!-- wp:video {"autoplay":true,"guid":"7IeP9E0R","id":34,"loop":true,"muted":true,"src":"https://chipsnyder.files.wordpress.com/2020/06/img_0029.mov"} -->
<figure class="wp-block-video wp-block-embed is-type-video is-provider-videopress"><div class="wp-block-embed__wrapper">
https://videopress.com/v/7IeP9E0R?autoPlay=true&amp;loop=true&amp;muted=true&amp;persistVolume=false&amp;preloadContent=metadata
</div></figure>
<!-- /wp:video -->
```

Where an atomic site I'm using produces:
```
<!-- wp:video {"autoplay":true,"id":608,"loop":false,"muted":false,"playsInline":false,"src":"https://testeisbardev.wpcomstaging.com/wp-content/uploads/2020/04/60686287497__6ff2dbfc-6c7f-4ae0-8e54-992daf76849a-1.mov"} -->
<figure class="wp-block-video"><video autoplay controls src="https://testeisbardev.wpcomstaging.com/wp-content/uploads/2020/04/60686287497__6ff2dbfc-6c7f-4ae0-8e54-992daf76849a-1.mov"></video></figure>
<!-- /wp:video -->
```

I'm currently working on revisiting the block registration to handle these cases.

**Comment by chipsnyder** [comment] 2020-06-16 21:17
Describing the issue helped me better understand @marecar3 comment here:

> The reason why we are showing: "Unsupported block type" is this: pafL3P-pg-p2 #comment-1712

I'll sync up with him to see if there are any options to prevent the apps from overwriting what the web has. 

As for the issue here for people like me who may have overlooked it. This configuration results in a `jetpack/vaultpress` block instead of a `core/video` block even though the code in the editor appears the same. To add support for this type Gutenberg would need to add support for Jetpack blocks.

**Comment by chipsnyder** [comment] 2020-06-17 17:40
After discussing some options with others it looks like support for this is being tracked by https://github.com/Automattic/jetpack/issues/12358 and work is underway to better handle the case when the block fails validation https://github.com/WordPress/gutenberg/pull/15674.

The work that's being done in [the parser](https://github.com/WordPress/gutenberg/pull/15674) should help provide a better experience

**Comment by hypest** [comment] 2020-12-04 12:21
> After discussing some options with others

👋 @chipsnyder, can you expand on the options discussed, or link me to related convos? I'm thinking, now that we have the ability to separate .com from .org code, maybe we can address this by incorporating the "Jetpack" side block too.

**Comment by chipsnyder** [comment] 2020-12-04 14:34
Hey @hypest. I think there are some internal documents that capture parts of these options but I'm failing to uncover a combined explanation. 

1. Make some changes to apply the `guid` formatting to the generated block more details here: `pafL3P-pg#comment-1719`
1. Add support for `jetpack/vaultpress` 
    - This seems like the best option now that we have started added Jetpack Support in GBM
    - If memory serves me correctly this is what was decided on because at the time we hadn't added Jetpack support to GBM yet but we were working on it. 
1. Modify Jetpack to use a different [registration](https://github.com/Automattic/jetpack/blob/f3f6887770c2022adaf9af52a5f0eb147c005c40/extensions/extended-blocks/core-video/core-video.php#L25) for the block like `jetpack/vaultpress` instead of `core/video`
    - This seems like it will have a lot of rippling consequences.

**Comment by chipsnyder** [comment] 2020-12-04 14:46
Ps. There is worked started that seems to be going down the path of (3) mentioned [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1152#issuecomment-738817171) however that work seems to have stalled. Here is the PR and Issue I'm referring to:

- https://github.com/Automattic/jetpack/issues/12358
- https://github.com/WordPress/gutenberg/pull/15674

**Comment by hypest** [comment] 2021-03-18 12:47
I wonder, now that we have the Unsupported Block Editor in place, perhaps we could enable it for the video block by somehow detecting the situation with the Calypso treatment of the video block? Pinging @guarani in case you have some thoughts on this since you've worked on the UBE in the past.

**Comment by guarani** [comment] 2021-03-19 01:15
> I wonder, now that we have the Unsupported Block Editor in place, perhaps we could enable it for the video block by somehow detecting the situation with the Calypso treatment of the video block? Pinging @guarani in case you have some thoughts on this since you've worked on the UBE in the past.

I did a quick test and was able to reproduce this issue. Looking at the UBE, it might work to allow users to edit these video blocks that have been edited on the web, but unless we also update the UI to assure users that the Video block is not "unsupported", this could lead to user confusion. So as-is, the UBE doesn't feel like a drop-in temporary solution, unless we modify it for this use case.

Is the alternative to add support for `jetpack/vaultpress` block?

**Comment by hypest** [comment] 2021-03-19 11:51
> Is the alternative to add support for jetpack/vaultpress block?

AFAIK, Jetpack isn't actually registrering a new block type, it's just overrides the `core/video` one. In those terms, we'd need to add support for the Jetpack Gutenberg extension and see how to to wrangle the whole flow (detecting when to use which version when adding a new block too). We could explore that but sounds messy.

That said, the judging from the movements in https://github.com/Automattic/jetpack/issues/12358, looks like that ticket is now in a prioritized list (at the time I'm writing this comment anyway) so, perhaps work on revising that Jetpack implementation will resume soon.

**Comment by thabotswana** [comment] 2022-07-16 09:51
We have a user reporting this issue here: 5375141-zen

* They can add their video to their media library, then insert it into a post, but they can't upload directly from the editor.
* We have been able to reproduce this by uploading a video to a Simple site.

**Comment by SiobhyB** [comment] 2024-02-13 16:49
This was resolved in https://github.com/Automattic/jetpack/pull/24548 and will be further improved with some upcoming work on the Video block.

**Closed by SiobhyB** 2024-02-13 16:49 UTC
Labels: [Type] Bug, [OS] iOS, [OS] Android, Video block
