### ISSUE TITLE
Scrolling glitch when splitting a long paragraph

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#463] opened 2019-01-03 14:11 UTC
There is a small scrolling glitch when splitting a long paragraph content on enter. It looks like it scrolls to the top of the block first and then down to the new block.

Note: It doesn't happen always, it is an intermittent issue, couldn't find the root cause yet

![50632271-fcd28980-0f4f-11e9-949f-67fcfde7d5d1](https://user-images.githubusercontent.com/5032900/50641954-bcd4cc00-0f7a-11e9-8c8c-59198748efc2.gif)

**Comment by pinarol** [comment] 2019-01-17 09:30
This also looks like the same issue, we need to address this one too https://github.com/wordpress-mobile/gutenberg-mobile/pull/474#pullrequestreview-193307699

**Comment by pinarol** [comment] 2019-02-11 08:26
I have opened a separate issue for the case of appending next text at the end of a long paragraph because that has a different root cause https://github.com/wordpress-mobile/gutenberg-mobile/issues/583

**Comment by pinarol** [comment] 2019-02-12 16:27
Most of the annoying issues are solved within https://github.com/wordpress-mobile/gutenberg-mobile/pull/554

But still there are some small glitching issues left on merge/split, but they are originating from RN layer. I'll describe the root cause below, and I am planning to open an issue to RN repo, I am also planning to open a PR to there because what I want is just a flag to turn off the automatic scroll adjustments they are making, so it'd be simple but there's a possibility of reject ofc. But even so, I am hoping we might have useful feedbacks.

So here's what happens: whenever content size changes scroll offset is also **sometimes** adjusted accordingly (only under some conditions, see RCTScrollView's calculateOffsetForContentSize:(CGSize)newContentSize to see exactly what conditions, long paragraphs don't have it always) If we could just delete the call for calculateOffsetForContentSize then everything could have worked perfectly(I tried and it worked perfectly). But, currently there's no way to do it, so I think it'd be good to request a ticket from RN folks to be able to turn it off. They put a comment explaining why they are calling this method and it looks like was a workaround in the first place:

>    // When contentSize is set manually, ScrollView internals will reset
>    // contentOffset to  {0, 0}. Since we potentially set contentSize whenever
>    // anything in the ScrollView updates, we workaround this issue by manually
>    // adjusting contentOffset whenever this happens

maybe this was needed in old iOS versions? not sure, but with iOS 12 it looks like we don't need that workaround imho. At least my tests were ok when I remove that call.

BTW I tried to make lots of other workarounds but had no chance. Any idea is welcomed.

I should underline this, the problem with merging and splitting blocks is not related with the length of the block's content, sometimes long blocks split/merge pretty good, other times short blocks can have glitch. It is more related with the logic inside calculateOffsetForContentSize.

**Comment by etoledom** [comment] 2019-02-13 08:01
> Since the unsolved issues aren't that annoying, we can use some time to report this and see their response, and solve this after the beta.

I agree with that!

While I was testing the PR, I could reproduce this issue but it didn't happen too often and it wasn't too annoying comparing with the one that was solved.

Hopefully we can get some support from Facebook 👍

**Comment by pinarol** [comment] 2019-02-14 13:46
Opened the issue https://github.com/facebook/react-native/issues/23450

**Comment by koke** [comment] 2019-02-14 13:55
Sorry I somehow missed your ping, but it sounds like a good plan

**Comment by hypest** [comment] 2019-03-14 15:39
👋 @pinarol , using a more recent React Native version is [just around the corner so](https://github.com/wordpress-mobile/gutenberg-mobile/pull/741), you might want to use it to update the bug report.

**Comment by pinarol** [comment] 2019-03-15 07:36
@hypest exactly! I was thinking the same thing, thanks! 👍

**Comment by pinarol** [comment] 2019-03-18 16:16
I had to open a new issue since previous was automatically closed: react-native/issues/24011
Looks like issues that are not updated with latest RN version for a while are being closed by the bot.

**Comment by koke** [comment] 2019-04-04 21:58
I've been testing around and couldn't reproduce so I assume the glitch is somewhat rare. I'm moving this to the Future column since, from what I understand, we're waiting for an answer from upstream, but let's revisit the priority when we hear back from them.

**Comment by maxme** [comment] 2020-07-15 09:42
I can't reproduce that one, it was maybe fixed by a RN update. Closing it until we get another report.

**Closed by maxme** 2020-07-15 09:42 UTC
Labels: Writing Flow, [OS] iOS, [Pri] Low, [Type] Enhancement
