### ISSUE TITLE
[GlobalStep] “Start writing...” text disappears when Align Right is selected

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#1917] opened 2020-02-14 15:46 UTC
### Description
When typing into a Paragraph Block, selecting the Align Right setting causes the “Start writing...” and the cursor to disappear and the Paragraph Block to appear slightly shorter.

### Reproduction Rate
4/4 100%

### Expected behavior
The “Start writing…” text and the cursor should remain visible and the block should remain the same size regardless of the text alignment.

### Actual behavior
The “Start writing...” text disappears along the cursor while the block becomes slightly shorter.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Press “Add new”.
4. Tap the “Start writing...” block.
5. Select the “Align Right” setting.
##### Tested on the following
iPhone SE (12.0.1)

#### Please see the attached video for more information
[iOSAlignRightCursor.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4205194/iOSAlignRightCursor.zip)

### Submitted by:
Luis Pimenta

**Comment by mchowning** [comment] 2020-05-05 21:02
I was not able to reproduce this on a physical iPhone Xr (iOS 13.3.1), but **I was able to reproduce the issue on an iPhone SE Simulator (iOS 12.4)**.

**Comment by hypest** [comment] 2021-06-24 11:33
Closing as I can't replicate on an iPhone 12 simulator, iOS 14.4, demo app on develop 9bf53198. Similar with the Android demo app, can't replicate on a physical Pixel 2 XL. Please, feel free to reopen if issue still persists. Thanks!

**Closed by hypest** 2021-06-24 11:33 UTC
Labels: HACK week, [OS] iOS, [Pri] Medium, [Status] Needs iOS Dev, [Type] Bug
