### ISSUE TITLE
Make sure an empty draft can't be published

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#369] opened 2018-12-13 08:20 UTC
As reported by @rachelmcr:

---

I’m able to save a completely empty post (no title or content). That shouldn’t be possible. To reproduce:

1. Start a new Gutenberg post.
2. Tap into the post content area. This makes a new paragraph block appear.
3. Tap the ellipsis menu and select “Save as Draft.”

You can also try to publish an empty post, although it fails. The “Publish” button shouldn’t be enabled in that case:

1. Start a new Gutenberg post. (You don’t have to enter any content or tap anywhere in the post title or content area.)
2. Tap the Publish button.

---

I'm adding this one for the alpha assuming it's a quick fix, since Aztec already behaves that way.

**Comment by hypest** [comment] 2018-12-13 09:55
> Tap into the post content area. This makes a new paragraph block appear.

Hmm, interesting. We'll need to figure out a way to mask out the change introduced by the empty GB paragraph block. The block does sport the GB delimiters and an empty `<p></p>` set. I'm not too confident this can be done in the Alpha. Can we bump it to the Beta perhaps?

**Comment by daniloercoli** [comment] 2018-12-14 13:31
> I'd still like to address the second part if it's a quick fix.

Are you sure that Aztec already behaves that way?

I just tried to publish and empty post with Aztec on Android, and the `Publish` button is available on the screen. Once I tapped on it, the "Publish now" dialog appeared, and if I confirm to publish the post the error toast `can't publish an empty post` was there.

**Comment by koke** [comment] 2018-12-14 15:18
Interesting, it does on iOS. Let's do it on iOS for the Alpha, since I imagine it'd be easy, and consider the Android part for the beta

**Comment by etoledom** [comment] 2018-12-17 07:41
The problem is that we need to send a signal from JS to Native for every time the post content changes. In that way our `GutenbergViewController` will know if the content is empty or not to enable/disable the publish button at any given time.

This means that we will need to serialize to HTML on every key stroke or action that modifies the content. Probably we will have to do something of the sort at some point anyway.

I can give it a look to be sure about the difficulties, but I believe it is not an easy/quick fix.

**Comment by koke** [comment] 2018-12-17 15:11
OK, thanks for the explanation, let's move it to the Beta then

**Comment by koke** [comment] 2019-01-16 14:50
This is actually two separate issues. For the beta let's at least figure out what's not working correctly and re-evaluate.

**Comment by hypest** [comment] 2020-06-09 16:15
Verified the issue still happening on WPiOS 15.0.

On WPAndroid (alpha-228) the empty post is not saved as a draft when you exit the editor (by pressing "Back"), and hitting "Publish" shows a Toast with "Can't publish an empty post", both of which are not an issue.

I will change this ticket to "iOS" only, mark is as "Writing flow" and assign it to the Releases&Maintenance squad.

**Closed** 2020-06-26 14:42 UTC
Labels: App Integration, Writing Flow, [OS] iOS, [Status] Needs Research
