### ISSUE TITLE
Can't hide the keyboard when on Quote block (iOS)

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1103] opened 2019-06-07 20:53 UTC
Note: I'm running a custom version of WPiOS, built off of `develop` (iOS 12.4, iPhone Xs Max). I haven't tried a build w/ Quote on Android yet.

## Steps to reproduce

* Select a Quote block
* Tap `hide-keyboard` button on Quick Toolbar

## Expected Behavior

Keyboard should hide as it does on all other blocks (where keyboard is shown on focus).

Related to: #952

**Comment by iamthomasbishop** [comment] 2019-06-07 20:54
After submitting this, I realized that it seems to work _some_ of the time but feels very random.

**Comment by etoledom** [comment] 2019-06-11 08:17
I'm not able to reproduce this testing https://github.com/wordpress-mobile/WordPress-iOS/pull/11885

Are specific steps needed? It might have been solved.

**Comment by iamthomasbishop** [comment] 2019-06-11 20:26
I'm unable to test at the moment, but if others are also unable to reproduce, then perhaps it has been fixed. I will check it out when I'm able to get the new release.

**Comment by hypest** [comment] 2019-07-01 12:05
Tried the gutenberg-mobile demo app on an iPhone X 12.2 simulator and _am_ able to hide the virtual keyboard by hitting the `hide-keyboard` button on Quick Toolbar. Able both in the Quote main body and the citation section.

Will close this but, please feel free to reopen if still happening.

**Closed by hypest** 2019-07-01 12:05 UTC
Labels: bug

**Comment by iamthomasbishop** [comment] 2019-07-01 13:34
Can confirm this is working for me as of the last release. Thanks for checking!
