### ISSUE TITLE
Post preview displays stale content

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#2207] opened 2020-05-01 04:48 UTC
**Describe the bug**

The post preview does not always relfect the latest state of the content. This issue was encountered [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/14002#issuecomment-620486147). In the screencast below, the preview content displayed is "stale" for button block inside a group, however, I have also reproduced the behavior with only paragraph blocks.

<details>
<summary>Screencast - Preview doesn't show new content after button inside group</summary>

<img src="https://user-images.githubusercontent.com/8507675/80556878-6bc2d400-8a18-11ea-9bcc-01e0718a2962.gif" width="360">
</details>

**To Reproduce**

1. Add a new post
2. Repeat the following 3 times:
   1. Add a paragraph with some text
   2. View preview (obvserve the new paragraph is display in the preview)
   3. Switch back to editing

On the third edit, I observed that the preview content was "stale".

**Expected behavior**
The post preview should display the most up-to-date post content.

**Smartphone:**
 - Device: iPhone 11
 - OS: iOS 13.3.1

**Additional context**
It may be worth investigating whether `provideToNative_Html` sends the correct value for `hasChanges`.

**Comment by guarani** [comment] 2021-03-08 20:22
I notice you're assigned here @mkevins, but I just gave this a test and was unable to reproduce on iOS. It looks like this was an iOS-only issue (based on the labels), but wanted to check if you think this can be closed or needs more investigation?

**Comment by mkevins** [comment] 2021-03-10 22:14
> I notice you're assigned here @mkevins, but I just gave this a test and was unable to reproduce on iOS. It looks like this was an iOS-only issue (based on the labels), but wanted to check if you think this can be closed or needs more investigation?

I test as well, and it seems to have been resolved! Thanks for the ping! Closing.

**Comment by guarani** [comment] 2021-03-11 13:29
Thanks @mkevins!

**Comment by osullivanchris** [comment] 2021-04-28 12:29
I am having the same issue as @mkevins 

- on WP Android v17.2
- Pixel 3a
- Android v11

If I publish the post, it publishes with the correct content. But previewing doesn't show updated content. Even when I make sure its saved.

Edit: also noting this is happening for a test Pressable site that I have. Doesn't seem to be happening on my WP.com sites.

**Comment by geriux** [comment] 2024-01-12 11:41
This is no longer reproducible in the `24.0` version of the Jetpack iOS app, quite a few changes have been done to the Post/Pages functionality so it looks like some of those fixed this 🎉 

Closing the ticket.

**Closed by geriux** 2024-01-12 11:41 UTC
Labels: [Type] Bug, [Status] Needs iOS Dev, [OS] iOS, [Pri] High, HACK week
