### ISSUE TITLE
Android: Title and Inserter do not honor system language when set to Hebrew

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/gutenberg-mobile#4368] opened 2021-12-10 22:30 UTC
**Describe the bug**
The title text (e.g. "Add title") and block names in the Inserter (e.g. "Heading", "Paragraph") are not translated when the OS is set to use Hebrew and the app's language setting is kept at the default.

**To Reproduce**
1. Set Android's language to Hebrew [[instructions](https://support.google.com/accounts/answer/32047?hl=en&co=GENIE.Platform%3DAndroid)]
2. Clean install WordPress for Android
3. Start a new Post and observe the "Add title" text
4. Open the Block Inserter and observe the block names

**Expected behavior**
The app displays labels in Hebrew for the title and Inserter's block names. The portions of the app outside of the editor also reflect this setting.

**Actual behavior**
The portions of the app outside of the editor reflect this setting only.

**Screenshots**
<div>
<img src="https://user-images.githubusercontent.com/2092798/145648787-82420b18-1640-4c1d-8182-a6b6ca5ece95.png" width="250px" alt="Screenshot of the inserter not being translated" />
</div>

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11
 - Version 18.8-rc-2

**Additional context**
Setting the language to Hebrew from within the app settings (Me -> App Settings -> Interface Language) works correctly. It should be noted that it overrides the system setting. This may affect other languages (maybe just RTL), so those should be tested as well.

**Comment by hypest** [comment] 2021-12-17 11:11
👋 @mchowning ! I assigned this ticket to you since I think you have started looking into it but, we can reassign if needed. Thanks!

**Comment by mchowning** [comment] 2021-12-17 18:28
Confirmed this issue exists in 18.8, 18.0, and 17.0 (I didn't go back any further). So this is not a recent regression (and I suspect it probably never worked).

**Comment by mchowning** [comment] 2021-12-17 22:13
I don't have a fix implementation yet, but I've isolated the issue. 

Android/Java [uses some old locale codes instead of the new ones](https://developer.android.com/reference/java/util/Locale#legacy-language-codes) in order to avoid breaking backward compatibility (giving us "forward incompatibility" :trollface:  ). One of these languages is Hebrew, where Java uses "iw", even though that [has been superseded by "he"](http://www.loc.gov/standards/iso639-2/php/code_list.php). 

When providing the locale to Gutenberg, WPAndroid [checks if we've set a locale within the app](https://github.com/wordpress-mobile/WordPress-Android/blob/4585d19679b9f651d39dfd3372de544a093b221c/WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java#L103). If we have, then we send that. If we haven't, we send the device locale `Locale.getDefault()`, and Locale [uses the old "iw" code for hebrew instead of the new "he" code](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/trunk/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java#L27). Gutenberg, however, only generates translations for the new "he" locale, not the old "iw" locale.

![image](https://user-images.githubusercontent.com/4656348/146612904-c5d0d050-e2ad-4871-9ce7-70f5391bb260.png)

This explains why the issue does not occur when we set the locale from within the app. The app specifies "he" as the available "Hebrew" locale when the user selects that language [within the app](https://github.com/wordpress-mobile/WordPress-Android/blob/61e09f8e97bd863c90eff82f0ca274fdfd012d2b/WordPress/src/main/res/values/available_languages.xml#L12). When we default to the device locale, however, then Android tells us the Hebrew locale is "iw".

WPAndroid probably doesn't have this problem outside of Gutenberg because of how Java [automatically converts any "he" locales to "iw"](https://developer.android.com/reference/java/util/Locale#legacy-language-codes). I think we just need to make a similar "fix" for Gutenberg.

In light of this, I can pretty easily fix the problem by modifying the locale with something like `locale.replace(/iw(-.*)/, 'he$1')` before the locale gets used within Gutenberg. I need to figure out where is the best place to do that conversion. My thinking is that the conversion should happen on the Gutenberg side since this is the standard Android behavior--that way this fix would get picked up by any other app that uses Gutenberg. With that said, the fix does not have to happen in javascript, it could be applied within Gutenberg's native Android code.

cc: @fluiddot and @jhnstn  since you two are also doing some unrelated translations work right now

I'm AFK on Monday, but I'll plan to pick this back up on Tuesday.

#### TODO
- [ ] Find the best place to apply the conversion fix
- [x] Check if we have a similar problem with the `yi -> ji` and `id -> in` mappings that [Android also does](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/trunk/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java#L27).

**Comment by mchowning** [comment] 2021-12-21 16:51
> Check if we have a similar problem with the `yi -> ji` and `id -> in` mappings that [Android also does](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/trunk/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java#L27). 

Confirmed that the same issue exists with the Indonesian `id -> in` mapping. 

I do not see any Gutenberg translations for `yi` showing up in the i18n-cache (`packages/react-native-editor/i18n-cache/data`) after generating the translation strings, so there isn't an issue (currently) with the Yiddish `yi -> ji` mapping that Java does. That would change if GUtenberg ever adds Yiddish translations under `yi` though.

**Closed as completed** 2022-01-14 19:39 UTC
Labels: [OS] Android, RTL
