### ISSUE TITLE
[GlobalStep] [iOS] Brief lag is observed upon adding more than 1 image in "Cover" from "Free photo library" option

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2254] opened 2020-05-07 16:57 UTC
**Environment:**
iPad Air 2(v13.3.1), iPhone 11 Pro (v13.3.1).
 
**Steps To Reproduce:**
 1. Install and launch the application.
 2. log in with valid credentials.
 3. Tap on "My Site" tab.
 4. Tap on "Post" and Add new Post.
 5. Tap on "+" icon available on left side corner . 
 6. Add "Cover".
 7. Tap on "Add Image or Video".
 8. Select option "Free Photo Library"
 9. Search image and select more than 1 images and add to cover.
10. Observe the lag while loading the images on "Post site" page .
  
**Actual Result:**
Brief lag is observed upon adding more than 1 image in "Cover" from "Free photo library" option
 
**Expected Result:**
 User should able to add more that 1 images in the Cover and page smoothly.

[#14075.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4594520/14075.zip)

**Comment by designsimply** [comment] 2020-05-13 02:38
Tested and confirmed that there is a delay when uploading multiple images to the Cover block using the Free Photo Library upload option, and it appears that's because each image is loaded one at a time and each one may take some time to upload before it is inserted into the content area. ([4m5s](https://cloudup.com/cFXEWAZuaaV))

It's much more prominent on a slow connection.  It also makes the keyboard pop up and down as the focus for each block changes. 

@mkevins would it be possible to smooth that out so multiple blocks are added in more smoothly?

I checked the other upload options (Choose from device, Take a Photo, Take a Video, WordPress Media Library, and Other Apps) and none of them gave the option to select more than one image at a time when adding media to the Cover block, so we should consider whether to keep multi-select as an option for that block. It's worth mentioning that it's really nice to be able to select multiple images and have multiple blocks get added and I recall that has been requested in the past by users for both the image and gallery blocks when selecting images from other upload options as well.

The focus loop making the blocks "jump" was reported earlier in https://github.com/wordpress-mobile/gutenberg-mobile/issues/953 and I added a comment mentioning this issue because it was a lot more prominent in my test where the keyboard was also affected as it opened and closed repeatedly with each focus change until either the app froze or the images finished uploading and I could close and re-open the post. Note: my test was made with 14.8.0.1 and the original report here was made with 14.8.0.0.

**Comment by mkevins** [comment] 2020-05-13 09:29
Hi @designsimply :wave: :smile: 
> I checked the other upload options (Choose from device, Take a Photo, Take a Video, WordPress Media Library, and Other Apps) and none of them gave the option to select more than one image at a time when adding media to the Cover block, so we should consider whether to keep multi-select as an option for that block

I think the best approach would be to make the selection singular for Cover block, since I believe that is the intended behavior.

Thanks for linking to the focus loop bug, and giving context there. It seems that the RichText / Paragraph block has exhibited this bug for a long time, and this Cover block bug is another way that it can manifest. I also observed the keyboard (and block toolbar) behaving erratically after adding multiple images from the free photo library, which is not a nice UX. I'll prioritize a fix for this.

**Comment by pinarol** [comment] 2020-05-13 13:31
> I think the best approach would be to make the selection singular for Cover block, since I believe that is the intended behavior.

@mkevins It turns out the challenging part is we don't have a mechanism to define different behavior for Image, Cover, Media-Text about multiSelect, they are all multiSelect=false, if we set it to true this time they'll try to handle an array of uploaded images like Gallery and they'll fail. And the mechanism that creates new blocks for the rest of the images will never kick in.

So, if multiple uploads doesn't generate problem on Android we might allow for rest of the uploads appear as image blocks as well. On iOS, we limited the ability to multi select for all these blocks since we have a focus loop currently.

Opened [an issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2255) to discuss this widely.

**Comment by designsimply** [comment] 2020-05-14 02:15
This problem should be solved by https://github.com/wordpress-mobile/WordPress-iOS/pull/14108 because there will not be the option to multi-select media from the Cover block. Props @dratwas. 🎉

**Closed by designsimply** 2020-05-14 02:15 UTC
Labels: Beta Request, Blocks, [Type] Bug

**Comment by mkevins** [comment] 2020-05-14 06:05
Hi @pinarol :wave: :smile: 

> (This can be confusing because we do allow for multi select even if we have multiSelect=false, that's because we simply ignore that flag on main apps.)

In Android, we introduced _another_ flag called [`mAppendsMultipleSelectedToSiblingBlocks`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/6d7a9952ea964eb9d3eb79f41463e2465fba6585/react-native-gutenberg-bridge/android/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java#L72) to specify the intention to ignore the `allowMultipleSelection` flag, but this has only ever been for _already uploaded_ WordPress Media Library images.

> So, if multiple uploads doesn't generate problem on Android we might allow for rest of the uploads appearing as image blocks as well. On iOS, [we limited the ability to multi select](https://github.com/wordpress-mobile/WordPress-iOS/pull/14108) for all these blocks since we have a focus loop currently.
> 
> Opened [an issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2255) to discuss this widely.

Multiple uploads appending multiple Image blocks has not been implemented yet on Android. Also, for Cover block, the Free Photos Library flow has a similar bug (allowing multiple selection) which results in a different problem (descibed here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2261).

I've opened [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/11912) on WordPress-Android to fix the issue there.

**Comment by pinarol** [comment] 2020-05-14 15:47
Cool thanks @mkevins !
