### ISSUE TITLE
[GlobalStep] Android – Adding or editing Site Pages / Blog Posts with the Block Editor enabled causes a crash to occur on the Samsung Galaxy S7

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#1839] opened 2020-01-30 10:20 UTC
### Description
Adding or editing Site Pages / Blog Posts when the Block Editor is enabled causes a crash to occur on Samsung Galaxy S7 devices. The issue was seen to occur on different firmware versions on different Samsung Galaxy S7 devices.

The issue was also tested on the Samsung Galaxy S6 (7.0) and the Samsung Galaxy Note 4 (6.0.1) but the crash didn’t occur on these devices.

### Reproduction Rate
4/4 100%

### Expected behavior
The Block Editor should work on Samsung Galaxy S7 devices.

### Actual behavior
Using the Block Editor in Samsung Galaxy S7 devices causes a crash to occur.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Enable the Block Editor.
4. Press the “Add new” button.
5. Select the Site Pages / Blog Posts option.
6. Type anything.
##### Tested on the following
Samsung Galaxy S7 (7.0)
Samsung Galaxy S7 (6.0.1)

#### Please see the attached video and log for more information
[AndroidS7BlockEditorCrash.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4133474/AndroidS7BlockEditorCrash.zip)
[AndroidS7BlockEditorCrash.txt](https://github.com/wordpress-mobile/gutenberg-mobile/files/4133475/AndroidS7BlockEditorCrash.txt)

### Submitted by:
Luis Pimenta

**Comment by hypest** [comment] 2020-06-11 10:47
Cannot reproduce on a Galaxy S7 Edge (Android 8.0), WPAndroid v14.1. I know it's not the very same device and Android version as the ones reported in the ticket but, the Android versions mentioned (7.0, 6.0.1) are already old enough, even for the mentioned devices and there's no specific error reported to look for on Sentry.

Will close this ticket as "non reproducible" but feel free to open if we find more context or occurrences of this.

**Closed by hypest** 2020-06-11 10:47 UTC
Labels: [Type] Crash
