### ISSUE TITLE
Synced pattern name and controls are not visible on dark background

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/gutenberg-mobile#6224] opened 2023-09-22 19:26 UTC
**Describe the bug**

Synced pattern name and control are not visible on dark background.

**To Reproduce**

Follow https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/synced-patterns.md#tc001

**Screenshots**

![Screenshot 2023-09-22 at 3 24 04 PM](https://github.com/wordpress-mobile/gutenberg-mobile/assets/1567433/b1d63256-493b-4ad9-9b3d-14cdcf7bfc01)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.0.1
 - Version 23.3.0.1

**Comment by dcalhoun** [comment] 2023-09-23 17:15
Closing as a duplicate of https://github.com/WordPress/gutenberg/issues/37203. Feel free to re-open if inaccurate.

**Closed as completed by dcalhoun** 2023-09-23 17:15 UTC
Labels: [Type] Bug
