### ISSUE TITLE
 [GlobalStep] [iOS] Unable to operate or handle all tags in HTML mode.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2298] opened 2020-05-21 15:16 UTC
**Environment:**
 iOS: iPhone 8 (v13.4.1), iPhone 11 Pro (v13.2.2), iPhone XS (v13.2.2).
Build [version]: v14.9

**Steps To Reproduce:**
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Tap on "Create a new Post" symbol.
 5. Enter any text at title.
 6. Tap on (More)three dots symbol at top right side.
 7. Now tap on Switch to HTML mode.
 8. Enter any tag except paragraph.
 9. Observe that user is not able to add other tags apart from Paragraph.

Note: Paragraph tag "<p>" gets automatically added when we enter text in HTML view.

**Actual Result:**
Unable to operate or handle all tags in HTML mode.

**Expected Result:**
User should be able to operate smoothly in HTML mode.

**Attachment:**
[#2298.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663225/2298.zip)

**Comment by designsimply** [comment] 2020-05-22 21:08
Duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2292.

No need to report iOS and Android issue separately in the `gutenberg-mobile` repo unless the behavior is significantly different or noteworthy. Thank you!

**Closed by designsimply** 2020-05-22 21:08 UTC
Labels: Beta Request, Writing Flow, [Status] Duplicate, [Type] Bug
