### ISSUE TITLE
Image Block: add a "Link To" option to easily link media to a larger or original version of the image

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#924] opened 2019-04-23 17:52 UTC
I expected to be able to easily link an image to the original image.

Steps to reproduce:

1. Add an image block and add an image to it.
1. Tap the gear icon at the bottom right of the image block.
1. Tap the "Link To" field.
1. Add a link to the Media File or Attachment page.

**Result:** there is not an easy way to link an image to the image file.

<img src="https://user-images.githubusercontent.com/1119271/56603666-6341ed00-65bd-11e9-9193-a842386608bd.PNG" width="270" alt="IMG_2611"> <img src="https://user-images.githubusercontent.com/1119271/56603762-984e3f80-65bd-11e9-9e48-60a6cc6204c5.png" width="270" alt="Screenshot_20190423-113856">

<p style="clear:both;"><sub>Tested with WPiOS 12.1.3 on iPhone 6S iOS 12.2 and WPAndroid alpha-166 (12.3 alpha) on Pixel 3 Android 9.</sub></p>

In comparison, the WordPress editor has Image Block > Link Settings > Link To options for: None, Media File, Attachment Page, or Custom URL.

<img src="https://user-images.githubusercontent.com/1119271/56603395-eca4ef80-65bc-11e9-9339-6f79985fff74.png" alt="Screen Shot 2019-04-23 at 11 34 10 AM">

Semi-related / also see: https://github.com/wordpress-mobile/gutenberg-mobile/issues/680.

<p style="clear:both;"><sub>(internal reference: p4a5px-2od-p2 cc @charliescheer)</sub></p>

**Comment by mattmiklic** [comment] 2019-06-14 15:16
I was going to pick this up for design groundskeeping, but discovered that @iamthomasbishop already has an initial design for this. Going to move it out of the groundskeeping project and assign it to him since he's already got an idea of how to approach this.

**Comment by iamthomasbishop** [comment] 2019-06-17 17:53
Roughly sketched down what's in my brain, while I have a minute. This is very much a work-in-progress, but using this as a starting point:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/1200432/59624368-3234f300-90fc-11e9-800f-477630cfcf08.png">

The example above relies on a sub-page interaction, which we'd need to build for. This could be tricky but I think is going to become necessary as we add more advanced block settings. // cc @etoledom how realistic do you think this nested structure would be at this point? I know early on we explored a couple of approaches and landed on using the most simple implementation – I think this simple approach is starting to restrict our scaling.

Another option would be to go straight into a dialog like this (or a full-screen dialog, which might scale better):

<img width="916" alt="image" src="https://user-images.githubusercontent.com/1200432/59625274-817c2300-90fe-11e9-99e8-cd4a7059f8d9.png">

**Comment by hypest** [comment] 2020-12-21 09:13
Implemented with https://github.com/wordpress-mobile/gutenberg-mobile/pull/2841

**Comment by eduardozulian** [comment] 2021-06-29 21:50
@hypest is it possible to check if we had a regression here? This was [mentioned at least in the iOS forums](https://ios.forums.wordpress.org/topic/image-block-linking-to-media-file?replies=1).

The "Link To" field now shows only **Search or type URL**. Once tapped, I can only see a field to type my search for a custom URL. Here's an example from iOS:

<img src="https://user-images.githubusercontent.com/1136160/123871857-a240fb00-d90a-11eb-9d83-c1dd6c4954b5.jpeg" width="500"/>

Tested on two WP.com sites with:

* Android 10 with WP 17.3
* iOS 14.4 with WP 17.6 and 17.7

**Comment by hypest** [comment] 2021-06-30 13:01
👋 @mkevins , since you worked on the implementation, would you mind checking the report @eduardozulian brought up [above](https://github.com/wordpress-mobile/gutenberg-mobile/issues/924#issuecomment-870942491)? And oh, was the feature only implemented in Android perhaps, and it's not available yet on iOS?

**Comment by eduardozulian** [comment] 2021-06-30 15:13
@hypest I also tested on Android and I don't see the above options as well, only the same "Search or type URL" field.

**Comment by mkevins** [comment] 2021-07-01 01:35
I believe this issue may have been closed erroneously. The link picker integrated in #2841 adds the ability to link to existing content for image blocks, but does _not_ address the requirements of this issue. The desired behavior described in this issue had not previously existed for image blocks, and so is not a regression — perhaps the design mockups were confused for screenshots? Or it may be possible that the confusion is arising from the fact that the Gallery block _does_ have the "link to" options described above.

There is also a related (and maybe somewhat overlapping) issue here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1655

**Closed** 2021-11-03 11:56 UTC
Labels: [Type] Enhancement, Mobile Request
