### ISSUE TITLE
Autofill URLs aren't updated if a new URL is copied

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#3056] opened 2021-01-26 22:11 UTC
**Describe the bug**
Selecting new text does not update the autofill for links

**To Reproduce**
1. Go to a new post or page 
2. Type some text 
3. Leave the app to copy a URL
4. Highlight some text and open the link picker. 
5. Notice the URL has been auto-populated
6. Leave the app to copy a different URL
7. Highlight some new text and open the link picker. 
8. Notice the **OLD** URL has been auto-populated
9. Copy a non URL text
10. Highlight some new text and open the link picker. 
11. Notice the **OLD** URL has been auto-populated

**Expected behavior**
The auto-populated URL should reflect what is currently in the clipboard. 

**Smartphone (please complete the following information):**

iOS:
 - Device: iPhone 11
 - OS: iOS 13.5.1
 - Tested in WP iOS 16.5

Android:
 - Device: Pixel 3a
 - OS:  Android X
 - Version: 29
 - Tested in WP Android 16.5

**Comment by fluiddot** [comment] 2021-01-29 11:57
👋 @chipsnyder I see this issue is assigned to `1.46` milestone, since we're cutting the release I'll bump this to `1.47`. Please let me know if you think it needs to be included in this release, thanks!.

**Comment by geriux** [comment] 2021-01-29 12:09
Hey @chipsnyder 👋 

I'm not sure if I'm following the steps correctly but I'm unable to reproduce this issue, I tried with both iOS and Android versions on production.

https://user-images.githubusercontent.com/4885740/106272866-06fc0a80-6232-11eb-90e3-995f7cc6eb8c.mov

(The video I recorded it using the iOS simulator)

Can you please let me know what am I missing? Thanks!

**Comment by chipsnyder** [comment] 2021-01-29 13:23
Hey @geriux I see the difference I should have called out that these steps need to be done in the same block. 

https://user-images.githubusercontent.com/3384451/106279846-16b42880-620b-11eb-8438-6a4467b299db.mov

**Comment by geriux** [comment] 2021-01-29 13:31
> Hey @geriux I see the difference I should have called out that these steps need to be done in the same block.
> 
>  Untitled.mov

My bad 😅 I'll check it out, thanks!

**Closed as completed** 2021-02-01 18:03 UTC
Labels: [Type] Bug

**Comment by fluiddot** [comment] 2021-02-15 15:24
👋 I'm moving this to `1.46.1` milestone because it's going to be included in the beta fix.

Long story short, a PR was merged into the WordPress Android app after the `1.46.0` release was cut and due to the `gutenberg-mobile` submodule update these changes were included too.

Let me know if there's any concern about including in the beta fix, thanks!
