### ISSUE TITLE
[GlobalStep] [iOS] Keyboard malfunctions upon clearing Button Link URL field under button options and tapping on Link rel.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2230] opened 2020-05-06 17:11 UTC
**Environment:**
iPhone 6(v12.4.4)

**Reproduction Rate:** 
4/4 100%
 
**Steps To Reproduce:**
1. Install and open the application.
2. log in with valid credentials.
3. Make sure you have copied any link.
4. Add a button and tap on button settings.
5. Paste the Link in "Button Link URL" field.
6. Now clear the "Button Link URL" field.
7. Tap on "Button Link URL" and "Link Rel" fields multiple times.
6. Observe that Button settings mini menu keeps jittering and keyboard gets ON-OFF
 continuously. 

**Actual Result:**
Keyboard malfunctions upon clearing Button Link URL field under button options and tapping on Link rel.
 
**Expected Result:**
User should be able to navigate smoothly through the button options.

[#2230.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4588307/2230.zip)

**Comment by designsimply** [comment] 2020-05-14 01:29
I tried testing this on my Pixel 3 device, and I was unable to reproduce the keyboard focus loop problem in the buttons block bottomsheet as described. ([34s](https://cloudup.com/cBUNxaBBoIi))

<p style="clear:both;"><sup>Tested with WPiOS 14.8.0.2 TestFlight beta on iPhone 6S iOS 13.3.1 with a Jetpack site (shown in video) and also on iPhone 11 iOS 13.4.1 with a WordPress.com site.</sup></p>

@pinarol I noticed you reported a different focus loop problem in https://github.com/wordpress-mobile/gutenberg-mobile/issues/953 a while back and I was wondering if you might be able to help test this case since I've tried testing with two different devices and haven't been able to replicate it so far. I would also like to ask you if you can think of anything I might be missing in my testing steps?

**Comment by pinarol** [comment] 2020-05-14 15:02
@designsimply  I see a Google suggestions bar in the video, it might be effecting:

<img width="435" alt="Screen Shot 2020-05-14 at 17 58 54" src="https://user-images.githubusercontent.com/5032900/81950597-ce1cf680-960c-11ea-8d3f-da99254fb3f8.png">

Normally iOS suggestions are closed for those fields but i think it is a custom one.

**Comment by designsimply** [comment] 2020-05-19 23:21
@gglobalstep if you change the keyboard does the problem persist?

**Comment by gglobalstep** [comment] 2020-05-21 17:46
@designsimply Yes, the problem persist even after changing the keyboard. 

This issue is observed to be "Open" on following environment:
iOS- iPhone 6S (v13.4.1), iPhone 6(v12.4.4)
Build[version]: v14.9 

Attachment:
[#2230.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663904/2230.zip)

**Comment by pinarol** [comment] 2020-05-22 10:20
Thanks for the video. This keeps its mystery for me 🤔as I keep not being able to repro. @designsimply any chance you repro this? 

It can give a better clue if we can see the full steps that uses a normal keyboard instead of only the result step. @gglobalstep 

@lukewalczak can you also give it a try?

**Comment by gglobalstep** [comment] 2020-05-22 11:14
@pinarol  - The 2230.zip uploaded on 21st May was using iPhone 6s + 13.4.1 OS version. I updated the OS version to 13.5 and not able to reproduce. Tried multiple times.
Maybe @lukewalczak can give a try else we can close this issue. 
If we find this again, we shall comment on this bug accordingly. Please let us know if that's fine?

**Comment by lukewalczak** [comment] 2020-05-27 13:46
Hello! I was not able to reproduce it on the latest [build](https://github.com/wordpress-mobile/WordPress-iOS/pull/14192)>

Testing env:
iPhone XS
ios v: 13.4.1

**Comment by pinarol** [comment] 2020-06-09 13:56
> @pinarol - The 2230.zip uploaded on 21st May was using iPhone 6s + 13.4.1 OS version and Native Keyboard (Refer the video in the zip). I updated the OS version to 13.5 and not able to reproduce. Tried multiple times.
>Maybe @lukewalczak can give a try else we can close this issue.
>If we find this again, we shall comment on this bug accordingly. Please let us know if that's fine?


Sounds fine. Closing this accordingly. Let us know if you are able to repro again.

**Closed by pinarol** 2020-06-09 13:56 UTC
Labels: Beta Request, Blocks, [Status] Needs Author Reply, [Type] Bug
