### ISSUE TITLE
App Crashing as soon as a user adds text to a new post

### ISSUE THREAD

**Issue by sarahfg** [wordpress-mobile/gutenberg-mobile#2200] opened 2020-01-28 17:57 UTC
Steps to reproduce:
1. Tap the [+] button to add a new post
2. Start writing the title of a post like "The Fear Theory"

Results:
The user is able to get to 'Th' before the app freezes and displays the 'stopped working' message
They have tried uninstalling + reinstalling

WordPress - 13.9 - Version code: 811
Android device name: Samsung SM-G930F

#2633265-zen

<img src="https://user-images.githubusercontent.com/1119271/73485638-b1f89080-4360-11ea-9958-6518eb7b504a.png" width="270" alt="Annotation on 2020-01-28 at 13-41-55">

(Image link: https://d.pr/i/Bh4O9X )

**Comment by designsimply** [comment] 2020-04-28 22:04
I transferred this issue from `WordPress-Android` to `gutenberg-mobile` today. Please let me know if you find any unintended side effects of that!

**Comment by mkevins** [comment] 2020-06-04 12:24
I tried reproducing this crash by opening and closing the editor several times (also leaving chrome open with many tabs to consume memory, as well as using a low-memory emulator). I was not able to reproduce the crash though. I analyzed some of the memory leaks described and [posted my findings here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2214#issuecomment-638811940). I wonder whether this issue could also be related with the particular keyboard used for editing. :thinking: I tried using the Samsung keyboard (via apkmirror) within the emulator, but the keyboard itself was crashing (I don't think it is supported to use it that way, but in lieu of an actual Samsung device, it was worth a shot :smile: ).

**Comment by develric** [comment] 2020-11-09 12:40
Spent a bit of time here trying to replicate but was not able to. I tried the closer I could setup test scenario:

- WP Android 13.9
- Samsung Galaxy S5
- Android 6.0.1

I could replicate the issue Jirka mentioned above about memory leaks, but no luck in replicating the actual original reported crash when just typing a few characters (like the initial part of the reported sentence "The Fear Theory").

**Comment by mzorz** [comment] 2020-12-14 16:10
I tried the same as @develric  with what I had available to make a closes match possible:
- WPAndroid 13.9 downloaded from https://github.com/wordpress-mobile/WordPress-Android/releases/tag/13.9
- Samsung J2 Core (that's what I have)
- low battery (1% but connected, the screenshot from the user report shows 6% and plugged)
- changed the keyboard to use Portuguese as per what the screenshot shows
- started a draft with having the Me screen on (as can be seen on the screenshot as well)
- also observed the microphone (speech to text)  option was used recently in the screenshot so tried that as well (see the microphone on the left of the space bar)
- tried both entering text on the soft keyboard and using the microphone
- tried dismissing the keyboard while it was listening / using the keyboard toggle button on Gutenberg's toolbar.

Video showing this here https://cloudup.com/cGy_zIKImVm

I think we would probably be able to close this issue and instead follow @malinajirka's findings about memory leaks on this ticket https://github.com/wordpress-mobile/gutenberg-mobile/issues/2214#issuecomment-638811940 previously opened by @hypest , wdyt @designsimply ?

**Comment by antonis** [comment] 2021-04-16 16:30
I didn't manage to reproduce this either. I too think that [tracking down memory leaks](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2214) is our best bet on this.
I'm closing this as "non reproducible" (feel free to reopen if this is reported again).

**Closed by antonis** 2021-04-16 16:30 UTC
Labels: HACK week, [OS] Android, [Pri] High, [Status] Needs Android Dev, [Type] Crash
