### ISSUE TITLE
Gallery block outline overlaps block

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/gutenberg-mobile#5411] opened 2023-01-20 14:31 UTC
**Describe the bug**
Starting with WP/JP 21.5, when a new gallery block is added the outline overlaps with the main content of the block.
This is only occurring on Android, not iOS.

**To Reproduce**
1. In a new post, add a gallery block
2. Note misalignment of outline

**Expected behavior**
The outline should not overlap with the block itself.

**Screenshots**

![](https://user-images.githubusercontent.com/103850310/212409979-6d18fb23-d493-4a75-bd89-042d4d3261fe.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 13
 - Version WP/JP 21.5

**Additional context**
It appears to only happen if the gallery does not have any media selected.

**Comment by fluiddot** [comment] 2023-01-20 14:40
@lmischner thanks for reporting the issue 🙇 !

[We already fixed this issue](https://github.com/WordPress/gutenberg/pull/47086) and incorporated it into version `21.5` via a beta fix. It was included in `21.5.0.1` ([reference](https://github.com/wordpress-mobile/WordPress-iOS/pull/19911)), would you mind checking this in the latest version of `21.5` to confirm it's fixed? Thanks!

**Comment by lmischner** [comment] 2023-01-20 15:04
Ah, thanks for letting me know, @fluiddot ! It seems likely I don't have the fix yet. 
I'm only able to find `21.5-rc-1`, which is where I'm seeing the issue.

**Comment by geriux** [comment] 2023-01-20 15:12
It looks like there was [only one](https://github.com/wordpress-mobile/WordPress-Android/releases) release candidate for WordPress Android `21.5`.

**Comment by fluiddot** [comment] 2023-01-20 15:15
> Ah, thanks for letting me know, @fluiddot ! It seems likely I don't have the fix yet.
> I'm only able to find `21.5-rc-1`, which is where I'm seeing the issue.

> It looks like there was [only one](https://github.com/wordpress-mobile/WordPress-Android/releases) release candidate for WordPress Android 21.5.

Ah, that probably explains why this issue is only showing up on Android. Let's see if a new build is generated to confirm that the issue was addressed.

**Comment by fluiddot** [comment] 2023-01-25 12:20
@lmischner WordPress-Android version `21.5` has been just released. I tried to reproduce it and confirm it's not happening, as we expected and mentioned in [this comment](https://github.com/wordpress-mobile/gutenberg-mobile/issues/5411#issuecomment-1398542632). I'll close this issue for now, but please let us know if you manage to reproduce it in the latest production version. Thanks!

**Closed as completed by fluiddot** 2023-01-25 12:20 UTC
Labels: [Type] Bug, [OS] Android, Gallery block
