### ISSUE TITLE
Gallery Block - Animation Settings make Images Unviewable in Editor

### ISSUE THREAD

**Issue by NoHopeRadio** [wordpress-mobile/gutenberg-mobile#2737] opened 2020-10-17 00:13 UTC
**The Issue**
When an animation is added to a gallery block that had previously appeared in the editor on iOS, when viewed in the editor again, all that can be seen is a gray block that says, "Gallery - Problem Displaying Block." This seems like an unexpected behavior. In contrast, the iOS app does not display the filter options, but it continues to display the original images when those options are selected.

**To Reproduce**
1. Add an image gallery.
2. Confirm that it displays on iOS.
3. Add the animation option from the Gallery Block settings on browser.
4. Confirm that it does not display on iOS.

**Expected behavior**
Animations do not display within the editor, and although these settings cannot be toggled from this view, it doesn't seem like it should entirely obscure the whole block as well. I expected to see the same images as before.

**Screenshots**
![IMG_5320](https://user-images.githubusercontent.com/71042895/96323437-1e98e580-0feb-11eb-96e4-6ecef108c3b4.PNG)

**Smartphone (please complete the following information):**
 - Device: [iPad 6th Generation]
 - OS: [iOS 14.0.1]
 - Version iOS 15.9

**Additional context**
This is a pretty minor issue about a tiny feature that most people won't use and even fewer should, but I hoped it wouldn't be too difficult to fix.

**Comment by chipsnyder** [comment] 2021-02-10 21:42
Hi @NoHopeRadio I pulled up this issue but I think I might be missing a step. When I look at the definition for the [gallery block](https://wordpress.org/support/article/gallery-block/) I don't see a reference to the `animation option from the Gallery Block settings on browser` that you mention. Can you provide some guidance on what animation settings you're using?

**Comment by NoHopeRadio** [comment] 2021-02-11 02:27
Looking more closely, I see that the animation feature is an add-on from the CoBlocks plugin built in to Atomic sites, though that plugin also adds photo filters (grayscale, sepia, etc.) which, when applied, do not create this same behavior.

**Comment by chipsnyder** [comment] 2021-02-11 13:15
Thank you for confirming @NoHopeRadio! I see the option now and was able to recreate it. I'll remove the iOS flag as this seems to be an issue on the ReactNative side.

**Comment by antonis** [comment] 2022-01-24 10:42
Closing this as I wasn't able to reproduce the issue with the new Gallery block implementation. Please reopen if that is not the case.

**Closed as completed by antonis** 2022-01-24 10:42 UTC
Labels: [Type] Bug
