### ISSUE TITLE
Gallery Block failing to upload images

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2956] opened 2021-01-04 20:49 UTC
**Describe the bug**
Images are failing to upload sometimes when uploading the image and closing the editor. 

**To Reproduce**
- Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- Gallery block - Try adding same images from WP Media library and moving the images around - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)
    - Try uploading new images instead of using ones from the library.

**Expected behavior**
Images should upload successfully

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 14
 - Version 16.3

**Additional Context**
I was able to reproduce this 75% of the time. Sometimes I needed to add to an existing gallery.

**Comment by mkevins** [comment] 2021-01-05 09:52
I've begun looking into this, and managed to reproduce it. At first I was unable to reproduce it, since it seems that the upload completion was handled correctly if the editor was opened prior to the upload completing. I reproduced it reliably by leaving the editor closed when the upload completed. I also noticed that there was an error message associated with the failed media upon opening the editor, after the upload failed, indicating a timeout had occurred after `30001 milliseconds`.

I will continue by debugging the processors code.

**Comment by mkevins** [comment] 2021-01-06 10:02
I'm not sure what changed since yesterday, but I haven't been able to reproduce this today. I re-tried everything I had tried yesterday, but every time the image upload completed successfully, and the URL was updated properly. I tried several times with different "timings" of when I re-opened the editor (after upload finished, right before it finished, long before it finished, etc.) and nothing seemed to reproduce it again. Now I'm wondering whether the issue could have been an intermittent server issue, where the completion response timed out :thinking: .

Chip, are you still able to reproduce this?

**Comment by chipsnyder** [comment] 2021-01-06 18:08
Hey @mkevins 

I was able to repro this still although not reliably. 

Here's a video of when I was able to reproduce it. (It took a couple of tries) https://cldup.com/MPtxCuUn1b.mov

In this attempt, I added to a gallery block, closed the editor, opened the editor, closed and opened again. Although the original report was that they were moving images around. I haven't been able to reproduce with those steps yet.

<kbd><a href="https://user-images.githubusercontent.com/3384451/103804412-15cf1300-5020-11eb-8e8a-e65e516a29fd.png"><img width="300" src="https://user-images.githubusercontent.com/3384451/103804412-15cf1300-5020-11eb-8e8a-e65e516a29fd.png"/></a></kbd>
The circled image failed to upload

**Comment by hypest** [comment] 2021-01-08 06:22
Only reports so far are on iOS so, adding the [iOS] label.

**Comment by mkevins** [comment] 2021-01-08 06:45
> Only reports so far are on iOS so, adding the [iOS] label.

I've found steps to reliably reproduce this on iOS, and those same steps do not exhibit the issue on Android. These steps _do_ exhibit the issue in a prior version of iOS (16.3).

#### Steps

* Add a Gallery block to a post
* Add media from device (a single image is enough)
* While media is uploading, exit the editor (saving / updating post when prompted)
* Observe the upload progress on the post card in the post list
* Just as the progress reaches 100%, tap to open the post in the editor
* As the editor opens, close the editor quickly

After these steps, the post card becomes stuck in a state "Uploading media...":

<img src="https://user-images.githubusercontent.com/8507675/103983145-85840000-51d0-11eb-82d3-2d4e42964ddc.png" width="360">

Then, editing the post, the image is blurry, and viewing the html, the `src` begins with `file:///` indicating it is still referencing the local image. After exiting the post again, the post card indicates "local changes":

<img src="https://user-images.githubusercontent.com/8507675/103983227-a187a180-51d0-11eb-9587-3ef05d5f0e84.png" width="360">

The above issue is also reproducible for Image block (though the image is not blurry).

**Comment by mkevins** [comment] 2021-01-08 11:45
I spent some more time debugging this, and I've confirmed that the processors are not running after the steps listed above (even after leaving the editor). At first I had a theory that the events are deferred properly (i.e. responsibility for updating the image ids and URLs is "handed off" to the RN editor), but if we close the editor before the queue can be processed, the editor closes without saving. I'm not convinced yet about this theory, since the progress bar shows (albeit briefly) in the small moment while the editor is open, and it is at 100%, so the component either somehow received the completion event, or it received one of the last progress events. Also, when logging this, I noticed that the tracks event for `media_serivce_upload_successful` occurred _after_ the `editor_closed` event.

I also tried logging the queued events, and it seems that there is a single event that fires in the steps that exhibit the issue. This deferred event seems to be emitted even for an empty post, when the editor is first loaded. Another possibility is that whatever listener is bound to this initial event is blocking the queued events (on the JS side) and the editor closes before processing the rest of them.

**Comment by mkevins** [comment] 2021-01-08 12:03
#### Some more info on the debugging

I added some logs for the while loop that flushes the event queue, and when I leave the editor, and then reopen it allowing a successful completion, I get the following:

```
2021-01-08 21:52:21.927825+1000 WordPress[942:898317] emitting deferred event: updateCapabilities => {
    canEnableUnsupportedBlockEditor = 1;
    mentions = 1;
    modalLayoutPicker = 1;
    unsupportedBlockEditor = 0;
}
2021-01-08 21:52:21.928530+1000 WordPress[942:898317] emitting deferred event: mediaUpload => {
    mediaId = 855907894;
    progress = "0.4476752";
    state = 1;
}
2021-01-08 21:52:41:850 WordPress[942:898317] 🔵 Tracked: media_service_upload_successful <blog_id: 159258778>
```

Note that there is almost no delay between the two deferred events (I think this rules out the possibility that the first event, `updateCapabilities`, was blocking things).

However, when I follow the steps above and get a failure, I see the following:

```
2021-01-08 21:53:27.334571+1000 WordPress[942:898317] emitting deferred event: updateCapabilities => {
    canEnableUnsupportedBlockEditor = 1;
    mentions = 1;
    modalLayoutPicker = 1;
    unsupportedBlockEditor = 0;
}
2021-01-08 21:53:27:706 WordPress[942:898317] 🔵 Tracked: editor_session_end <blog_type: jetpack, content_type: gutenberg, editor: gutenberg, has_unsupported_blocks: 0, outcome: cancel, post_type: post, session_id: 6FDF9B5F-BF4D-4017-B0EF-6890988A3DBC>
2021-01-08 21:53:27:732 WordPress[942:898317] 🔵 Tracked: editor_closed <blog_id: 159258778, editor_source: gutenberg, has_gutenberg_blocks: 1>
2021-01-08 21:53:28.372677+1000 WordPress[942:898317] Invalidating RCTSampleTurboModule...
2021-01-08 21:53:30:797 WordPress[942:898317] 🔵 Tracked: media_service_upload_successful <blog_id: 159258778>
```

Note that there are no `mediaUpload` events processed in the queue. I think this means that the problem is a gap in when the processors resume responsibility for the upload completion when the editor closes.

**Comment by chipsnyder** [comment] 2021-01-08 22:05
Thank you for these updates @snapfractalpop!  

> Note that there are no mediaUpload events processed in the queue. I think this means that the problem is a gap in when the processors resume responsibility for the upload completion when the editor closes.

I agree, based on the repro steps and these logs; this seems like it's the area we need to investigate.

Dropping this to medium as the steps here seem to need precise timing, although I would like us to keep investigating.

**Comment by mkevins** [comment] 2021-01-12 10:40
I spent a small amount of time today doing some further debugging, and discovered two things of interest. One is that it seems the observer [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/03742949c43ea54fa8262270d44d734bb719a78c/WordPress/Classes/Services/PostCoordinator.swift#L156) does not get called for the media upon completion in the failure case.

The second thing I noticed is that the number of observers in [`mediaCoordinator.observersForMedia(media)`](https://github.com/wordpress-mobile/WordPress-iOS/blob/03742949c43ea54fa8262270d44d734bb719a78c/WordPress/Classes/Services/MediaCoordinator.swift#L622) seems to increase upon opening and closing the editor, without decreasing. I'm not sure if this is expected, or whether this indicates that there is some necessary cleanup that is not occurring (a leak perhaps?).

**Comment by chipsnyder** [comment] 2021-01-13 17:06
> the observer here does not get called for the media upon completion in the failure case.

That seems odd that we aren't calling the observer there. It feels like we test out what happens if we add that completion call back there.

> a leak perhaps?

This seems likely and maybe the editor is getting "mixed signals" from the state of different observers. 

One thing I find strange is that we lazy load `mediaPickerHelper`and `mediaInserterHelper` but then also set them when we set the Post. I wonder if this is causing a conflict?
[reference](https://github.com/wordpress-mobile/WordPress-iOS/blob/f59d751e9ce6669b3afbc69071a8d426dbe31929/WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift#L213-L237)

It does[ look like](https://github.com/wordpress-mobile/WordPress-iOS/blob/f59d751e9ce6669b3afbc69071a8d426dbe31929/WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift#L27) we remove the observer on `deinit` so a leak seems likely

**Comment by mkevins** [comment] 2021-01-18 00:04
On further investigation, it turns out the steps to reproduce the issue are simpler than I originally thought. The timing does not have to be so precise, so I resumed investigating as a higher priority.

It seems that the underlying cause is that the processors are invoked from the save mechanism when leaving the editor, but not when the user does not save. When the media is added initially, the post is changed, and a prompt to save / update is presented when closing the editor. When the post is re-opened for editing and subsequently closed (prior to the media upload completion), there are no new changes, and the editor closes without a prompt. This results in a failure to properly handle the completion.

#### Simpler steps to reproduce the issue

* Add a media-containing block to a post (Image block is sufficient)
* Add media from device (a single image is enough)
* While media is uploading, exit the editor (saving / updating post when prompted)
* Open the post in the editor again (it is _not necessary_ to wait until 100% upload progress as described previously)
* Close the editor
* Allow the media to finish uploading
  * Observe the upload progress on the post card in the post list

This was a bit elusive to detect, since it is actually possible to exit and re-open the editor several times (I closed and re-opened 7 times in one case) and still have the upload completion handled successfully. This will be the case if the editor is opened during the completion. Even the deferred events are working as expected.

#### Another possibly related issue

Another issue I observed while testing is that the post card shows stale text after the post is finished uploading. In the video below, I added a second word "test" to the post, and it is reflected immediately in the post card after exiting the editor (and saving). However, after the post upload is complete, the summary in the post card "reverts" to the previous text. Also, for a very brief moment, upon tapping to re-open the post, the text in the card refreshes to reflect the latest state.


https://user-images.githubusercontent.com/8507675/104859944-6de90c00-5974-11eb-8c73-87fc900faef3.mov


This is possibly related in that it exhibits an invalid or stale state after the editor is closed and upload completes.

#### Solution

I've [drafted a PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/15656) which "fixes" the issue with upload completion handling, ensuring the processors are called. However, the changes introduce a new issue where, after the upload completes outside the editor, the user re-opens the post, and subsequently leaves without making changes, they are prompted to save changes (which is confusing). It seems that the mechanism to save / update the post is missing some step, or somehow the `post` and the `post.original` are out of sync.

I think this could use some input from others that are more familiar with how the code around revisions is intended to function. I tried a few combinations (e.g. save and publish), but I couldn't seem to avoid introducing this secondary issue with a solution for the first issue.

**Closed as completed** 2021-02-01 00:58 UTC
Labels: [Type] Bug, [OS] iOS, [Type] Regression, [Pri] Medium
