### ISSUE TITLE
Tapping on a Page Break block does make the block-holder selected but keep the keyboard up, and the caret to the Para block

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#308] opened 2018-11-30 17:09 UTC
This is related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/306 - This time the selection of Page Break block happens by the "user" with the cursor/tapping, instead of programatically like in #306, but the end result is the same.

Steps to repro:
- Tap on a para block
- Tap on the page break block
- The block holder is selected, but the soft keyboard is still up, and the caret blinking in the previous para block
- If you tap on the keyboard characters are inserted in the para block

**Comment by hypest** [comment] 2018-12-03 08:30
Added this to the Alpha milestone but it's not a blocker for the Alpha.

**Comment by koke** [comment] 2018-12-04 18:03
I think this is a duplicate of #197?

> When a non textual block (e.g. image, more) is selected, hide the keyboard.

I think we want this for the alpha, focus should follow the selected block, it's really confusing when it doesn't

**Comment by daniloercoli** [comment] 2018-12-19 10:41
The tentative fix for this issue is available here: https://github.com/WordPress/gutenberg/pull/12765
but then reverted since introduced a problem with the Keyboard dismissed when tapping Enter. Details: https://github.com/wordpress-mobile/gutenberg-mobile/issues/381#issuecomment-447405111

**Comment by daniloercoli** [comment] 2018-12-19 11:16
As per chat convo, this here https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L46 should be the right direct to go (removes the nasty side effect that EditTexts have, which is that focus is always maintained on one of the EditTexts).

**Comment by koke** [comment] 2018-12-19 12:47
> removes the nasty side effect that EditTexts have, which is that focus is always maintained on one of the EditTexts

For reference, I think I managed to work around that by adding this in the app:
https://gist.github.com/koke/b572a7c4e203bf92c50d7c57b614e82c

However that didn't solve the keyboard being dismissed. I think the logic was right to dismiss the keyboard from RichText on split, but then the new block wasn't regaining focus. My hypothesis is that we handle the focus on `componentDidUpdate`, which won't get called since it's a newly created component, not an update to an existing one. We might have to replicate some of it on `componentDidMount`, but I haven't tested any of that.

**Closed** 2018-12-19 16:38 UTC
