### ISSUE TITLE
Content doesn't scroll to new paragraph upon inserting one

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1881] opened 2020-02-12 08:13 UTC
**Describe the bug**
UI doesn't scroll to the new block at the end of the context, when there is enough content already to fill the screen.

**To Reproduce**
1. Open the demo app on Android
2. Don't put the caret/focus anywhere
3. Tap on the Inserter ("+") and add a new paragraph block
4. Notice that the UI doesn't scroll to the end of the content where the new block was appended

**Expected behavior**
The UI should scroll to the new block at the end of the content when adding one and the UI is not already at the end.

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 10
 - Version replicated at least on v1.20.0 and v1.21.0 and v1.22.0

**Additional context**

**Comment by guarani** [comment] 2020-02-21 16:30
@hypest, this looks like the same issue as: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1672

**Comment by hypest** [comment] 2020-02-28 12:08
> @hypest, this looks like the same issue as: #1672

Thanks for the pointer @guarani. Looks like the two are not quite the same issue since 1672 is about what happens before the block is inserted while this one is for after the block is added.

Most probably, fixing 1672 will alleviate this one too, but since the vertical height of the insertion point marker is way smaller than most of the blocks, this ticket will still be valid and we'll need to scroll to a reasonable position to show most or all of the new block. Let's keep both tickets open, but it's obvious that they are related. WDYT?

**Comment by guarani** [comment] 2020-02-28 17:43
> Let's keep both tickets open, but it's obvious that they are related. WDYT?
Yes, upon rereading they are indeed different, thanks for pointing this out 👍

**Comment by mchowning** [comment] 2020-03-13 21:21
Did some investigation into this but I got pulled into some other things before I was able to implement a fix, so leaving some notes of what I found: 

The issue can be recreated on  any sufficiently long post even if a block is in focus (it does not only occur when loading the editor):
1. Focus a block at the end of a long post (the demo post is long enough)
2. Scroll to the beginning of the post (without removing focus from the block at the end of the post)
3. tap the inserter and insert a new block
4. Note that focus does not shift to the end of the post
5. Start scrolling to the end of the post and note that at some point the newly added block will become focused and the screen will jump to the end of the post.

The cause of the issue appears to be that the newly added block is not rendered if it is not either on screen or relatively close to being on screen in the `FlatList`. As you scroll toward the newly added block, it eventually gets close enough to the viewable area to be rendered, at which point [its `componentDidMount` function](https://github.com/WordPress/gutenberg/blob/34fa8b2a481693bd75ab3b96aafd004c5ecbfd91/packages/rich-text/src/component/index.native.js#L595-L610) is called, which then calls through to `this._editor.focus()` and focuses the block.

**Comment by guarani** [comment] 2020-11-02 21:50
I tested this and it looks like either the original issue is resolved or the steps to reproduce need to be updated.

Here's why:
1. On the Gutenberg demo app, I followed to the letter the steps to reproduce and the editor always scrolled to the newly inserted Paragraph block (couldn't reproduce on Android or iOS)
2. I tried the same steps, but instead of having no block selected I left the last block in the editor selected — same result, couldn't reproduce on either platform
3. The editor **does not** scroll when I insert an Image, Video (or any other block that does not try to gain keyboard focus on insertion) — **reproducible on Android and iOS**
4. If I scroll to the bottom of a long post (e.g. demo app sample content), focus the last Paragraph block and attempt to scroll up to the top of the editor content while the keyboard is open, it's nearly impossible because the editor jumps back down to the focused Paragraph — **only reproducible on Android**. @mchowning when performing Step 2 of https://github.com/wordpress-mobile/gutenberg-mobile/issues/1881#issuecomment-598916685, do you recall running into this or have you ever experienced this behavior? 

@hypest, do you think this issue a) should be closed as non-reproducible, b) is still reproducible for y'all (maybe I'm having trouble reproducing), or c) should be edited to specify in the steps to reproduce that a block that doesn't auto-focus on insertion (e.g. Image, Video, etc) must be used instead of a Paragraph block in order to reproduce this?

**Comment by hypest** [comment] 2020-11-03 11:14
I replicated all your findings there @guarani . I made the title of this ticket more specific (to paragraphs).

It does seem that non text-input blocks do not scroll. Since this ticket is rather old, let's close it and, can you create new ones:
1. for the non text-input blocks not scrolling
2. text-input fields stealing the scroll position?
Thanks!

**Comment by guarani** [comment] 2020-11-03 13:24
> I replicated all your findings there @guarani . I made the title of this ticket more specific (to paragraphs).

Thanks for checking @hypest! 

Created https://github.com/wordpress-mobile/gutenberg-mobile/issues/2773 and https://github.com/wordpress-mobile/gutenberg-mobile/issues/2774 and added the "Hack week" label to both.

**Closed by guarani** 2020-11-03 13:24 UTC
Labels: HACK week, Writing Flow, [Type] Bug
