### ISSUE TITLE
"Escape" key event closes add block bottom sheet without removing "Add Block Here" indicator

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1224] opened 2019-07-12 18:31 UTC
### "Add Block Here" (ABH) indicator remains if dismissed via "escape" key

On Android, sending the escape key to the device when the add block bottom sheet open closes the bottom sheet without removing the "Add Block Here" indicator. Tapping the screen a few times after this seems to generally dismiss the stray ABH indicator, but I have also seen the editor get into weird states where the ABH indicator will then come back while typing.

![Screen Capture on 2019-07-12 at 14-00-08 gif](https://user-images.githubusercontent.com/4656348/61149964-55ab4d80-a4b0-11e9-9df7-38281da72ef7.gif)

### State after ABH indicator is not dismissed

Tapping the screen a few times after this seems to generally dismiss the stray ABH indicator, but I have also seen the editor get into weird states where the ABH indicator will stay/come-back while typing. One fun example:

![top-bottom-abh mp4](https://user-images.githubusercontent.com/4656348/61149678-b5edbf80-a4af-11e9-8d6a-b77501e56b67.gif)

### How I Tested This

I do not have a bluetooth keyboard, but I have recreated this issue on an emulator and a physical device by (a) sending the [escape key](https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_ESCAPE) to the device via adb (`adb shell input keyevent 111`); or (b) using the escape key of the keyboard connected to my computer (with the physical device I was projecting the screen to my computer using [scrcpy](https://github.com/Genymobile/scrcpy)).

⚠️ I think it would be a good idea for someone with a bluetooth keyboard to confirm this behavior because a user is only likely to encounter this issue if it also occurs with keyboards connected directly to the phone (as opposed to the key commands being sent via computer like I have done).

I was not able to recreate this issue on iOS.

**Comment by hypest** [comment] 2019-07-16 10:14
FWIW, not able to reproduce it with a usb keyboard attached to my Galaxy S7 or Galaxy Tab S2. In both devices I tried WPAndroid v12.9-rc-1 and hitting the ESC key on the external keyboard makes both the Inserter and the "ADD BLOCK CLEAR" marker to dismiss.

Unfortunately, my bluetooth keyboard doesn't have an ESC key to try out (and key combinations like CTRL-D or CTRL-[ didn't seem to work either).

**Comment by hypest** [comment] 2019-11-29 17:35
Is this still happening for you @mchowning ? Let's close this if not.

**Comment by mchowning** [comment] 2019-12-02 14:49
@hypest I just recreated this bug using a physical bluetooth keyboard (Logitech K380) on both
* Pixel 3, Android 10, alpha-198 (updated 11/20/19 on Google Play Store) of the app; and
* Pixel, Android 10, demo app built from the v1.18.0 tag.

**Comment by hypest** [comment] 2020-06-11 15:13
Not happening for me anymore, at least on 7495fbf3. Closing this but, let's reopen if it's still happening for others.

**Comment by mchowning** [comment] 2020-06-11 15:29
I just recreated the issue with the jalapeno build for testing the 1.30 release (c2a85e0), which is later than the  7495fbf commit you tested with @hypest . I'll go ahead and reopen this, but if anyone else tests this and cannot reproduce the issue then let's go ahead and close this.

**Comment by SiobhyB** [comment] 2024-02-09 17:56
I haven't been able to reproduce in the latest version (24.2). As we haven't had additional reports in three and half years, I'll go ahead to close this issue.

**Closed by SiobhyB** 2024-02-09 17:56 UTC
Labels: [Type] Bug, [OS] Android, Project: Flow improvements, [Pri] Low
