### ISSUE TITLE
JSApplicationIllegalArgumentException: Error while updating property 'text' of a view managed by: RCTAztecView

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/gutenberg-mobile#2472] opened 2020-07-09 05:57 UTC
I am still figuring out how to monitor crashes from the JS side. This one in particular seems to have at least some info about what it's related to, specifically with the `parentStyle must not be null` message.

Please let me know if I should be on the lookout for anything specific for these type of issues so I can use that to decide whether an issue is worth reporting or how best to report it etc.

**Sentry Url**: https://sentry.io/share/issue/9c56a9ad3cb84f9a865e4462cf4925ff/
**User Count**: 298
**Count**: 700
**First Release**: org.wordpress.android-14.0
**First Seen**: 2020-02-03T09:35:53Z
**Last Seen**: 2020-07-09T05:45:18Z
**24 Hours**: 4
**30 Days**: 133

```
JSApplicationIllegalArgumentException: Error while updating property 'text' of a view managed by: RCTAztecView

...
(18 additional frame(s) were not displayed)
```

**Comment by hypest** [comment] 2020-07-09 10:17
> parentStyle must not be null

Looks like a crash coming from the embedded Aztec instance and by quickly looking at the code we should be able to guard for this case. I'll put a "medium" priority on this ticket since the occurrences are fairly low in the last month.

**Comment by hypest** [comment] 2020-07-31 11:44
https://github.com/wordpress-mobile/gutenberg-mobile/issues/2524 has steps to reproduce, and also connected to a support thread so, will keep both tickets open. Let's just remember to close both when this gets fixed.

**Comment by AmandaRiu** [comment] 2021-08-06 00:28
Tested on a Pixel 4 running Android 11 and WPAndroid v17.9. **Unable to reproduce crash**. I did some digging and the crash was last reported in Sentry for v15.7 of WPAndroid. With further digging I found this Aztec PR that implemented the fix: https://github.com/wordpress-mobile/AztecEditor-Android/pull/923

I've marked the associated Sentry events as resolved, and am closing this ticket.

**Closed by AmandaRiu** 2021-08-06 00:28 UTC
Labels: [Type] Crash, [Pri] Medium
