### ISSUE TITLE
Modal Layout Picker: layout preview creates duplicate page

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2797] opened 2020-11-11 07:28 UTC
Steps to reproduce:

1. Go to My Site > Site Pages > + and select any layout.
1. Tap Preview at bottom left.
1. Tap the Create page button.
1. Make some changes to the title and content.
1. Tap the back arrow at top left.

**Result:** a page with the changes is present but there's also a duplicate page with the same template but without a title. (WP.com Premium: [3m56s](https://cloudup.com/c2M8KoqCfqE), Jetpack: [2m59s](https://cloudup.com/cdXun5pal5t), Self-hosted: [5m20s](https://cloudup.com/cITcPB7eRMc))

Also:

1. Go to My Site > Site Pages > + and select any layout.
1. Tap Preview at bottom left.
1. Tap the back arrow at top left.

**Result:** a duplicate page is created but disappears if you pull to refresh.

<img src="https://user-images.githubusercontent.com/1119271/98782110-a5f03380-23b4-11eb-86c8-a43343edd3a6.png" width="300" alt="Screen Shot 2020-11-11 at Nov 11 12 26 07 AM">

<sup>Tested with WPAndroid 16.1-rc-1 on Pixel 3 Android 11.</sup>

**Comment by antonis** [comment] 2020-11-11 08:41
Hello @designsimply 👋 
Thank you for reporting this. I really appreciate it.
Please check my comments inline your message.

> Steps to reproduce:
> 
> 1. Go to My Site > Site Pages > + and select any layout.
> 2. Tap Preview at bottom left.
> 3. Make some changes to the title and content.

You should not be able to make changes in preview mode. If that's not the case I need to investigate further.
If you pressed *Create page* after step 2 this is normal.

> 4. Tap the back arrow at top left.
> 
> **Result:** a page with the changes is present but there's also a duplicate page with the same template but without a title. ([3m56s](https://cloudup.com/c2M8KoqCfqE), [2m59s](https://cloudup.com/cdXun5pal5t), [5m20s](https://cloudup.com/cITcPB7eRMc))

A temporary local page is created while previewing. This should be already deleted when you exit the editor.
I've recorder what I'm seeing [here](https://cloudup.com/cNM9xxEz3BU). Let me know if you follow slightly different steps or you are still able to reproduce this on your device 😕 


> Also:
> 
> 1. Go to My Site > Site Pages > + and select any layout.
> 2. Tap Preview at bottom left.
> 3. Tap the back arrow at top left.
> 
> **Result:** a duplicate page is created but disappears if you pull to refresh.

I'm experiencing the same issue here ([recording](https://cloudup.com/cfPcebdRcog)). I'll try to force a refresh in that case.
Since I'm using the editor for generating the preview I'm not able to prevent the creation of a local preview copy completely (without major changes to the editor). @malinajirka reported this while reviewing the preview functionality [here](https://github.com/wordpress-mobile/WordPress-Android/pull/13022#issuecomment-707171189).

**Comment by designsimply** [comment] 2020-11-11 09:00
> You should not be able to make changes in preview mode. If that's not the case I need to investigate further.

Correct, I was not able to make changes in preview mode. 👍

The main problem is that _if_ I preview _before_ I create the page then a duplicate is created that does not have a title and does not disappear even after a pull-to-refresh. I did another test from a different account and got the same result. I tried with two different templates and tested modifying content as well as only modifying the title only: [1m43s](https://cloudup.com/cCS8CYfdGhX), [1m5s](https://cloudup.com/cQwlGO-vsrd). Tested using a WordPress.com Free site that was created on 2020-11-06.

Note: I'm testing with 16.1-rc-1, have you tried with that [apk](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/16.1-rc-1)? Has the problem perhaps been resolved in a later release candidate already and I need to update?

**Comment by antonis** [comment] 2020-11-11 09:03
Thank you for the prompt feedback @designsimply 🙇 

> Note: I'm testing with 16.1-rc-1, have you tried with that apk? Has the problem perhaps been resolved in a later release candidate already and I need to update?

I tested with this release. I'll investigate this further.

**Comment by antonis** [comment] 2020-11-11 11:39
Hello @designsimply 👋 
You can find a patch for this at https://github.com/wordpress-mobile/WordPress-Android/pull/13358
If you have the time please validate that this [build](https://github.com/wordpress-mobile/WordPress-Android/pull/13358#issuecomment-725374655) works on your setup too.
Thank you 🙇

**Comment by antonis** [comment] 2020-11-12 12:25
Fix merged in 16.1 https://github.com/wordpress-mobile/WordPress-Android/pull/13363 and dev https://github.com/wordpress-mobile/WordPress-Android/pull/13358

**Closed as completed by antonis** 2020-11-12 12:25 UTC
Labels: [Type] Bug, Beta Request, Page Templates
